// ===== CLASSEMENTS EN LIGNE (saisons d'une semaine, récompenses du top 10) ET HÔTEL DES VENTES ENTRE JOUEURS =====
PARTS.paint.o.laurier={n:'Laurier de champion',p:0,uniq:1,d:'Or vif et vert laurier : réservée aux champions d\'une saison.',c:[0xf2c230,0x1f6b3a,0xfff1a0]};
function isoWeek(d=new Date()){const t2=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));const day=t2.getUTCDay()||7;t2.setUTCDate(t2.getUTCDate()+4-day);const y=t2.getUTCFullYear();const w=Math.ceil(((t2-Date.UTC(y,0,1))/864e5+1)/7);return y+'-W'+String(w).padStart(2,'0')}
function seasonLeft(){const d=new Date(),day=(d.getUTCDay()+6)%7,end=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()-day+7);return end-Date.now()}
const SEA=GX('sea',{});
function seaCheck(){const id=isoWeek();if(SEA.id!==id){SEA.id=id;SEA.earn=0;SEA.kills=0;SEA.disc=0;SEA.race=0;save()}}seaCheck();
// ----- compteurs de la saison -----
const SEAW={cr:null,d:null};TICK.push(()=>{if(SEAW.cr==null||G.ecoReset)SEAW.cr=G.cr;if(G.cr>SEAW.cr)SEA.earn+=G.cr-SEAW.cr;SEAW.cr=G.cr;const d=G.disc.size+Object.keys(CX.sp).length+Object.keys(ANK).length+STS.ders;if(SEAW.d==null)SEAW.d=d;if(d>SEAW.d)SEA.disc+=d-SEAW.d;SEAW.d=d});
{const _he=hitEnemy;hitEnemy=function(e,dm,p){const was=e.dead;_he(e,dm,p);if(!was&&e.dead)SEA.kills++}}
{const _re=raceEnd;raceEnd=function(ok){const R=RC.on;_re(ok);if(ok&&R&&R.C.id=='Base Alpha'){const tm=+R.t.toFixed(2);if(!SEA.race||tm<SEA.race)SEA.race=tm}}}
{const _dd=droneDie;droneDie=function(d){_dd(d);SEA.kills++}}
// ----- classement -----
const BRD={cat:'riche',data:null,busy:false,last:'',t:-1e9,msg:''};
const BCAT={riche:['Fortune','coin',v=>fmt(Math.round(v))+' ¢','Crédits gagnés cette semaine'],chasse:['Chasseurs','target',v=>fmt(v)+' ennemis','Ennemis abattus cette semaine'],explo:['Explorateurs','planet',v=>fmt(v)+' découvertes','Planètes, espèces, anomalies, épaves'],course:['Course','race',v=>tfmt(v),'Meilleur temps — circuit de la Base Alpha'],niveau:['Pilotes','star',(v,lv)=>'Niv. '+lv+' · '+fmt(v)+' XP','Expérience totale']};
const bName=()=>(typeof MP!='undefined'&&MP.nick)||'Pilote';
function bVals(){return{riche:Math.round(SEA.earn),chasse:SEA.kills,explo:SEA.disc,course:SEA.race||0,niveau:Math.round(G.xp||0),lv:lvl()}}
async function boardPost(force){if(!API_OK||BRD.busy)return;seaCheck();const body={code:CLOUD.code,n:bName(),ti:G.x.title||'',v:bVals()},k=JSON.stringify(body);if(!force&&k===BRD.last)return;BRD.busy=true;try{const r=await api('/api/board',body);BRD.last=k;if(r&&r.top){BRD.data={season:r.season,top:r.top,me:r.me,n:r.n};BRD.t=Date.now();if(CXP.open&&CXP.tab=='board')cxRender()}}catch(e){BRD.msg='Classement injoignable pour l\'instant'}BRD.busy=false}
async function boardFetch(){if(!API_OK||BRD.busy||Date.now()-BRD.t<15000)return;BRD.busy=true;try{const r=await api('/api/board?season='+encodeURIComponent(SEA.id)+'&code='+encodeURIComponent(CLOUD.code));BRD.data=r;BRD.t=Date.now();BRD.msg=''}catch(e){BRD.msg='Classement injoignable pour l\'instant'}BRD.busy=false;if(CXP.open&&CXP.tab=='board')cxRender()}
function boardHTML(){const lt=seasonLeft(),dd=Math.floor(lt/864e5),hh=Math.floor(lt/36e5)%24,C=BCAT[BRD.cat],V=bVals();let h=`<div class="psec"><b class="pt">Saison ${SEA.id} · fin dans ${dd} j ${hh} h</b><small>Le top 10 de chaque catégorie est récompensé à la fin de la semaine (jusqu'à 4 000 ¢). La 1<sup>re</sup> place gagne le titre « Champion de la saison » et la peinture Laurier.</small>
<div class="cxtabs bcat">${Object.entries(BCAT).map(([k,c])=>`<button data-bc="${k}" class="${BRD.cat==k?'on':''}" title="${c[0]}">${ICO(c[1])}<span>${c[0]}</span></button>`).join('')}</div></div>`;
h+=`<div class="psec"><b class="pt">${ICO(C[1])} ${C[0]} — ${C[3]}</b>`;if(!API_OK)h+='<small>Les classements en ligne fonctionnent sur le jeu publié (starvody.netlify.app). Tes scores de la semaine sont comptés ici quand même :</small>';
else if(!BRD.data)h+=`<small>${BRD.msg||'Chargement…'}</small>`;else{const L=(BRD.data.top||{})[BRD.cat]||[];if(!L.length)h+='<small>Personne n\'est encore classé : à toi de jouer !</small>';L.forEach((x,i)=>{h+=`<div class="brow${x.me?' me':''}"><b>${i+1}</b><span>${esc(x.n)}${x.ti?` <i>« ${esc(x.ti)} »</i>`:''}</span><em>${C[2](x.v,x.lv)}</em></div>`});const me=(BRD.data.me||{})[BRD.cat];h+=`<small>${me?'Ta place : <b>'+me.r+'</b>':'Pas encore classé dans cette catégorie'} · ${fmt(BRD.data.n||0)} pilote${(BRD.data.n||0)>1?'s':''} cette saison</small>`}
const mv=BRD.cat=='niveau'?V.niveau:V[BRD.cat];h+=`<small>Ton score : <b>${mv?C[2](mv,V.lv):'—'}</b> · pseudo « ${esc(bName())} » (modifiable dans le panneau Multijoueur)</small></div>`;return h}
function boardBind(el){el.querySelectorAll('[data-bc]').forEach(b=>b.onclick=()=>{BRD.cat=b.dataset.bc;cxRender();SFX.tick()})}
TICK.push(()=>{BRD.pt=(BRD.pt==null?25:BRD.pt)-DT;if(BRD.pt<=0){BRD.pt=180;boardPost(false)}});
// ----- récompenses de la saison précédente -----
async function seaReward(){if(!API_OK)return;const prev=isoWeek(new Date(Date.now()-7*864e5));if(G.x.seaClaim===prev)return;try{const r=await api('/api/board?season='+prev+'&code='+encodeURIComponent(CLOUD.code));G.x.seaClaim=prev;let cr=0,best=99;for(const c in r.me||{}){const k=r.me[c].r;if(k<=10){cr+=(11-k)*400;best=Math.min(best,k)}}
if(cr>0){G.cr+=cr;if(best==1){G.x.xti=G.x.xti||[];if(!G.x.xti.includes('Champion de la saison'))G.x.xti.push('Champion de la saison');if(!G.pown.includes('paint:laurier'))G.pown.push('paint:laurier')}banner('trophy','Saison '+prev+' terminée !','Top '+best+' · récompense +'+fmt(cr)+' ¢'+(best==1?' · titre et peinture Laurier débloqués':''),'#ffd34d');SFX.win()}save()}catch(e){}}
setTimeout(seaReward,9000);
addEventListener('pagehide',()=>{if(!API_OK||!navigator.sendBeacon)return;try{const body={code:CLOUD.code,n:bName(),ti:G.x.title||'',v:bVals()};if(JSON.stringify(body)!==BRD.last)navigator.sendBeacon('/api/board',new Blob([JSON.stringify(body)],{type:'application/json'}))}catch(e){}});
// ===== HÔTEL DES VENTES =====
const MK={open:false,tab:'buy',data:null,busy:false,t:-1e9,msg:''};
const mkItems=()=>{const ids=new Set([...Object.keys(G.cargo),...Object.keys(G.stash)]);return[...ids].filter(id=>haveMat(id)>0&&matG(id).n!==id)};
const mkRef=id=>{const g=matG(id);return g.p||40};
async function mkLoad(force){if(!API_OK)return;if(!force&&Date.now()-MK.t<15000){mkRender();return}MK.busy=true;mkRender();try{MK.data=await api('/api/market?code='+encodeURIComponent(CLOUD.code));MK.t=Date.now();MK.msg=''}catch(e){MK.msg='Hôtel des ventes injoignable pour l\'instant'}MK.busy=false;mkRender()}
async function mkDo(body,ok){if(MK.busy)return;MK.busy=true;mkRender();let r=null;try{r=await api('/api/market',Object.assign({code:CLOUD.code},body))}catch(e){r={error:'Connexion impossible'}}MK.busy=false;if(r&&r.error){toast('🏛 '+r.error);MK.t=0;mkLoad(true);return null}if(ok)ok(r);MK.t=0;mkLoad(true);return r}
function mkTake(id,q){let n=q;const c=Math.min(n,G.cargo[id]||0);if(c){G.cargo[id]-=c;n-=c;if(!G.cargo[id])delete G.cargo[id]}if(n>0){G.stash[id]-=n;if(G.stash[id]<=0)delete G.stash[id]}}
function mkGive(id,q){const room=Math.max(0,cap()-cargoUsed()),k=Math.min(q,room);if(k)G.cargo[id]=(G.cargo[id]||0)+k;if(q-k>0)G.stash[id]=(G.stash[id]||0)+(q-k)}
function mkSell(){const id=$('mkit').value,q=Math.floor(+$('mkq').value),p=Math.floor(+$('mkp').value);if(!id||q<1||q>haveMat(id)){toast('Quantité invalide');return}if(p<1){toast('Prix invalide');return}mkTake(id,q);save();
mkDo({a:'sell',n:bName(),it:id,q,p},()=>{toast('🏛 Annonce publiée : '+q+' '+matG(id).n+' à '+fmt(p)+' ¢ l\'unité');SFX.coin();save()}).then(r=>{if(!r){mkGive(id,q);save()}})}
function mkBuy(x){const tot=x.q*x.p;if(G.cr<tot){toast('Pas assez de crédits');return}mkDo({a:'buy',id:x.id},r=>{G.cr-=r.q*r.p;mkGive(r.it,r.q);toast('🏛 Achat : '+r.q+' '+matG(r.it).n+' pour '+fmt(r.q*r.p)+' ¢ (soute ou entrepôt)');SFX.coin();gainXP(10);save()})}
function mkCancel(x){mkDo({a:'cancel',id:x.id},r=>{mkGive(r.it,r.q);toast('Annonce retirée : marchandise récupérée');save()})}
function mkClaim(){mkDo({a:'claim'},r=>{if(r.cr){G.cr+=r.cr}for(const o of r.items||[])mkGive(o.it,o.q);toast(r.cr||r.items.length?'🏛 Encaissé : +'+fmt(r.cr)+' ¢'+(r.items.length?' · '+r.items.length+' lot(s) invendu(s) récupéré(s)':''):'Rien à encaisser');if(r.cr)SFX.coin();save()})}
function mkRender(){const el=$('mkpanel');if(!MK.open)return;let h=`<div class="phead"><b>${ICO('gavel')} Hôtel des ventes</b><button id="mkx">${ICO('close')}</button></div>`;
if(!API_OK){h+='<div class="psec"><small>L\'hôtel des ventes relie tous les joueurs du jeu publié (starvody.netlify.app). Il n\'est pas disponible dans cette version.</small></div>';el.innerHTML=h;$('mkx').onclick=()=>mkToggle(false);return}
const D=MK.data||{open:[],mine:[]},mine=D.mine||[],due=mine.filter(x=>!x.paid&&(x.st=='sold'||x.st=='exp')).length;h+=`<div class="cxtabs">${[['buy','Acheter','cargo'],['sell','Vendre','coin'],['mine','Mes annonces'+(due?' ('+due+')':''),'flag']].map(([k,n,ic])=>`<button data-mkt="${k}" class="${MK.tab==k?'on':''}">${ICO(ic)}${n}</button>`).join('')}</div>`;
if(MK.busy)h+='<small>Connexion…</small>';else if(MK.msg)h+=`<small>${MK.msg}</small>`;
if(MK.tab=='buy'){const L=(D.open||[]).filter(x=>!x.mine);h+='<div class="psec">';if(!L.length)h+='<small>Aucune annonce pour l\'instant. Reviens plus tard, ou mets tes propres marchandises en vente !</small>';
for(const x of L.slice(0,40)){const g=matG(x.it),tot=x.q*x.p,ok=G.cr>=tot;h+=`<div class="bmod"><span style="font-size:20px">${g.ic}</span><div><b>${x.q} × ${esc(g.n)}</b><small>${fmt(x.p)} ¢ l'unité (réf. ${fmt(mkRef(x.it))} ¢) · vendeur : ${esc(x.n)}</small></div><button data-mkb="${x.id}" class="${ok?'':'dim'}">${fmt(tot)} ¢</button></div>`}h+='</div>'}
else if(MK.tab=='sell'){const its=mkItems();h+='<div class="psec">';if(!its.length)h+='<small>Ta soute et ton entrepôt sont vides.</small>';else{const sel=MK.sel&&its.includes(MK.sel)?MK.sel:its[0];h+=`<label class="orow"><span>Marchandise</span><select id="mkit">${its.map(id=>`<option value="${id}" ${id==sel?'selected':''}>${matG(id).n} (${haveMat(id)})</option>`).join('')}</select></label><label class="orow"><span>Quantité</span><input id="mkq" type="number" min="1" value="${Math.min(10,haveMat(sel))}"></label><label class="orow"><span>Prix à l'unité (¢)</span><input id="mkp" type="number" min="1" value="${Math.round(mkRef(sel)*1.1)}"></label><small>Prix de référence : ${fmt(mkRef(sel))} ¢. L'annonce reste 3 jours ; 5 % de commission à l'encaissement. Les invendus te reviennent.</small><div class="obtns"><button id="mkgo">Mettre en vente</button></div>`}h+='</div>'}
else{h+='<div class="psec">';if(!mine.length)h+='<small>Tu n\'as aucune annonce.</small>';const SN={open:'En vente',sold:'Vendu',exp:'Expiré',gone:'Retiré'};for(const x of mine){const g=matG(x.it);h+=`<div class="bmod"><span style="font-size:20px">${g.ic}</span><div><b>${x.q} × ${esc(g.n)}</b><small>${fmt(x.p)} ¢ l'unité · ${SN[x.st]||x.st}${x.paid?' · encaissé':x.st=='sold'?' · à encaisser : '+fmt(Math.floor(x.q*x.p*.95))+' ¢':''}</small></div>${x.st=='open'?`<button data-mkc="${x.id}">Retirer</button>`:''}</div>`}
if(due)h+=`<div class="obtns"><button id="mkcl" class="hot">Encaisser</button></div>`;h+='</div>'}
el.innerHTML=h;$('mkx').onclick=()=>mkToggle(false);el.querySelectorAll('[data-mkt]').forEach(b=>b.onclick=()=>{MK.tab=b.dataset.mkt;mkRender();SFX.tick()});el.querySelectorAll('[data-mkb]').forEach(b=>b.onclick=()=>{const x=(D.open||[]).find(y=>y.id==b.dataset.mkb);if(x)mkBuy(x)});el.querySelectorAll('[data-mkc]').forEach(b=>b.onclick=()=>{const x=mine.find(y=>y.id==b.dataset.mkc);if(x)mkCancel(x)});
const it=$('mkit');if(it)it.onchange=()=>{MK.sel=it.value;mkRender()};const go=$('mkgo');if(go)go.onclick=mkSell;const cl=$('mkcl');if(cl)cl.onclick=mkClaim}
function mkToggle(v){MK.open=v==null?!MK.open:v;$('mkpanel').style.display=MK.open?'flex':'none';if(MK.open){mkLoad(false);mkRender()}}
SVC.act.mkopen=()=>mkToggle(true);
svcAdd({o:60,ic:'gavel',t:'Hôtel des ventes',show:st=>!st.ground,html:st=>SROW(`<div><b>Marché entre joueurs</b><small>Achète et vends des marchandises aux autres pilotes, même quand ils ne sont pas connectés.</small></div>`,`<button class="hot" data-sv="mkopen">Ouvrir</button>`)});
{const _dk=dock;dock=function(st){_dk(st);if(API_OK&&Math.random()<1)setTimeout(()=>{if(MK.data&&MK.data.mine&&MK.data.mine.some(x=>!x.paid&&x.st=='sold'))toast('🏛 Tu as des ventes à encaisser à l\'hôtel des ventes')},1500)}}
setTimeout(()=>{if(API_OK)mkLoad(true)},12000);
addEventListener('keydown',e=>{if(e.code=='Escape'&&MK.open)mkToggle(false)});
// ----- annonce de la mise à jour (une seule fois) -----
if(!G.x.news10){setTimeout(()=>{G.x.news10=1;banner('star','Mise à jour : 10 nouveautés !','Ailiers au bar, outils de vaisseau, épaves géantes, courses, anomalies, guerre des territoires, missions de faction, contrebande, journal de bord (J), classements','#7ab6ff');save()},7000)}
// ----- HUD : pas plus de quelques lignes d'objectifs à la fois (surtout sur mobile) -----
{const _ci=contentInfo;contentInfo=function(){const s=_ci();if(!s)return s;const L=s.split('<br>'),m=DESK?5:3;return L.length>m?L.slice(0,m).join('<br>'):s}}
// ===== SIGNALER UN PROBLÈME : journal des erreurs + rapport à copier =====
const ERRLOG=[];const errPush=(k,a)=>{try{const m=[...a].map(x=>x&&x.stack?String(x.stack).split('\n').slice(0,3).join(' ← '):String(x)).join(' ').slice(0,280);ERRLOG.push(new Date().toLocaleTimeString('fr-FR')+' '+k+' '+m);if(ERRLOG.length>15)ERRLOG.shift()}catch(e){}};
{const _ce=console.error.bind(console),_cw=console.warn.bind(console);console.error=(...a)=>{errPush('ERR',a);_ce(...a)};console.warn=(...a)=>{errPush('AVT',a);_cw(...a)}}
addEventListener('error',e=>errPush('ERR',[e.message+' @'+(e.lineno||'?')]));addEventListener('unhandledrejection',e=>errPush('ERR',[e.reason]));
function bugReport(desc){const I=lvInfo(),st=S.docked,pl=mode=='surf'&&SURF.info()?SURF.info().name:'',fc=typeof fmCur=='function'&&fmCur();
const L=['— Rapport Starfarer 3D —','Problème : '+(desc||'(non décrit)'),'Version : '+(UPD.cur||'?')+' · '+new Date().toLocaleString('fr-FR'),'Appareil : '+(DESK?'PC':'mobile')+' · '+innerWidth+'×'+innerHeight+' · '+(navigator.userAgent.match(/(iPhone|iPad|Android|Windows|Mac OS X|Linux)[^;)]*/)||['?'])[0]+' · qualité '+(DESK?QN[QI]:QNM[GQL]),
'Partie : niveau '+I.L+' · '+fmt(G.cr)+' ¢ · vaisseau '+(HULLS[G.ship]||{}).n+' · améliorations '+G.u.join('/')+' · coque '+Math.round(S.hp)+'/'+maxhp(),
'Lieu : mode '+mode+(st?' · amarré à '+st.n:'')+(pl?' · planète '+pl:'')+(mode=='int'&&DER.on?' · épave '+DER.on.q.n:'')+' · position '+[S.pos.x,S.pos.y,S.pos.z].map(v=>Math.round(v)).join(', ')+' · '+ZN[danger()]+(typeof terrTag=='function'?terrTag():''),
'En cours : '+([G.m&&('mission « '+G.m.txt+' »'),fc&&(FMC[fc.f].n+' '+(fc.i+1)+'/5 étape '+(fc.s+1)),RC.on&&('course '+RC.on.C.n),LAW.b>0&&('prime '+fmt(Math.round(LAW.b))+' ¢'),WG.list.length&&(WG.list.length+' ailier(s)'),G.story&&G.story.ch<8&&('histoire chapitre '+G.story.ch)].filter(Boolean).join(' · ')||'rien'),
'Multijoueur : '+(typeof MP!='undefined'&&MP.room?(MP.others.size+' autre(s) pilote(s)'):'non'),'Dernières erreurs :',...(ERRLOG.length?ERRLOG.slice(-8):['aucune'])];return L.join('\n')}
const BUGP={open:false};
function bugRender(){const el=$('bugpanel');el.innerHTML=`<div class="phead"><b>${ICO('warn')} Signaler un problème</b><button id="bugx">${ICO('close')}</button></div><div class="psec"><small>Décris ce qui s'est passé (où, quand, ce que tu faisais). Le rapport ajoute tout seul les infos utiles sur ta partie.</small><textarea id="bugt" maxlength="800" placeholder="Ex. : en sortant de l'épave, mon vaisseau a disparu…"></textarea><div class="obtns"><button id="bugc" class="hot">Copier le rapport</button></div><small>Colle-le ensuite dans ta conversation avec Claude.</small><pre id="bugpre"></pre></div>`;
const upd=()=>{$('bugpre').textContent=bugReport($('bugt').value.trim())};upd();$('bugt').oninput=upd;for(const ev of['keydown','keyup'])$('bugt').addEventListener(ev,e=>e.stopPropagation());$('bugx').onclick=()=>bugToggle(false);
$('bugc').onclick=async()=>{const txt=bugReport($('bugt').value.trim());try{await navigator.clipboard.writeText(txt);toast('📋 Rapport copié : colle-le dans ta conversation avec Claude');SFX.coin()}catch(e){const r=document.createRange();r.selectNodeContents($('bugpre'));const s=getSelection();s.removeAllRanges();s.addRange(r);toast('Sélectionne le texte du rapport et copie-le')}}}
function bugToggle(v){BUGP.open=v==null?!BUGP.open:v;$('bugpanel').style.display=BUGP.open?'flex':'none';if(BUGP.open){optToggle(false);bugRender()}}
$('bugb').onclick=()=>bugToggle(true);addEventListener('keydown',e=>{if(e.code=='Escape'&&BUGP.open)bugToggle(false)});
