// ===== GROTTES ET RUINES : une entrée par planète, exploration à pied (moteur des épaves), gardiens de cristal, énigme des runes et sanctuaire scellé =====
Object.assign(CXT.an,{cave:['Grotte','Des galeries creusées sous la surface. Certaines cachent des ruines bien plus anciennes que la colonisation.'],ruin:['Sanctuaire ancien','Une salle scellée par une énigme de runes. Ceux qui l\'ont bâtie ont disparu depuis longtemps.']});
Object.assign(CXT.en,{gardien:['Gardien de cristal','Une sentinelle de cristal qui flotte dans les ruines et crache des éclats brûlants.'],totem:['Totem gardien','Une tête de pierre qui protège les sanctuaires. Elle tire dès qu\'on entre.']});
const CVT={Volcanique:{n:'Grotte de lave',rock:0x5a362a,glow:0xff6a20,fog:0x140604,amb:0xb06040,crys:0xff8040,pool:0xff5010,hot:1,pn:'Lac de lave'},
Désertique:{n:'Grotte de grès',rock:0xa88258,glow:0xffc070,fog:0x120c06,amb:0xb09878,crys:0xffd080,pool:0x5ab0d0,pn:'Oasis souterraine'},
Jungle:{n:'Grotte moussue',rock:0x52643f,glow:0x7aff9a,fog:0x040c06,amb:0x7aaa80,crys:0x80ffb0,pool:0x40c0a0,pn:'Source chaude'},
Océanique:{n:'Grotte marine',rock:0x3e5468,glow:0x5ad0ff,fog:0x030c14,amb:0x7aa0c0,crys:0x60e0ff,pool:0x2a90d0,pn:'Lagon souterrain'},
Glacée:{n:'Grotte de glace',rock:0xa8c4dc,glow:0x9fe8ff,fog:0x08101a,amb:0xa0c8e8,crys:0xa0f0ff,pool:0x80c8ff,ice:1,pn:'Lac gelé'},
Cristalline:{n:'Grotte de cristal',rock:0x625878,glow:0xc08aff,fog:0x08060e,amb:0x9a8ad0,crys:0xd0a0ff,pool:0xa070ff,pn:'Bassin irisé'}};
const cvT=ty=>CVT[ty]||CVT.Cristalline;
const RUNEN=['la Lune','l\'Étoile','l\'Œil','le Serpent','la Flamme','la Montagne'],RUNES=['☾','✶','◉','∿','♢','△'];
const CVRN={airlock:'Entrée',bridge:'Sanctuaire',cargo:'Galerie en ruine',quarters:'Salle aux fresques',engine:'',lab:'Grotte de cristaux',armory:'Nid des gardiens',breach:'Grande caverne'};
// ----- textures -----
function cvGlyph(g,k,x,y,s){g.beginPath();if(k==0){g.arc(x,y,s,Math.PI*.3,Math.PI*1.7);g.arc(x+s*.5,y,s*.78,Math.PI*1.62,Math.PI*.38,true);g.closePath()}else if(k==1){for(let i=0;i<3;i++){const a=i*Math.PI/3+Math.PI/2;g.moveTo(x+Math.cos(a)*s,y+Math.sin(a)*s);g.lineTo(x-Math.cos(a)*s,y-Math.sin(a)*s)}}
else if(k==2){g.moveTo(x-s,y);g.quadraticCurveTo(x,y-s*1.1,x+s,y);g.quadraticCurveTo(x,y+s*1.1,x-s,y);g.moveTo(x+s*.32,y);g.arc(x,y,s*.32,0,TAU)}else if(k==3){for(let i=0;i<=20;i++){const u=i/20,px=x-s+u*2*s,py=y+Math.sin(u*TAU*1.5)*s*.45;i?g.lineTo(px,py):g.moveTo(px,py)}g.moveTo(x+s,y-s*.2);g.arc(x+s,y-s*.2,s*.12,0,TAU)}
else if(k==4){g.moveTo(x,y-s);g.quadraticCurveTo(x+s*.95,y+s*.25,x,y+s);g.quadraticCurveTo(x-s*.95,y+s*.25,x,y-s);g.moveTo(x,y-s*.1);g.quadraticCurveTo(x+s*.35,y+s*.4,x,y+s*.6)}else{g.moveTo(x-s,y+s*.7);g.lineTo(x,y-s*.8);g.lineTo(x+s,y+s*.7);g.closePath();g.moveTo(x-s*.45,y+s*.05);g.lineTo(x+s*.45,y+s*.05)}g.stroke()}
const CVGL=[0,1,2,3,4,5].map(k=>{const c=mkC(128),g=c.getContext('2d');g.strokeStyle='#fff';g.lineWidth=9;g.lineCap=g.lineJoin='round';g.shadowColor='#fff';g.shadowBlur=14;cvGlyph(g,k,64,64,40);return new THREE.CanvasTexture(c)});
const CVROCK=(()=>{const c=mkC(256),g=c.getContext('2d'),r=rng(913);g.fillStyle='#8a8a8a';g.fillRect(0,0,256,256);for(let i=0;i<900;i++){const v=110+r()*110|0;g.fillStyle=`rgba(${v},${v},${v},${.12+r()*.25})`;const s=2+r()*10;g.fillRect(r()*256,r()*256,s,s*.6)}g.strokeStyle='rgba(40,40,40,.45)';g.lineWidth=1.5;for(let i=0;i<14;i++){g.beginPath();let x=r()*256,y=r()*256;g.moveTo(x,y);for(let k=0;k<6;k++){x+=rv(30);y+=rv(30);g.lineTo(x,y)}g.stroke()}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;return t})();
function cvMural(seq){const c=mkC(512,256),g=c.getContext('2d'),r=rng(seq.join('')|0+5);g.fillStyle='#6e655a';g.fillRect(0,0,512,256);for(let i=0;i<500;i++){g.fillStyle=`rgba(${r()<.5?30:200},${r()<.5?25:190},20,${r()*.12})`;g.fillRect(r()*512,r()*256,3+r()*8,2+r()*5)}g.strokeStyle='rgba(30,24,18,.8)';g.lineWidth=6;g.strokeRect(10,10,492,236);
g.lineCap=g.lineJoin='round';seq.forEach((k,i)=>{const x=72+i*123,y=120;g.strokeStyle='rgba(20,16,12,.9)';g.lineWidth=11;cvGlyph(g,k,x+2,y+2,38);g.strokeStyle='#e8d8a8';g.lineWidth=7;cvGlyph(g,k,x,y,38);g.fillStyle='rgba(232,216,168,.8)';g.font='bold 22px serif';g.textAlign='center';g.fillText(['I','II','III','IV'][i],x,214);if(i<3){g.fillStyle='rgba(232,216,168,.6)';g.beginPath();g.moveTo(x+54,y-8);g.lineTo(x+68,y);g.lineTo(x+54,y+8);g.fill()}});return new THREE.CanvasTexture(c)}
// ----- matériaux par thème -----
const CVM={};
function cvMat(T){const k=T.n;if(CVM[k])return CVM[k];const ice=!!T.ice;return CVM[k]={rock:new THREE.MeshStandardMaterial({map:CVROCK,vertexColors:true,roughness:ice?.35:.92,metalness:ice?.15:.04,flatShading:true,side:THREE.DoubleSide}),
deco:new THREE.MeshStandardMaterial({vertexColors:true,roughness:ice?.3:.9,metalness:.05,flatShading:true}),crys:new THREE.MeshStandardMaterial({color:T.crys,emissive:T.crys,emissiveIntensity:.75,roughness:.2,metalness:.3,flatShading:true,transparent:true,opacity:.92}),
stone:new THREE.MeshStandardMaterial({color:0xa49884,map:CVROCK,roughness:.85,metalness:.05}),rk:new THREE.MeshStandardMaterial({color:T.rock,map:CVROCK,roughness:ice?.35:.9,metalness:ice?.15:.04,flatShading:true}),pool:new THREE.MeshStandardMaterial(T.hot?{color:T.pool,emissive:T.pool,emissiveIntensity:1.3,roughness:.6}:{color:T.pool,emissive:T.pool,emissiveIntensity:.25,roughness:.08,metalness:.6,transparent:true,opacity:.85})}}
// déformation des parois (fonction de la position seule : pas de fissures entre les morceaux)
const _cvo=[0,0,0];
function cvD(x,y,z){const s=.38,A=.72;_cvo[0]=x+(noise3(x*s,y*s,z*s,71)-.5)*A;_cvo[2]=z+(noise3(x*s+31,y*s,z*s,73)-.5)*A;_cvo[1]=y<.01?0:y-noise3(x*.5,7,z*.5,79)*.38*Math.min(1,y/DCEIL);return _cvo}
function cvGeo(L,T){const{rooms,at}=L,isF=(i,j)=>at(i,j)>=-1,hOf=(i,j)=>{const v=at(i,j);return v>=0&&rooms[v].role=='breach'?DBRE:DCEIL};const P=[],U=[],C=[],col=new THREE.Color(T.rock),c2=new THREE.Color();
const vtx=(x,y,z,u,v)=>{const o=cvD(x,y,z);P.push(o[0],o[1],o[2]);U.push(u,v);const k=.55+noise3(x*.3,y*.3,z*.3,83)*.7-(y<.5?.1:0)+(y<.01?.12:0);c2.copy(col).multiplyScalar(k);C.push(c2.r,c2.g,c2.b)};
const patch=(ox,oy,oz,ax,ay,az,bx,by,bz,nu,nv,uvf)=>{for(let a=0;a<nu;a++)for(let b=0;b<nv;b++){const q=[[a,b],[a+1,b],[a+1,b+1],[a,b+1]].map(([i,j])=>[ox+ax*i/nu+bx*j/nv,oy+ay*i/nu+by*j/nv,oz+az*i/nu+bz*j/nv]);for(const k of[0,1,2,0,2,3]){const p=q[k],uv=uvf(p);vtx(p[0],p[1],p[2],uv[0],uv[1])}}};
const uxz=p=>[p[0]/4,p[2]/4],uw=p=>[(p[0]+p[2])/4,p[1]/4];
for(let j=0;j<DGH;j++)for(let i=0;i<DGW;i++){if(!isF(i,j))continue;const x0=i*DTS,x1=x0+DTS,z0=j*DTS,z1=z0+DTS,h=hOf(i,j);patch(x0,0,z0,DTS,0,0,0,0,DTS,2,2,uxz);patch(x0,h,z0,0,0,DTS,DTS,0,0,3,3,uxz);
const side=(ni,nj,ax,az,bx,bz)=>{const nf=isF(ni,nj),nh=nf?hOf(ni,nj):0;if(nf&&nh>=h)return;const y0=nf?nh:0;patch(ax,y0,az,bx-ax,0,bz-az,0,h-y0,0,3,Math.max(2,Math.ceil((h-y0)/1.4)),uw)};
side(i-1,j,x0,z1,x0,z0);side(i+1,j,x1,z0,x1,z1);side(i,j-1,x0,z0,x1,z0);side(i,j+1,x1,z1,x0,z1)}
const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(P,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(U,2));geo.setAttribute('color',new THREE.Float32BufferAttribute(C,3));geo.computeVertexNormals();return geo}
// ----- construction du niveau (compatible avec la boucle des épaves) -----
function cvRoomPt(rm,r,m=1.2){return{x:rm.x*DTS+m+r()*(rm.w*DTS-2*m),z:rm.z*DTS+m+r()*(rm.h*DTS-2*m)}}
function caveBuild(o){const T=cvT(o.ty),M=cvMat(T),L=derGen(o),{rooms,doors,at}=L,g=new THREE.Group(),r=rng((o.seed||7)+11),K=DERD[o.id]||(DERD[o.id]={});K.c=K.c||[];K.lg=K.lg||[];const isF=(i,j)=>at(i,j)>=-1;
for(const rm of rooms)rm.zg=0;g.add(new THREE.Mesh(cvGeo(L,T),M.rock));
const add=(geo,m,x,y,z,ry=0,par=g)=>{const q=new THREE.Mesh(geo,m);q.position.set(x,y,z);q.rotation.y=ry;par.add(q);return q};
const lv={o,L,g,inter:[],doorsM:[],anchors:[],drones:[],sparks:[],floaters:[],start:null,sx:0,sz:0,fx:{bea:[],scr:[],ends:[]},cave:1};
// stalactites, stalagmites et cristaux (fusionnés : deux appels de dessin)
const RC=new THREE.Color(T.rock),rc=k=>{const c=RC.clone().multiplyScalar(k);return[c.r,c.g,c.b]},DP=[],CP=[],cone=new THREE.ConeGeometry(1,1,6),oct=new THREE.OctahedronGeometry(1,0);let nCr=0;
for(let j=0;j<DGH;j++)for(let i=0;i<DGW;i++){if(!isF(i,j))continue;const v=at(i,j),rm=v>=0?rooms[v]:null,h=rm&&rm.role=='breach'?DBRE:DCEIL,x0=i*DTS,z0=j*DTS;
const nt=rm&&rm.role=='breach'?5:r()<.45?1+(r()*2|0):0;for(let k=0;k<nt;k++){const l=h>6?2+r()*3.5:.6+r()*1.1,w=.18+r()*.3,x=x0+.8+r()*(DTS-1.6),z=z0+.8+r()*(DTS-1.6);DP.push({g:cone,m:M4(x,h-.3-l/2,z,Math.PI,0,0,w,l,w),c:rc(.7+r()*.4)})}
for(const[di,dj]of[[1,0],[-1,0],[0,1],[0,-1]]){if(at(i+di,j+dj)!=-2)continue;if(r()<.32){const l=.7+r()*1.6,w=.25+r()*.35,x=x0+DTS/2+di*(DTS/2-.75)+(dj?rv(1.8):0),z=z0+DTS/2+dj*(DTS/2-.75)+(di?rv(1.8):0);DP.push({g:cone,m:M4(x,l/2-.05,z,0,0,0,w,l,w),c:rc(.75+r()*.4)})}
const crysP=rm&&rm.role=='lab'?.55:rm?.1:.05;if(r()<crysP){const cx=x0+DTS/2+di*(DTS/2-.6)+(dj?rv(1.6):0),cz=z0+DTS/2+dj*(DTS/2-.6)+(di?rv(1.6):0),n=3+(r()*4|0);for(let q=0;q<n;q++){const s=.12+r()*.18,l=.5+r()*1.1;CP.push({g:oct,m:M4(cx+rv(.4),l*.4,cz+rv(.4),rv(.7)-di*.3,r()*3,rv(.7)+dj*.3,s,l,s),c:[1,1,1]})}if(nCr++%2==0)lv.anchors.push({x:cx,y:1.2,z:cz,c:T.crys,k:.8,fl:0})}}}
if(DP.length)g.add(new THREE.Mesh(mergeG(DP),M.deco));if(CP.length)g.add(new THREE.Mesh(mergeG(CP),M.crys));
// énigme : 4 runes dans 4 salles, l'ordre est gravé sur une fresque
const seq=[];{const pool=[0,1,2,3,4,5];for(let k=0;k<4;k++)seq.push(pool.splice((r()*pool.length)|0,1)[0])}const CP2={seq,k:0,solved:!!K.rn,read:!!K.rd,stones:[],seals:[]};lv.cvp=CP2;
const cand=rooms.filter(x=>x.role!='airlock'&&x.role!='bridge');for(let k=cand.length-1;k>0;k--){const q=(r()*(k+1))|0;[cand[k],cand[q]]=[cand[q],cand[k]]}
const stoneRooms=cand.slice(0,4),muralRoom=rooms.find(x=>x.role=='quarters'&&!stoneRooms.includes(x))||cand[4]||cand[0];
const glyM=k=>new THREE.MeshBasicMaterial({map:CVGL[k],transparent:true,depthWrite:false,blending:ADDB,color:0x554433});
// les runes sont dans le désordre : chaque pierre porte un symbole de la séquence
const order=seq.slice();for(let k=3;k>0;k--){const q=(r()*(k+1))|0;[order[k],order[q]]=[order[q],order[k]]}
stoneRooms.forEach((rm,i)=>{const p=cvRoomPt(rm,r,1.6),k=order[i],grp=new THREE.Group();grp.position.set(p.x,0,p.z);g.add(grp);add(new THREE.BoxGeometry(.9,2.3,.9),M.stone,0,1.15,0,0,grp);add(new THREE.BoxGeometry(1.2,.25,1.2),M.stone,0,2.35,0,0,grp);const gm=glyM(k);
for(let s=0;s<4;s++){const pl=add(new THREE.PlaneGeometry(.7,.7),gm,Math.sin(s*Math.PI/2)*.46,1.5,Math.cos(s*Math.PI/2)*.46,s*Math.PI/2,grp)}const gl=sprite(T.glow,2.6,.9);gl.position.y=1.5;gl.visible=false;grp.add(gl);
const St={k,grp,gm,gl,on:false};CP2.stones.push(St);const I={pos:new V3(p.x,1,p.z),r:2.4,done:CP2.solved,label:()=>'✦ TOUCHER LA RUNE : '+RUNEN[k].toUpperCase(),act:()=>runeTouch(lv,St)};St.I=I;lv.inter.push(I);lv.anchors.push({x:p.x,y:2.6,z:p.z,c:T.glow,k:.5,fl:0});if(CP2.solved){St.on=true;gm.color.set(T.glow);gl.visible=true}});
// fresque sur un mur de la salle
{const rm=muralRoom;let wp=null;for(let i=rm.x;i<rm.x+rm.w&&!wp;i++)for(const[j,dj]of[[rm.z,-1],[rm.z+rm.h-1,1]])if(!wp&&at(i,j+dj)==-2)wp={x:i*DTS+DTS/2,z:j*DTS+DTS/2+dj*(DTS/2-.42),ry:dj>0?Math.PI:0,nx:0,nz:-dj};
if(!wp){const p=cvRoomPt(rm,r);wp={x:p.x,z:p.z,ry:0,nx:0,nz:1}}const grp=new THREE.Group();grp.position.set(wp.x,1.9,wp.z);grp.rotation.y=wp.ry;g.add(grp);add(new THREE.BoxGeometry(3,1.6,.25),M.stone,0,0,-.08,0,grp);const mt=new THREE.MeshStandardMaterial({map:cvMural(seq),roughness:.9,emissive:0x221a10,emissiveMap:null});add(new THREE.PlaneGeometry(2.7,1.35),mt,0,0,.06,0,grp);
const I={pos:new V3(wp.x+wp.nx*1.2,1,wp.z+wp.nz*1.2),r:2.8,done:CP2.read,label:()=>'📜 DÉCHIFFRER LA FRESQUE',act:function(){this.done=true;CP2.read=true;K.rd=1;const tx='Quatre runes, dans cet ordre : '+seq.map((k,i)=>(i+1)+'. '+RUNEN[k]+' '+RUNES[k]).join(' · ');say([['ia','Traduction de la fresque. '+tx+'. Touche les pierres dans cet ordre pour ouvrir le sanctuaire.']]);cxLog('Fresque de la '+T.n.toLowerCase()+' : '+tx,T.n);gainXP(20);save()}};lv.inter.push(I);lv.anchors.push({x:wp.x+wp.nx*2,y:3,z:wp.z+wp.nz*2,c:0xffe0b0,k:.7,fl:0})}
// portes scellées du sanctuaire (dalles de pierre)
const bi=rooms.findIndex(x=>x.role=='bridge');for(const d of doors){if(d.room!==bi)continue;const vx=d.i-d.pi,ex=(d.i+d.pi+1)/2*DTS,ez=(d.j+d.pj+1)/2*DTS,alongX=vx!==0,grp=new THREE.Group();grp.position.set(alongX?ex:d.i*DTS+DTS/2,0,alongX?d.j*DTS+DTS/2:ez);if(alongX)grp.rotation.y=Math.PI/2;g.add(grp);
const panel=add(new THREE.BoxGeometry(DTS,DCEIL,.45),M.stone,0,DCEIL/2,0,0,grp),strip=add(new THREE.PlaneGeometry(1.1,1.1),new THREE.MeshBasicMaterial({map:CVGL[seq[0]],transparent:true,blending:ADDB,depthWrite:false,color:T.glow}),0,.2,.24,0,panel);
const D2={d,grp,panel,strip,open:CP2.solved?1:0,lock:!CP2.solved,ax:alongX?'x':'z',line:alongX?ex:ez,c:alongX?d.j*DTS+DTS/2:d.i*DTS+DTS/2,pos:new V3(grp.position.x,1.2,grp.position.z)};lv.doorsM.push(D2);
const I={pos:D2.pos,r:2.8,done:CP2.solved,door:D2,label:()=>'🔒 PORTE SCELLÉE',act:()=>toast(CP2.read?'🔒 Touche les 4 runes dans l\'ordre de la fresque : '+seq.map(k=>RUNES[k]).join(' → '):'🔒 La porte est scellée par des runes. Une fresque, quelque part dans la grotte, donne l\'ordre.')};CP2.seals.push(I);lv.inter.push(I)}
// contenu des salles
let urnN=0;const rr2=rng((o.seed||7)+3),zl=Math.min(4,Math.floor(Math.hypot(o.x,o.z)/9000));
const urn=(x,z)=>{const id=urnN++,opened=K.c.includes(id),grp=new THREE.Group();grp.position.set(x,0,z);g.add(grp);add(new THREE.CylinderGeometry(.32,.42,.85,10),M.stone,0,.43,0,0,grp);add(new THREE.CylinderGeometry(.22,.3,.18,10),M.stone,0,.94,0,0,grp);const lid=add(new THREE.CylinderGeometry(.27,.27,.09,10),new THREE.MeshStandardMaterial({color:0xc8a050,metalness:.6,roughness:.4}),0,1.07,0,0,grp);let bl=null;
if(!opened){bl=sprite(0xffd070,1,.8);bl.position.y=1.4;grp.add(bl)}else{lid.position.set(.45,.05,.2);lid.rotation.x=1.4}const I={pos:new V3(x,.8,z),r:2,done:opened,secure:false,id,bl,lid,grp,label:()=>'🏺 OUVRIR L\'URNE',act:()=>urnOpen(I)};lv.inter.push(I)};
for(const rm of rooms){const cx=rm.cx*DTS+DTS/2,cz=rm.cz*DTS+DTS/2,h=rm.role=='breach'?DBRE:DCEIL,x0=rm.x*DTS,W=rm.w*DTS;
if(rm.role=='airlock'){lv.start=new V3(x0+1.6,0,cz);const sh=fxSprite(SMOKET,ADDB,0xfff4d8,.35);sh.scale.set(3,9,1);sh.position.set(x0+1,3,cz);g.add(sh);const ray=add(new THREE.CylinderGeometry(1.1,1.6,DCEIL,12,1,true),new THREE.MeshBasicMaterial({color:0xfff0d0,transparent:true,opacity:.12,blending:ADDB,depthWrite:false,side:THREE.DoubleSide}),x0+1,DCEIL/2,cz);
lv.anchors.push({x:x0+1,y:3.6,z:cz,c:0xfff0d8,k:1.5,fl:0});lv.air={pos:new V3(x0+1,1,cz),r:2.6,label:()=>'☀ REMONTER À LA SURFACE',act:()=>derExit(false)};lv.inter.push(lv.air);continue}
lv.anchors.push({x:cx,y:h-.6,z:cz,c:rm.role=='bridge'?0xffd890:T.glow,k:rm.role=='bridge'?1.5:.55,fl:rm.role=='engine'?1:0});
if(rm.role=='cargo'||rm.role=='quarters'){for(let k=0;k<4;k++){const p=cvRoomPt(rm,rr2),hh=.8+rr2()*2.8;add(new THREE.CylinderGeometry(.45,.5,hh,10),M.stone,p.x,hh/2,p.z);if(rr2()<.5){const c=add(new THREE.CylinderGeometry(.42,.42,2,10),M.stone,p.x+rv(1.5),.42,p.z+rv(1.5),rr2()*3);c.rotation.z=Math.PI/2}}const n=rm.role=='cargo'?3:2;for(let k=0;k<n;k++){const p=cvRoomPt(rm,rr2,1.4);urn(p.x,p.z)}}
else if(rm.role=='engine'){const pool=add(new THREE.CircleGeometry(Math.min(rm.w,rm.h)*DTS*.28,24),M.pool,cx,.04,cz);pool.rotation.x=-Math.PI/2;lv.anchors.push({x:cx,y:.8,z:cz,c:T.pool,k:T.hot?1.6:.9,fl:T.hot?1:0});const p=cvRoomPt(rm,rr2,1.4);urn(p.x,p.z)}
else if(rm.role=='lab'){const p=cvRoomPt(rm,rr2,1.6);urn(p.x,p.z);const big=add(new THREE.OctahedronGeometry(1,0),M.crys,cx,1.6,cz);big.scale.set(.6,1.6,.6);lv.floaters.push({g:big,y0:1.6,ph:rr2()*9,spin:1})}
else if(rm.role=='armory'){for(let k=0;k<6;k++){const p=cvRoomPt(rm,rr2,.8);add(new THREE.SphereGeometry(.25+rr2()*.2,8,6),M.crys,p.x,.2,p.z)}const p=cvRoomPt(rm,rr2,1.4);urn(p.x,p.z)}
else if(rm.role=='breach'){for(let k=0;k<3;k++){const p=cvRoomPt(rm,rr2,1.5),hh=4+rr2()*7;add(new THREE.CylinderGeometry(.5+rr2()*.4,1.1+rr2()*.6,hh,8),M.rk,p.x,hh/2,p.z)}const p=cvRoomPt(rm,rr2,1.4);urn(p.x,p.z)}
else if(rm.role=='bridge'){const alt=add(new THREE.BoxGeometry(2.2,1,1.4),M.stone,cx,.5,cz);const chest=new THREE.Group();chest.position.set(cx,1,cz);g.add(chest);add(new THREE.BoxGeometry(1.2,.7,.8),new THREE.MeshStandardMaterial({color:0xd8ad48,metalness:.85,roughness:.3,emissive:0x302008}),0,.35,0,0,chest);const cl=sprite(0xffe08a,2.4);cl.position.y=1.1;if(!K.b)chest.add(cl);
for(let k=0;k<4;k++){const a=k/4*TAU+.785,px=cx+Math.cos(a)*3,pz=cz+Math.sin(a)*3;add(new THREE.CylinderGeometry(.4,.45,DCEIL,10),M.stone,px,DCEIL/2,pz)}
lv.inter.push({pos:new V3(cx,1,cz+1),r:2.8,done:!!K.b,label:()=>'✨ TRÉSOR DU SANCTUAIRE',act:function(){this.done=true;chest.remove(cl);sanctLoot(o)}});lv.sentry=[{x:x0+1,z:rm.z*DTS+1},{x:x0+W-1,z:rm.z*DTS+rm.h*DTS-1}]}}
// gardiens de cristal et totems
for(const rm of rooms){if(rm.role=='airlock'||rm.role=='bridge')continue;const n=rm.role=='armory'?3:rr2()<.5?1:0;for(let k=0;k<n+(zl>=2&&rr2()<.35?1:0);k++){const p=cvRoomPt(rm,rr2,1);lv.drones.push(gardMk(p.x,p.z,zl,T))}}
{const cells=[];for(let j=0;j<DGH;j++)for(let i=0;i<DGW;i++)if(at(i,j)==-1)cells.push([i,j]);for(let k=0;k<2&&cells.length;k++){const c=cells[(rr2()*cells.length)|0];lv.drones.push(gardMk(c[0]*DTS+2.5,c[1]*DTS+2.5,zl,T))}}
for(const s of lv.sentry||[])lv.drones.push(totemMk(s.x,s.z,zl,T));lv.drones.forEach((d,i)=>d.i=i);return lv}
function gardMk(x,z,zl,T){const g=new THREE.Group(),M=cvMat(T).crys,core=new THREE.Mesh(new THREE.OctahedronGeometry(.42,0),M);core.scale.set(1,1.5,1);g.add(core);const ring=new THREE.Group();g.add(ring);for(let i=0;i<3;i++){const s=new THREE.Mesh(new THREE.OctahedronGeometry(.16,0),M),a=i/3*TAU;s.position.set(Math.cos(a)*.75,Math.sin(a)*.75,0);s.scale.set(.6,1.6,.6);ring.add(s)}
const eye=sprite(T.glow,1.4,.9);eye.position.z=-.3;g.add(eye);g.position.set(x,2.2,z);return{g,pos:g.position,vel:new V3(),hp:5+zl,mhp:5+zl,cd:1+Math.random(),tg:null,st:'patrol',seen:0,kind:'gardien',dmg:5+zl,ring}}
function totemMk(x,z,zl,T){const g=new THREE.Group(),M=cvMat(T).stone;g.add(new THREE.Mesh(new THREE.CylinderGeometry(.55,.75,.8,8),M));const head=new THREE.Group();head.position.y=1.2;g.add(head);head.add(new THREE.Mesh(new THREE.BoxGeometry(.9,.9,.9),M));for(const s of[-1,1]){const e=sprite(T.glow,.6,1);e.position.set(s*.2,.08,-.47);head.add(e)}
g.position.set(x,0,z);return{g,pos:new V3(x,1.3,z),vel:new V3(),hp:16+zl*2,mhp:16+zl*2,cd:2,st:'sentry',head,kind:'totem',dmg:6+zl,burst:0,static:1}}
{const _dd=droneDie;droneDie=function(d){if(d.kind!='gardien'&&d.kind!='totem')return _dd(d);d.hp=0;const T=cvT(DER.on&&DER.on.q.ty);boom3(d.pos.clone(),18,T.crys,6);fxGlow(d.pos.clone(),T.glow,4,.3,2,DER.scene);noise(.35,.3,2600);tone(1800,600,.3,'triangle',.04);d.g.parent&&d.g.parent.remove(d.g);
if(d.i!=null&&DER.on){const K=DERD[DER.on.q.id];(K.dd=K.dd||{})[d.i]=Date.now()}const cr=d.static?110:35;G.cr+=cr;gainXP(d.static?40:15);STS.k[d.kind]=(STS.k[d.kind]||0)+1;cxAdd('en',d.kind);let tx=(d.static?'🗿 Totem détruit':'💎 Gardien brisé')+' · +'+cr+' ¢';if(!d.static&&Math.random()<.25&&cargoUsed()<cap()){G.cargo.cristal=(G.cargo.cristal||0)+1;tx+=' · 1 cristal'}toast(tx)}}
// ----- énigme -----
function runeTouch(lv,St){const P=lv.cvp,T=cvT(lv.o.ty);if(P.solved){toast('✦ La rune de '+RUNEN[St.k]+' brille déjà');return}if(St.on){toast('✦ Cette rune est déjà allumée');return}
if(St.k===P.seq[P.k]){St.on=true;St.gm.color.set(T.glow);St.gl.visible=true;P.k++;tone(400+P.k*160,500+P.k*160,.5,'sine',.06);tone(800+P.k*220,900+P.k*220,.6,'triangle',.03,.08);fxGlow(St.I.pos.clone().add(new V3(0,.5,0)),T.glow,5,.5,2,DER.scene);
if(P.k>=4){P.solved=true;const K=DERD[lv.o.id];K.rn=1;for(const S2 of P.stones)S2.I.done=true;for(const I of P.seals){I.done=true;I.door.lock=false}shake=Math.min(1,shake+.6);noise(2,.15,160);tone(60,40,2,'sawtooth',.06);banner('lock','Le sanctuaire s\'ouvre !','Les quatre runes résonnent : la porte de pierre se lève','#ffe08a');gainXP(80);save()}else toast('✦ '+RUNEN[St.k].replace(/^./,c=>c.toUpperCase())+' s\'allume ('+P.k+'/4)')}
else{P.k=0;for(const S2 of P.stones){S2.on=false;S2.gm.color.set(0x554433);S2.gl.visible=false}damage(6);shake=Math.min(1,shake+.4);tone(300,80,.6,'sawtooth',.06);noise(.4,.2,900);toast('⚡ Mauvais ordre ! Les runes s\'éteignent'+(P.read?'':' — une fresque doit donner l\'ordre'));
if(Math.random()<.5){const p=DER.p,d=gardMk(p.x+rv(3),p.z+rv(3),1,T);if(dFree(d.pos.x,d.pos.z,.45)){lv.drones.push(d);DER.scene.add(d.g);d.st='chase';d.seen=t}}}}
function urnOpen(I){I.done=true;const K=DERD[DER.on.q.id];if(!K.c.includes(I.id))K.c.push(I.id);if(I.bl)I.grp.remove(I.bl);I.lid.position.set(.45,.05,.2);I.lid.rotation.x=1.4;boom3(I.pos.clone(),8,0xffd070,4);SFX.win();
let cr=Math.round((60+Math.random()*160)*(1+.25*talR('chance')));G.cr+=cr;let tx='+'+cr+' ¢';const pool=['or','cristal','titane','or'],id=Math.random()<.1?'relic':pool[Math.random()*pool.length|0],q=Math.min(id=='relic'?1:1+(Math.random()*3|0),cap()-cargoUsed());if(q>0){G.cargo[id]=(G.cargo[id]||0)+q;tx+=' · '+q+' '+matG(id).n}toast('🏺 Urne ancienne : '+tx);gainXP(15);save()}
function sanctLoot(o){const K=DERD[o.id],first=!K.b;K.b=1;SFX.win();boom3(DER.p.clone().add(new V3(0,1.5,0)),20,0xffe08a,5);if(first){const cr=Math.round(1200*(1+.25*talR('chance')));G.cr+=cr;let tx='+'+fmt(cr)+' ¢';if(cargoUsed()<cap()){G.cargo.relic=(G.cargo.relic||0)+1;tx+=' · 1 relique'}if(cargoUsed()<cap()){G.cargo.exo=(G.cargo.exo||0)+1;tx+=' · 1 matière exotique'}gainXP(250);addRep('carto',60);cxAdd('an','ruin');STS.ruins=(STS.ruins||0)+1;banner('star','Trésor du sanctuaire !',tx+' et un plan de fabrication','#ffe08a');setTimeout(giveBlueprint,1500)}else{G.cr+=150;toast('Le coffre est vide… sauf 150 ¢ oubliés')}save()}
// ----- entrée sur la planète -----
const CVS={bg:DER.scene.background.clone(),fog:DER.scene.fog.color.clone(),amb:DRAMB.color.clone(),hs:DRHEM.color.clone(),hg:DRHEM.groundColor.clone(),cur:null};
function caveSurf(F,sc){if(!GR||!GR.inter)return;const r=rng((seedOf(F.p.x,F.p.y,F.p.z,909)>>>0)||9),O=GR.op||{x:0,z:0};let p=null;for(let k=0;k<240&&!p;k++){const a=r()*TAU,d=300+r()*500,x=O.x+Math.cos(a)*d,z=O.z+Math.sin(a)*d;if(Math.abs(x)>F.HALF*.8||Math.abs(z)>F.HALF*.8)continue;const y=F.h(x,z);if(y<5)continue;let ok=true;for(let b=0;b<6;b++)if(Math.abs(F.h(x+Math.cos(b)*9,z+Math.sin(b)*9)-y)>3.5)ok=false;if(ok)p=new V3(x,y,z)}if(!p)return;
const T=cvT(F.ty),M=cvMat(T),dir=new V3(O.x-p.x,0,O.z-p.z).normalize(),ry=Math.atan2(dir.x,dir.z),g=new THREE.Group();g.position.copy(p);g.rotation.y=ry;sc.add(g);
const rk=M.rk;const mound=new THREE.Mesh(ROCKG[0],rk);mound.scale.set(13,8,11);mound.position.set(0,1,-7);g.add(mound);for(let k=0;k<5;k++){const b=new THREE.Mesh(ROCKG[k%3],rk);const s=1.5+r()*2.5;b.scale.setScalar(s);b.position.set(rv(9),s*.4,-2+rv(4));g.add(b)}
const hole=new THREE.Mesh(new THREE.CircleGeometry(3.4,20),new THREE.MeshBasicMaterial({color:0x020202}));hole.scale.y=1.25;hole.position.set(0,3.6,3.85);g.add(hole);
for(const s of[-1,1]){const pil=new THREE.Mesh(new THREE.BoxGeometry(1.2,7,1.2),M.stone);pil.position.set(s*4.4,3.5,4.3);g.add(pil);const gm=new THREE.Mesh(new THREE.PlaneGeometry(.9,.9),new THREE.MeshBasicMaterial({map:CVGL[(r()*6)|0],transparent:true,blending:ADDB,depthWrite:false,color:T.glow}));gm.position.set(s*4.4,4.6,4.92);g.add(gm);const gl=sprite(T.glow,3,.6);gl.position.set(s*4.4,4.6,5.1);g.add(gl)}
const lin=new THREE.Mesh(new THREE.BoxGeometry(10.4,1.1,1.5),M.stone);lin.position.set(0,7.4,4.3);g.add(lin);
const front=p.clone().addScaledVector(dir,6.5);front.y=F.h(front.x,front.z);const id='cv:'+F.p.name,o={id,n:T.n,ty:F.ty,pl:F.p.name,seed:((seedOf(F.p.x,F.p.y,F.p.z,911)>>>0)%999999)+1,x:F.p.x,z:F.p.z,cave:1},C={o,front,dir};GR.cave=C;
exInter(front,5,()=>DERD[id]&&DERD[id].b?'🕳 ENTRER DANS LA GROTTE (EXPLORÉE)':'🕳 ENTRER DANS LA GROTTE',()=>caveEnter(C));GR.pois.push({k:'cave',name:T.n,pos:front.clone(),ic:'🕳',found:false,id:'cave'})}
{const _oe=SURF.onEnter;SURF.onEnter=function(F,sc){_oe(F,sc);try{caveSurf(F,sc)}catch(e){console.warn(e)}}}
function cvTheme(T){CVS.cur=T;DER.scene.background.setHex(T.fog);DER.scene.fog.color.setHex(T.fog);DRAMB.color.setHex(T.amb);DRHEM.color.setHex(T.amb);DRHEM.groundColor.setHex(T.rock).multiplyScalar(.3);DFX.amb0=null}
function cvThemeReset(){CVS.cur=null;DER.scene.background.copy(CVS.bg);DER.scene.fog.color.copy(CVS.fog);DRAMB.color.copy(CVS.amb);DRHEM.color.copy(CVS.hs);DRHEM.groundColor.copy(CVS.hg);DFX.amb0=null}
function caveEnter(C){if(mode!='surf'||!FOOT.on||S.dead||DER.on)return;FADE.col='0,0,0';FADE.tg=1;FADE.sp=5;SFX.buy();tone(140,70,.7,'sawtooth',.05);
setTimeout(()=>{if(mode!='surf'||!FOOT.on)return;const o=C.o;if(DER.lvl&&DER.lvl.o.id!==o.id){DER.scene.remove(DER.lvl.g);DER.lvl.g.traverse(m=>{if(m.geometry)m.geometry.dispose()});for(const d of DER.lvl.drones)d.g.parent&&d.g.parent.remove(d.g);DER.lvl=null}
if(!DER.lvl){DER.lvl=caveBuild(o);DER.scene.add(DER.lvl.g)}const lv=DER.lvl,KD=(DERD[o.id]||{}).dd||{};for(const d of lv.drones)if(d.i==null)d.g.parent&&d.g.parent.remove(d.g);lv.drones=lv.drones.filter(d=>d.i!=null);for(const d of lv.drones){const dead=KD[d.i]&&Date.now()-KD[d.i]<30*60e3;if(dead){d.hp=0;d.g.parent&&d.g.parent.remove(d.g);continue}if(d.hp<=0)d.hp=d.mhp;if(!d.g.parent)DER.scene.add(d.g)}
DER.on={q:o,cave:1,from:'surf',C};DER.p.copy(lv.start);DER.vel.set(0,0,0);DER.vy=0;FOOT.cy=-Math.PI/2;FOOT.cp=.12;DER.yaw=FOOT.cy;DER.fuel=1;
if(!DER.model)DER.model=buildHuman({suit:new THREE.Color().setHSL(((typeof MP!='undefined'?MP.hue:200))/360,.3,.78).getHex(),acc:0xff8a2a,tool:true,skin:0xe0b090,helmet:true,closed:true,visor:0x3a6a8a});if(DER.model.parent!==DER.scene)DER.scene.add(DER.model);
DER.scene.add(SPK.pts,FIRE.pts);SPK.clear();FIRE.clear();DER.psz=[SPK.pts.material.size,FIRE.pts.material.size];SPK.pts.material.size=.35;FIRE.pts.material.size=1.6;cvTheme(cvT(o.ty));
mode='int';S.docked=null;S.spd=0;S.vel.set(0,0,0);S.thr=0;clearWeapons();ship.visible=false;camInit=true;btnSet('fire','tool','Tirer');btnSet('boost','jump','Saut');btnSet('brake','run','Course');document.body.classList.add('foot');setD('footb','none');
FADE.tg=0;FADE.sp=1.2;if(cxAdd('an','cave')){G.cr+=80;gainXP(40)}const K=DERD[o.id];toast(K.b?'🕳 '+o.n+' — le sanctuaire a déjà été pillé, mais les urnes se remplissent… parfois':'🕳 '+o.n+' — trouve les quatre runes et ouvre le sanctuaire');save()},260)}
function caveExit(silent){const on=DER.on;DER.on=null;DER.hack=null;DER.map=false;mode='surf';ship.visible=true;SURF.scene.add(SPK.pts,FIRE.pts);SPK.clear();FIRE.clear();if(DER.psz){SPK.pts.material.size=DER.psz[0];FIRE.pts.material.size=DER.psz[1]}
for(const b of DER.pb)b.m.parent&&b.m.parent.remove(b.m);for(const b of DER.eb)b.m.parent&&b.m.parent.remove(b.m);DER.pb=[];DER.eb=[];cvThemeReset();btnSet('fire','tool','Outil');btnSet('boost','jump','Saut');btnSet('brake','run','Course');if(GR)GR.lastLabel='';
try{if(document.pointerLockElement)document.exitPointerLock()}catch(e){}camInit=true;if(silent||!on)return;const C=on.C;FOOT.pos.copy(C.front).addScaledVector(C.dir,2.5);FOOT.pos.y=GR.h(FOOT.pos.x,FOOT.pos.z);FOOT.vel.set(0,0,0);FOOT.vy=0;FOOT.cy=Math.atan2(-C.dir.x,-C.dir.z);FOOT.yaw=FOOT.cy;
FADE.col='0,0,0';FADE.v=1;FADE.tg=0;FADE.sp=1.5;SFX.buy();toast('☀ De retour à la surface');save()}
{const _dx=derExit;derExit=function(silent){if(mode=='int'&&DER.on&&DER.on.from=='surf'){caveExit(silent);return}_dx(silent)}}
// panneau d'infos en mode grotte
{const _di=derInfo;derInfo=function(){const on=DER.on;if(!on||!on.cave)return _di();const lv=DER.lvl,T=cvT(on.q.ty),rm=dRoom(DER.p.x,DER.p.z),P=lv&&lv.cvp,left=lv?lv.inter.filter(I=>I.secure!=null&&!I.done).length:0,dr=lv?lv.drones.filter(d=>d.hp>0).length:0;const rn=rm?(rm.role=='engine'?T.pn:CVRN[rm.role]):'Galerie';
return{info:`<span style="color:#d8c8a8">🕳 ${esc(T.n)} · ${esc(on.q.pl||'')}</span><br><span style="color:#ffe0a0">${rn}</span>${P&&P.read&&!P.solved?'<br><b style="color:#ffd27a">Ordre : '+P.seq.map(k=>RUNES[k]).join(' → ')+'</b>':''}`,sub:`<span title="Urnes">🏺<b>${left}</b></span><span title="Gardiens">${ICO('target')}<b>${dr}</b></span>`,zone:[P&&P.solved?((DERD[on.q.id]||{}).b?'Sanctuaire pillé ✓':'Le sanctuaire est ouvert !'):'Runes : '+(P?P.k:0)+'/4','#e8d0a0']}}}
// ----- annonce de la mise à jour -----
if(!G.x.news12){setTimeout(()=>{if(G.x.news12||typeof news13=='function')return;G.x.news12=1;G.x.news10=1;banner('star','Mise à jour : combat, grottes et espace vivant !',(DESK?'Tonneau (R), leurres (X), énergie (1 2 3 4), talents (K)':'Tonneau, leurres, énergie (touche le panneau), talents (Profil)')+', nouveaux ennemis, grottes et ruines sur les planètes, saut hyperspatial, stations de faction, comètes, éclipses, nouvelles du secteur','#7ab6ff');save()},7000)}
