// ===== ÉPAVES GÉANTES : croiseurs abandonnés à explorer à pied (couloirs sombres, lampe frontale, portes à pirater, drones de sécurité, salle en apesanteur, butin rare) =====
const DERFIX={id:'der-fix',n:'Vigilant',x:-5200,y:200,z:4800,seed:777};
const DERN=['Vigilant','Aurore Boréale','Prométhée','Odyssée','Léviathan III','Cassiopée','Intrépide','Mnémosyne','Requiem','Sirocco','Hypérion','Sélène'];
const DERD=GX('der',{});
const DLOGS=['Journal du capitaine : « Le réacteur a lâché au troisième saut. Nous dérivons. J\'ai ordonné l\'évacuation, mais quelqu\'un doit rester pour verrouiller la passerelle. »','Note de l\'ingénieure Voss : « Les drones de sécurité ne répondent plus aux codes. Ils protègent la passerelle… contre nous. »',
'Message enregistré : « Si quelqu\'un trouve ce vaisseau : la cargaison de la soute B n\'a jamais existé. Compris ? Jamais existé. »','Rapport médical : « Troisième membre d\'équipage pris de visions. Tous parlent d\'un chant venu des étoiles. Le même que l\'Écho de Kepler ? »',
'Carnet du cuisinier : « Plus de café depuis six jours. Le moral est au plus bas. Je crois que c\'est ça qui nous tuera, pas les pirates. »','Journal de bord, entrée 211 : « Brèche dans la soute. La moitié des caisses flotte dans le vide. Ne pas entrer sans combinaison magnétique. »',
'Dernier message du second : « Corbeau nous a vendus. Il connaissait notre route. Il connaissait tout. »','Fichier crypté (déchiffré) : « Coordonnées du phare ancien transmises aux Cartographes. Que personne d\'autre ne les obtienne. »',
'Note de sécurité : « Les portes de l\'armurerie se verrouillent en cas d\'alerte. Le code se force, mais déclenche les drones si on se trompe. »','Journal du capitaine, dernière entrée : « Je reste. Un vaisseau ne meurt pas tant que son capitaine respire. »'];
// ----- emplacement des épaves (une fixe près du départ, d'autres rares dans les secteurs) -----
function derCell(cx,cz){if(!cx&&!cz)return null;if(((cx%3)+3)%3==1&&((cz%3)+3)%3==1)return null;if(Math.hypot(cx,cz)*CS<7000||h3(cx,0,cz,601)>=.04)return null;const ox=cx*CS,oz=cz*CS;return{id:'der'+cx+'_'+cz,n:DERN[(h3(cx,0,cz,602)*DERN.length)|0],x:ox+900+h3(cx,0,cz,603)*(CS-1800),y:(h3(cx,0,cz,604)-.5)*1000,z:oz+900+h3(cx,0,cz,605)*(CS-1800),seed:(h3(cx,0,cz,606)*1e9)|0}}
function derNearList(p,R){const L=[];if(Math.hypot(DERFIX.x-p.x,DERFIX.z-p.z)<R)L.push(DERFIX);const cx=cof(p.x),cz=cof(p.z),N=Math.ceil(R/CS)+1;for(let i=-N;i<=N;i++)for(let l=-N;l<=N;l++){const o=derCell(cx+i,cz+l);if(o&&Math.hypot(o.x-p.x,o.z-p.z)<R)L.push(o)}return L}
function derScan(p,R){for(const o of derNearList(p,R)){const K=DERD[o.id]||(DERD[o.id]={});if(!K.seen){K.seen=1;K.x=o.x|0;K.y=o.y|0;K.z=o.z|0;K.n=o.n;cxAdd('an','der');toast('🛸 Épave géante repérée : '+o.n);SFX.disc()}}}
// ----- l'épave dans l'espace -----
const DRH={act:new Map(),ck:'',near:null};
function derHull(o){const g=new THREE.Group(),r=rng(o.seed||1),H=new THREE.MeshStandardMaterial({color:0x4a4e54,map:HULLT,normalMap:typeof HULLN!='undefined'?HULLN:null,metalness:DESK?.7:.4,roughness:.55}),Dk=new THREE.MeshStandardMaterial({color:0x1c1e22,metalness:.6,roughness:.7}),Bu=new THREE.MeshStandardMaterial({color:0x2a2422,roughness:.9});
const add=(geo,m,x,y,z,rx=0,ry=0,rz=0)=>{const q=new THREE.Mesh(geo,m);q.position.set(x,y,z);q.rotation.set(rx,ry,rz);g.add(q);return q};
add(lathe([[0,-280],[30,-240],[58,-150],[62,40],[54,170],[40,240],[0,250]],12),H,0,0,0).scale.set(1,.8,1);add(new THREE.BoxGeometry(70,36,120),H,0,44,60);add(new THREE.BoxGeometry(40,22,40),Dk,0,70,80);
for(const s of[-1,1]){add(new THREE.BoxGeometry(110,8,70),H,s*90,-6,40,0,0,s*(.08+r()*.2));add(new THREE.CylinderGeometry(16,20,60,12).rotateX(Math.PI/2),Dk,s*40,-10,250);for(let k=0;k<5;k++)add(new THREE.BoxGeometry(8,8,40+r()*40),Dk,s*(30+r()*30),rv(40),-150+k*60)}
// coque éventrée : plaques arrachées, débris
for(let i=0;i<16;i++){const b=add(new THREE.BoxGeometry(8+r()*30,2+r()*6,10+r()*40),i%3?H:Bu,rv(90),rv(60),rv(260));b.rotation.set(rv(3),rv(3),rv(3));b.position.multiplyScalar(1.15)}
const gash=add(new THREE.SphereGeometry(34,12,8),new THREE.MeshBasicMaterial({color:0x050608}),48,10,-60);gash.scale.set(.4,1,1.6);
const lights=[];for(let i=0;i<18;i++){const s=sprite(i%4?0xff4030:0xffb060,10);s.position.set(rv(60),rv(40),rv(250));g.add(s);lights.push({s,ph:r()*9})}
// sas d'amarrage (côté gauche) : anneau vert et balise
const air=new THREE.Group();air.position.set(-66,6,-20);g.add(air);const ring=new THREE.Mesh(new THREE.TorusGeometry(10,1.4,8,32),new THREE.MeshBasicMaterial({color:0x5af0a0}));ring.rotation.y=Math.PI/2;air.add(ring);air.add(new THREE.Mesh(new THREE.BoxGeometry(6,16,16),Dk));const bc=sprite(0x5af0a0,40);bc.position.x=-6;air.add(bc);
g.position.set(o.x,o.y,o.z);g.rotation.set(rv(.3)*0+.15,(o.seed%628)/100,.25);g.userData={lights,air,bc};return g}
function derAirPos(o){return o.mesh.userData.air.getWorldPosition(new V3()).add(new V3(-30,0,0).applyQuaternion(o.mesh.quaternion))}
function derSpaceTick(dt){const ck=cof(S.pos.x)+','+cof(S.pos.z);if(ck!==DRH.ck){DRH.ck=ck;const L=derNearList(S.pos,9000),ids=new Set(L.map(o=>o.id));for(const o of L)if(!DRH.act.has(o.id)){const q={...o};
for(let i=-1;i<=1;i++)for(let l=-1;l<=1;l++)for(let j=-1;j<=1;j++){const c=cdata(cof(q.x)+i,j,cof(q.z)+l);for(const b of[c.pl,c.st,c.sun]){if(!b)continue;const rr=(b.r||200)+900,dd=Math.hypot(q.x-b.x,q.y-b.y,q.z-b.z);if(dd<rr){q.x=b.x+(q.x-b.x)/(dd||1)*rr;q.z=b.z+(q.z-b.z)/(dd||1)*rr}}}
q.mesh=derHull(q);scene.add(q.mesh);DRH.act.set(o.id,q)}for(const[id,q]of DRH.act)if(!ids.has(id)){scene.remove(q.mesh);q.mesh.traverse(m=>{if(m.geometry)m.geometry.dispose()});DRH.act.delete(id)}}
DRH.near=null;for(const q of DRH.act.values()){const u=q.mesh.userData;for(const L of u.lights)L.s.visible=Math.sin(t*3+L.ph)>.3;u.bc.scale.setScalar(36+Math.sin(t*4)*8);const d=S.pos.distanceTo(q.mesh.position);if(d<4000){const K=DERD[q.id]||(DERD[q.id]={});if(!K.seen){K.seen=1;K.x=q.x|0;K.y=q.y|0;K.z=q.z|0;K.n=q.n;cxAdd('an','der');toast('🛸 Épave géante : '+q.n+' — approche-toi du sas vert pour entrer');SFX.disc()}}
// collision avec la coque (ellipsoïde)
if(d<400){const lp=q.mesh.worldToLocal(S.pos.clone()),e=(lp.x/72)**2+(lp.y/58)**2+(lp.z/275)**2;if(e<1){lp.divideScalar(Math.sqrt(e)*.98);S.pos.copy(q.mesh.localToWorld(lp));S.spd*=.4;S.vel.multiplyScalar(-.3);damage(3,'col')}}
const ap=derAirPos(q);if(ap.distanceTo(S.pos)<120&&S.spd<95&&!S.dead&&!S.docked)DRH.near=q}}
STICK.push(derSpaceTick);
function derNear(){return mode=='space'&&!!DRH.near&&!S.entry&&!S.dead}
{const _ov=overlay;overlay=function(){_ov();if(mode!='space'||S.dead)return;for(const q of DRH.act.values()){const ap=derAirPos(q),d=ap.distanceTo(S.pos);if(d<2500&&d>40)edgeMarker(ap,'#5af0a0','Sas · '+q.n,'⬢')}}}
{const _mr=mpRadar;mpRadar=function(blip){_mr(blip);if(mode=='space')for(const q of DRH.act.values())blip(q.mesh.position,'#c8c0b0',4,true)}}
{const _dm=drawMap;drawMap=function(){_dm();if(mode=='surf'&&GR)return;for(const id in DERD){const K=DERD[id];if(!K.seen)continue;const[x,y]=w2s(K.x,K.z);if(x<-30||y<-30||x>innerWidth+30||y>innerHeight+30)continue;MX.fillStyle=K.b?'#7f9':'#c8c0b0';MX.font="700 12px 'Chakra Petch',system-ui";MX.textAlign='center';MX.fillText('🛸',x,y+4);if(MAP.zoom>.008){MX.fillStyle='rgba(220,235,255,.8)';MX.font="600 10px 'Chakra Petch',system-ui";MX.fillText(K.n+(K.b?' ✓':''),x,y-11)}}}}
// ===== INTÉRIEUR =====
const DTS=5,DMW=4,DMH=3,DMC=7,DGW=DMW*DMC,DGH=DMH*DMC,DCEIL=4.2,DBRE=14;
const DER={scene:new THREE.Scene(),on:null,lvl:null,group:null,p:new V3(),vel:new V3(),vy:0,yaw:0,ph:0,grounded:true,model:null,fuel:1,pb:[],eb:[],dr:[],hack:null,tcd:0,map:false,lightsT:0,kf:0};
DER.scene.background=new THREE.Color(0x020306);DER.scene.fog=new THREE.FogExp2(0x04060b,.034);
const DRAMB=new THREE.AmbientLight(0x6a7c98,.38),DRHEM=new THREE.HemisphereLight(0x8fb0d8,0x1a1410,.32);DER.scene.add(DRAMB,DRHEM);
const DRLAMP=new THREE.SpotLight(0xfff2dc,1.9,46,.6,.5,1.3);DER.scene.add(DRLAMP,DRLAMP.target);
const DRPL=[];for(let i=0;i<5;i++){const L=new THREE.PointLight(0xff4030,0,22,1.6);DER.scene.add(L);DRPL.push(L)}
// ----- textures -----
const DRTEX=(()=>{const mk=(f)=>{const c=mkC(256),g=c.getContext('2d');f(g);const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;return t};
const floor=mk(g=>{g.fillStyle='#2b3036';g.fillRect(0,0,256,256);for(let i=0;i<500;i++){g.fillStyle=`rgba(255,255,255,${Math.random()*.035})`;g.fillRect(Math.random()*256,Math.random()*256,1+Math.random()*3,1)}g.strokeStyle='#15181c';g.lineWidth=4;g.strokeRect(2,2,252,252);g.strokeStyle='#3c434b';g.lineWidth=1;for(let i=16;i<256;i+=16){g.beginPath();g.moveTo(i,10);g.lineTo(i,246);g.stroke()}g.fillStyle='#4a525b';for(const[x,y]of[[10,10],[246,10],[10,246],[246,246]]){g.beginPath();g.arc(x,y,4,0,TAU);g.fill()}g.fillStyle='rgba(255,190,40,.55)';for(let i=0;i<8;i++)g.fillRect(i*32,0,16,5)});
const wall=mk(g=>{g.fillStyle='#3a4048';g.fillRect(0,0,256,256);g.fillStyle='#2c3138';g.fillRect(0,0,256,40);g.fillRect(0,200,256,56);g.strokeStyle='#22262c';g.lineWidth=3;for(let x=0;x<=256;x+=64){g.beginPath();g.moveTo(x,0);g.lineTo(x,256);g.stroke()}g.fillStyle='#1a1d22';g.fillRect(0,96,256,14);for(let i=0;i<300;i++){g.fillStyle=`rgba(0,0,0,${Math.random()*.12})`;g.fillRect(Math.random()*256,Math.random()*256,2+Math.random()*8,2)}g.fillStyle='#596169';for(let x=8;x<256;x+=64)for(const y of[50,190]){g.fillRect(x,y,4,4);g.fillRect(x+48,y,4,4)}});
const wallE=mk(g=>{g.fillStyle='#000';g.fillRect(0,0,256,256);g.fillStyle='#9fd8ff';g.fillRect(0,99,256,7);g.fillStyle='rgba(159,216,255,.25)';g.fillRect(0,95,256,15);for(let x=20;x<256;x+=64){g.fillStyle='#ff5040';g.fillRect(x,214,6,6)}});
const ceil=mk(g=>{g.fillStyle='#1d2126';g.fillRect(0,0,256,256);g.strokeStyle='#2c3138';g.lineWidth=6;g.strokeRect(0,0,256,256);g.fillStyle='#2a2f35';g.fillRect(40,40,176,176);g.fillStyle='#14171b';for(let i=0;i<6;i++)g.fillRect(56,60+i*24,144,8)});
const ceilE=mk(g=>{g.fillStyle='#000';g.fillRect(0,0,256,256);g.fillStyle='rgba(220,235,255,.55)';g.fillRect(100,100,56,56)});return{floor,wall,wallE,ceil,ceilE}})();
const DRMAT={floor:new THREE.MeshStandardMaterial({map:DRTEX.floor,metalness:.55,roughness:.55,side:THREE.DoubleSide}),wall:new THREE.MeshStandardMaterial({map:DRTEX.wall,emissiveMap:DRTEX.wallE,emissive:0xffffff,emissiveIntensity:.55,metalness:.5,roughness:.6,vertexColors:true,side:THREE.DoubleSide}),
ceil:new THREE.MeshStandardMaterial({map:DRTEX.ceil,emissiveMap:DRTEX.ceilE,emissive:0xffffff,emissiveIntensity:.35,metalness:.4,roughness:.7,side:THREE.DoubleSide}),crate:new THREE.MeshStandardMaterial({color:0x8a6a3a,map:HULLT,metalness:.3,roughness:.7}),crate2:new THREE.MeshStandardMaterial({color:0x3a4250,map:HULLT,metalness:.7,roughness:.35}),
dark:new THREE.MeshStandardMaterial({color:0x22262c,metalness:.6,roughness:.5}),door:new THREE.MeshStandardMaterial({color:0x56606c,map:HULLT,metalness:.7,roughness:.35}),pipe:new THREE.MeshStandardMaterial({color:0x4a5058,metalness:.8,roughness:.35})};
// ----- génération du plan (salles reliées par des couloirs) -----
function derGen(o){const r=rng(o.seed||7),grid=new Int16Array(DGW*DGH).fill(-2),rooms=[];const at=(i,j)=>i<0||j<0||i>=DGW||j>=DGH?-2:grid[j*DGW+i];
for(let mj=0;mj<DMH;mj++)for(let mi=0;mi<DMW;mi++){const w=3+(r()*3|0),h=3+(r()*3|0),x=mi*DMC+1+(r()*(DMC-1-w)|0),z=mj*DMC+1+(r()*(DMC-1-h)|0),id=rooms.length;rooms.push({id,mi,mj,x,z,w,h,cx:x+(w>>1),cz:z+(h>>1),role:'room',links:[]});for(let a=x;a<x+w;a++)for(let b=z;b<z+h;b++)grid[b*DGW+a]=id}
const R=(mi,mj)=>rooms[mj*DMW+mi],edges=[],seen=new Set([0]),stack=[0];while(stack.length){const cur=stack[stack.length-1],c=rooms[cur],nb=[[1,0],[-1,0],[0,1],[0,-1]].map(([a,b])=>[c.mi+a,c.mj+b]).filter(([a,b])=>a>=0&&b>=0&&a<DMW&&b<DMH&&!seen.has(b*DMW+a));if(!nb.length){stack.pop();continue}const[a,b]=nb[(r()*nb.length)|0],n=b*DMW+a;seen.add(n);edges.push([cur,n]);stack.push(n)}
for(let k=0;k<2;k++){const a=(r()*rooms.length)|0,c=rooms[a],d=[[1,0],[0,1]][(r()*2)|0],b=R(Math.min(DMW-1,c.mi+d[0]),Math.min(DMH-1,c.mj+d[1]));if(b&&b.id!==a&&!edges.some(e=>(e[0]==a&&e[1]==b.id)||(e[1]==a&&e[0]==b.id)))edges.push([a,b.id])}
const doors=[];for(const[a,b]of edges){const A=rooms[a],B=rooms[b];A.links.push(b);B.links.push(a);const path=[];let i=A.cx,j=A.cz;const hz=r()<.5;const step=(ti,tj)=>{while(i!==ti||j!==tj){if(i!==ti)i+=Math.sign(ti-i);else j+=Math.sign(tj-j);path.push([i,j])}};if(hz){step(B.cx,A.cz);step(B.cx,B.cz)}else{step(A.cx,B.cz);step(B.cx,B.cz)}
let prev=[A.cx,A.cz];for(const[pi,pj]of path){const v=at(pi,pj);if(v==-2){grid[pj*DGW+pi]=-1}const pv=at(prev[0],prev[1]),cv=at(pi,pj);if((pv>=0&&cv==-1)||(pv==-1&&cv>=0)){const rm=pv>=0?pv:cv;if(!doors.some(d=>d.i==pi&&d.j==pj&&d.pi==prev[0]&&d.pj==prev[1]))doors.push({i:pi,j:pj,pi:prev[0],pj:prev[1],room:rm,lock:false})}prev=[pi,pj]}}
// rôles des salles : sas (départ), passerelle (la plus loin), les autres au hasard
const dist=new Array(rooms.length).fill(1e9);dist[0]=0;const q=[0];while(q.length){const c=q.shift();for(const n of rooms[c].links)if(dist[n]>dist[c]+1){dist[n]=dist[c]+1;q.push(n)}}
let far=0;for(let k=0;k<rooms.length;k++)if(dist[k]>dist[far])far=k;rooms[0].role='airlock';rooms[far].role='bridge';const roles=['cargo','quarters','engine','lab','armory','breach','cargo','quarters','lab','cargo'];let ri=(r()*3)|0;for(const rm of rooms)if(rm.role=='room'){rm.role=roles[ri++%roles.length]}
if(!rooms.some(x=>x.role=='breach')){const c=rooms.find(x=>x.role=='cargo'||x.role=='quarters');if(c)c.role='breach'}
for(const d of doors){const rm=rooms[d.room];if(rm.role=='bridge'||(rm.role=='armory'&&r()<.8)||(rm.role=='lab'&&r()<.35))d.lock=true}
return{grid,rooms,doors,at,far,r}}
// ----- construction de la géométrie -----
function derBuild(o){const L=derGen(o),{grid,rooms,doors,at}=L,g=new THREE.Group(),r=rng((o.seed||7)+11);const hOf=(i,j)=>{const v=at(i,j);return v>=0&&rooms[v].role=='breach'?DBRE:DCEIL};const isF=(i,j)=>at(i,j)>=-1;
const F={p:[],n:[],u:[]},Wl={p:[],n:[],u:[],c:[]},Ce={p:[],n:[],u:[]};const ROLEC={airlock:[.7,1,.8],bridge:[1,1,1],cargo:[1,.9,.75],quarters:[.85,.9,1],engine:[1,.75,.55],lab:[.75,1,.95],armory:[1,.7,.7],breach:[.6,.75,1]};
const quad=(A,a,b,c,d,n,uv,col)=>{for(const v of[a,b,c,a,c,d]){A.p.push(...v);A.n.push(...n)}for(const k of[0,1,2,0,2,3])A.u.push(...uv[k]);if(col)for(let k=0;k<6;k++)A.c.push(...col)};
for(let j=0;j<DGH;j++)for(let i=0;i<DGW;i++){if(!isF(i,j))continue;const x0=i*DTS,x1=x0+DTS,z0=j*DTS,z1=z0+DTS,h=hOf(i,j),v=at(i,j),col=v>=0?ROLEC[rooms[v].role]:[.8,.85,.9];
quad(F,[x0,0,z0],[x1,0,z0],[x1,0,z1],[x0,0,z1],[0,1,0],[[0,0],[1,0],[1,1],[0,1]]);quad(Ce,[x0,h,z0],[x0,h,z1],[x1,h,z1],[x1,h,z0],[0,-1,0],[[0,0],[0,1],[1,1],[1,0]]);
const side=(ni,nj,a,b,n)=>{const nf=isF(ni,nj),nh=nf?hOf(ni,nj):0;if(nf&&nh>=h)return;const y0=nf?nh:0,hk=(h-y0)/DCEIL;quad(Wl,[a[0],y0,a[1]],[b[0],y0,b[1]],[b[0],h,b[1]],[a[0],h,a[1]],n,[[0,0],[1,0],[1,hk],[0,hk]],col)};
side(i-1,j,[x0,z1],[x0,z0],[1,0,0]);side(i+1,j,[x1,z0],[x1,z1],[-1,0,0]);side(i,j-1,[x0,z0],[x1,z0],[0,0,1]);side(i,j+1,[x1,z1],[x0,z1],[0,0,-1])}
const mkG=(A,c)=>{const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(A.p,3));geo.setAttribute('normal',new THREE.Float32BufferAttribute(A.n,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(A.u,2));if(c)geo.setAttribute('color',new THREE.Float32BufferAttribute(A.c,3));return geo};
g.add(new THREE.Mesh(mkG(F),DRMAT.floor),new THREE.Mesh(mkG(Wl,1),DRMAT.wall),new THREE.Mesh(mkG(Ce),DRMAT.ceil));
const add=(geo,m,x,y,z,ry=0,par=g)=>{const q=new THREE.Mesh(geo,m);q.position.set(x,y,z);q.rotation.y=ry;par.add(q);return q};const K=DERD[o.id]||(DERD[o.id]={});K.c=K.c||[];K.lg=K.lg||[];
const lv={o,L,g,inter:[],doorsM:[],anchors:[],drones:[],sparks:[],floaters:[],start:null,sx:0,sz:0};
// tuyaux dans les couloirs
const pipeG=new THREE.CylinderGeometry(.14,.14,DTS,6).rotateZ(Math.PI/2);for(let j=0;j<DGH;j++)for(let i=0;i<DGW;i++)if(at(i,j)==-1&&r()<.7){const hz=isF(i-1,j)||isF(i+1,j);const p=add(pipeG,DRMAT.pipe,i*DTS+DTS/2,DCEIL-.35,j*DTS+DTS/2+(hz?-1.6:0),hz?0:Math.PI/2);if(!hz)p.position.x-=1.6;if(r()<.12)lv.anchors.push({x:i*DTS+2.5,y:DCEIL-.6,z:j*DTS+2.5,c:0xff3020,k:.6,fl:1})}
// portes
for(const d of doors){const vx=d.i-d.pi,vz=d.j-d.pj,ex=(d.i+d.pi+1)/2*DTS,ez=(d.j+d.pj+1)/2*DTS,alongX=vx!==0;const grp=new THREE.Group();grp.position.set(alongX?ex:d.i*DTS+DTS/2,0,alongX?d.j*DTS+DTS/2:ez);if(alongX)grp.rotation.y=Math.PI/2;g.add(grp);
const panel=add(new THREE.BoxGeometry(DTS,DCEIL,.3),DRMAT.door,0,DCEIL/2,0,0,grp);const strip=add(new THREE.BoxGeometry(DTS*.9,.12,.34),new THREE.MeshBasicMaterial({color:d.lock?0xff3030:0x40ff90}),0,1.6-DCEIL/2,0,0,panel);add(new THREE.BoxGeometry(.4,DCEIL,.5),DRMAT.dark,-DTS/2+.2,DCEIL/2,0,0,grp);add(new THREE.BoxGeometry(.4,DCEIL,.5),DRMAT.dark,DTS/2-.2,DCEIL/2,0,0,grp);
const D2={d,grp,panel,strip,open:0,lock:d.lock&&!(K.dh||[]).includes(d.i+','+d.j),ax:alongX?'x':'z',line:alongX?ex:ez,c:alongX?d.j*DTS+DTS/2:d.i*DTS+DTS/2,pos:new V3(grp.position.x,1.2,grp.position.z)};if(!D2.lock)strip.material.color.setHex(0x40ff90);lv.doorsM.push(D2);
if(D2.lock){const I={pos:D2.pos,r:2.6,label:()=>'🔒 PIRATER LA PORTE',act:()=>hackStart({door:D2}),door:D2};lv.inter.push(I)}}
// contenu des salles
let crateN=0,logN=0;const rr2=rng((o.seed||7)+3);for(const rm of rooms){const cx=rm.cx*DTS+DTS/2,cz=rm.cz*DTS+DTS/2,h=rm.role=='breach'?DBRE:DCEIL,x0=rm.x*DTS,z0=rm.z*DTS,W=rm.w*DTS,Hh=rm.h*DTS;
const AC={airlock:0x5af0a0,bridge:0xdfe8ff,cargo:0xffb060,quarters:0x9fb8ff,engine:0xff7a30,lab:0x7fffd0,armory:0xff4040,breach:0x5a9cff}[rm.role];lv.anchors.push({x:cx,y:h-.5,z:cz,c:AC,k:rm.role=='bridge'?1.6:1.1,fl:rm.role=='engine'||rm.role=='breach'?1:0});
const crate=(x,z,y,secure,fl)=>{const id=crateN++,opened=K.c.includes(id),grp=new THREE.Group();grp.position.set(x,y||0,z);g.add(grp);const m=add(new THREE.BoxGeometry(1.4,1.1,1.4),secure?DRMAT.crate2:DRMAT.crate,0,.55,0,0,grp);const lid=add(new THREE.BoxGeometry(1.46,.16,1.46),DRMAT.dark,0,1.14,0,0,grp);let bl=null;if(!opened){bl=sprite(secure?0x7fd0ff:0xffc040,1.2);bl.position.y=1.6;grp.add(bl)}else{lid.position.set(0,.6,.9);lid.rotation.x=-1.4}
if(fl)lv.floaters.push({g:grp,y0:y,ph:rr2()*9});const I={pos:new V3(x,(y||0)+.8,z),r:2.2,done:opened,label:()=>secure?'🔒 COFFRE SÉCURISÉ · PIRATER':'📦 OUVRIR LA CAISSE',act:()=>{if(secure)hackStart({crate:I});else crateOpen(I)},secure,id,bl,lid,grp};lv.inter.push(I);return I};
const ins=(k)=>({x:x0+1.2+rr2()*(W-2.4),z:z0+1.2+rr2()*(Hh-2.4)});
if(rm.role=='airlock'){lv.start=new V3(x0+1.6,0,cz);const ring=add(new THREE.TorusGeometry(1.6,.18,8,24),new THREE.MeshBasicMaterial({color:0x5af0a0}),x0+.3,1.8,cz,Math.PI/2);lv.air={pos:new V3(x0+1,1,cz),r:2.6,label:()=>'🚀 RETOURNER AU VAISSEAU',act:()=>derExit(false)};lv.inter.push(lv.air)}
else if(rm.role=='cargo'){for(let k=0;k<3;k++){const p=ins();crate(p.x,p.z,0,k==2&&rr2()<.4)}for(let k=0;k<5;k++){const p=ins();add(new THREE.BoxGeometry(1.2+rr2(),1+rr2(),1.2+rr2()),DRMAT.crate,p.x,.6,p.z,rr2()*3)}}
else if(rm.role=='quarters'){for(let k=0;k<3;k++){const p=ins();add(new THREE.BoxGeometry(2.2,.6,1),DRMAT.door,p.x,.3,p.z,rr2()<.5?0:Math.PI/2)}const p=ins();crate(p.x,p.z,0,false);const p2=ins();termAdd(p2,logN++)}
else if(rm.role=='lab'){for(let k=0;k<2;k++){const p=ins();const tube=add(new THREE.CylinderGeometry(.6,.6,2.4,14),new THREE.MeshStandardMaterial({color:0x60ffd0,emissive:0x20a080,emissiveIntensity:.8,transparent:true,opacity:.55}),p.x,1.2,p.z)}const p=ins();termAdd(p,logN++);const p2=ins();crate(p2.x,p2.z,0,true)}
else if(rm.role=='engine'){const core=add(new THREE.CylinderGeometry(1.4,1.4,DCEIL-.4,16),new THREE.MeshStandardMaterial({color:0xff7a30,emissive:0xff5010,emissiveIntensity:1.2}),cx,(DCEIL-.4)/2,cz);for(let k=0;k<4;k++){const a=k/4*TAU;add(new THREE.BoxGeometry(.5,DCEIL,.5),DRMAT.dark,cx+Math.cos(a)*2.4,DCEIL/2,cz+Math.sin(a)*2.4)}for(let k=0;k<3;k++){const p=ins();lv.sparks.push({p:new V3(p.x,DCEIL-.3,p.z),t:rr2()*4})}const p=ins();crate(p.x,p.z,0,false)}
else if(rm.role=='armory'){for(let k=0;k<4;k++)add(new THREE.BoxGeometry(.4,2.4,1.6),DRMAT.dark,x0+.3,1.2,z0+1.5+k*2);const p=ins();crate(p.x,p.z,0,true);const p2=ins();crate(p2.x,p2.z,0,false);lv.sentry=lv.sentry||[];lv.sentry.push({x:x0+W-1,z:cz})}
else if(rm.role=='breach'){rm.zg=1;for(let k=0;k<10;k++){const p=ins(),b=add(new THREE.BoxGeometry(.6+rr2()*1.6,.4+rr2(),.6+rr2()*1.6),rr2()<.5?DRMAT.crate:DRMAT.dark,p.x,2+rr2()*9,p.z,rr2()*3);b.rotation.x=rr2()*3;lv.floaters.push({g:b,y0:b.position.y,ph:rr2()*9,spin:1})}const p=ins();crate(p.x,p.z,7+rr2()*3,true,true);const gash=add(new THREE.PlaneGeometry(W*.6,6),new THREE.MeshBasicMaterial({color:0x8fb8ff,transparent:true,opacity:.18,blending:ADDB,depthWrite:false,side:THREE.DoubleSide}),cx,DBRE-1,cz);gash.rotation.x=Math.PI/2}
else if(rm.role=='bridge'){for(let k=0;k<5;k++){const a=-1+k*.5;add(new THREE.BoxGeometry(1.6,1,.8),DRMAT.door,cx+Math.sin(a)*3.5,.5,cz-Math.cos(a)*3.5,-a);add(new THREE.PlaneGeometry(1.4,.8),new THREE.MeshBasicMaterial({color:0x4ab0ff}),cx+Math.sin(a)*3.45,1.25,cz-Math.cos(a)*3.45+.01,-a)}
const chest=new THREE.Group();chest.position.set(cx,0,cz+2);g.add(chest);add(new THREE.BoxGeometry(1.8,1.2,1.2),new THREE.MeshStandardMaterial({color:0xd8ad48,metalness:.8,roughness:.3}),0,.6,0,0,chest);const cl=sprite(0xffe08a,2.6);cl.position.y=1.8;if(!K.b)chest.add(cl);
lv.inter.push({pos:new V3(cx,1,cz+2),r:2.6,done:!!K.b,label:()=>'✨ COFFRE DU CAPITAINE',act:function(){this.done=true;chest.remove(cl);bridgeLoot(o)}});const p=ins();termAdd(p,99);lv.sentry=lv.sentry||[];lv.sentry.push({x:x0+1,z:z0+1},{x:x0+W-1,z:z0+Hh-1})}}
function termAdd(p,n){const term=add(new THREE.BoxGeometry(1,1.4,.5),DRMAT.dark,p.x,.7,p.z);const scr=add(new THREE.PlaneGeometry(.8,.5),new THREE.MeshBasicMaterial({color:0x40c0ff}),p.x,1.15,p.z+.26);const li=n==99?0:(((o.seed||7)>>>0)+n*3)%DLOGS.length,txt=n==99?DLOGS[DLOGS.length-1]:DLOGS[li];
lv.inter.push({pos:new V3(p.x,1,p.z+.4),r:2.2,done:false,label:()=>'💻 LIRE LE JOURNAL',act:function(){scr.material.color.set(0x80ff90);say([['ia','Journal récupéré — '+o.n+'.'],['echo',txt]]);cxLog(txt,'Épave du '+o.n);if(!K.lg.includes(li)){K.lg.push(li);gainXP(30);addRep('carto',15)}this.done=true}})}
// drones et tourelles
const z=Math.min(4,Math.floor(Math.hypot(o.x,o.z)/9000));for(const rm of rooms){if(rm.role=='airlock')continue;const n=rm.role=='bridge'?2:rm.role=='armory'?2:rr2()<.55?1:0;for(let k=0;k<n+(z>=2&&rr2()<.4?1:0);k++){lv.drones.push(droneMk(rm.x*DTS+1+rr2()*(rm.w*DTS-2),rm.z*DTS+1+rr2()*(rm.h*DTS-2),z))}}
for(let k=0;k<2;k++){const cells=[];for(let j=0;j<DGH;j++)for(let i=0;i<DGW;i++)if(at(i,j)==-1)cells.push([i,j]);if(cells.length){const c=cells[(rr2()*cells.length)|0];lv.drones.push(droneMk(c[0]*DTS+2.5,c[1]*DTS+2.5,z))}}
for(const s of lv.sentry||[])lv.drones.push(sentryMk(s.x,s.z,z));
return lv}
// ----- drones -----
const DRNG=new THREE.SphereGeometry(.42,16,12),DRNM=new THREE.MeshStandardMaterial({color:0x30343a,metalness:.8,roughness:.3}),DRNE=new THREE.MeshBasicMaterial({color:0xff2a20});
function droneMk(x,z,lv){const g=new THREE.Group();g.add(new THREE.Mesh(DRNG,DRNM));const eye=new THREE.Mesh(new THREE.SphereGeometry(.16,10,8),DRNE);eye.position.z=-.36;g.add(eye);const ring=new THREE.Mesh(new THREE.TorusGeometry(.55,.05,6,24),DRNM);ring.rotation.x=Math.PI/2;g.add(ring);const gl=sprite(0xff3020,1.4,.8);gl.position.z=-.4;g.add(gl);
for(const s of[-1,1]){const f=new THREE.Mesh(new THREE.BoxGeometry(.5,.06,.25),DRNM);f.position.x=s*.6;g.add(f)}g.position.set(x,2.2,z);return{g,pos:g.position,vel:new V3(),hp:4+lv*.8,mhp:4+lv*.8,cd:1+Math.random(),tg:null,st:'patrol',seen:0,kind:'drone',dmg:5+lv,ring}}
function sentryMk(x,z,lv){const g=new THREE.Group();g.add(new THREE.Mesh(new THREE.CylinderGeometry(.5,.7,.6,10),DRNM));const head=new THREE.Group();head.position.y=.6;g.add(head);head.add(new THREE.Mesh(new THREE.SphereGeometry(.38,12,10),DRNM));for(const s of[-1,1]){const b=new THREE.Mesh(new THREE.CylinderGeometry(.06,.06,.9,6).rotateX(Math.PI/2),DRNM);b.position.set(s*.16,0,-.45);head.add(b)}const eye=new THREE.Mesh(new THREE.SphereGeometry(.1,8,6),DRNE);eye.position.z=-.34;head.add(eye);
g.position.set(x,0,z);return{g,pos:new V3(x,1,z),vel:new V3(),hp:14+lv*2,mhp:14+lv*2,cd:2,st:'sentry',head,kind:'sentry',dmg:6+lv,burst:0,static:1}}
// ----- collisions -----
function dSolid(x,z){const lv=DER.lvl;if(!lv)return true;const i=Math.floor(x/DTS),j=Math.floor(z/DTS);if(lv.L.at(i,j)<-1)return true;for(const D2 of lv.doorsM){if(D2.open>.85)continue;const a=D2.ax=='x'?x:z,b=D2.ax=='x'?z:x;if(Math.abs(a-D2.line)<.3&&Math.abs(b-D2.c)<DTS/2)return true}return false}
const dFree=(x,z,r)=>!dSolid(x-r,z-r)&&!dSolid(x+r,z-r)&&!dSolid(x-r,z+r)&&!dSolid(x+r,z+r);
function dLOS(a,b){const d=a.distanceTo(b),n=Math.ceil(d/.4);for(let k=1;k<n;k++){const f=k/n;if(dSolid(lerp(a.x,b.x,f),lerp(a.z,b.z,f)))return false}return true}
const dRoom=(x,z)=>{const lv=DER.lvl;if(!lv)return null;const v=lv.L.at(Math.floor(x/DTS),Math.floor(z/DTS));return v>=0?lv.L.rooms[v]:null};
const dCeil=(x,z)=>{const rm=dRoom(x,z);return rm&&rm.role=='breach'?DBRE:DCEIL};
// ----- entrer / sortir -----
function derEnter(){const q=DRH.near;if(!q||mode!='space')return;FADE.col='0,0,0';FADE.tg=1;FADE.sp=5;SFX.buy();tone(180,90,.6,'sawtooth',.05);
setTimeout(()=>{if(DER.lvl&&DER.lvl.o.id!==q.id){DER.scene.remove(DER.lvl.g);DER.lvl.g.traverse(m=>{if(m.geometry)m.geometry.dispose()});for(const d of DER.lvl.drones)d.g.parent&&d.g.parent.remove(d.g);DER.lvl=null}
if(!DER.lvl){DER.lvl=derBuild(q);DER.scene.add(DER.lvl.g)}const lv=DER.lvl;for(const d of lv.drones){if(d.hp<=0&&!d.static){d.hp=d.mhp}if(d.hp>0&&!d.g.parent)DER.scene.add(d.g)}
DER.on={q,air:S.pos.clone(),aq:S.q.clone()};DER.p.copy(lv.start);DER.vel.set(0,0,0);DER.vy=0;FOOT.cy=-Math.PI/2;FOOT.cp=.12;DER.yaw=FOOT.cy;DER.fuel=1;
if(!DER.model)DER.model=buildHuman({suit:new THREE.Color().setHSL(((typeof MP!='undefined'?MP.hue:200))/360,.3,.78).getHex(),acc:0xff8a2a,tool:true,skin:0xe0b090,helmet:true,closed:true,visor:0x3a6a8a});if(DER.model.parent!==DER.scene)DER.scene.add(DER.model);
DER.scene.add(SPK.pts,FIRE.pts);SPK.clear();FIRE.clear();DER.psz=[SPK.pts.material.size,FIRE.pts.material.size];SPK.pts.material.size=.35;FIRE.pts.material.size=1.6;mode='int';S.docked=null;landP=null;S.spd=0;S.vel.set(0,0,0);S.thr=0;clearWeapons();ship.visible=false;camInit=true;btnSet('fire','tool','Tirer');btnSet('boost','jump','Saut');btnSet('brake','run','Course');document.body.classList.add('foot');setD('footb','none');
FADE.tg=0;FADE.sp=1.2;toast('🛸 Tu entres dans l\'épave du '+q.n+' — trouve la passerelle. '+(DESK?'ZQSD pour marcher, clic pour tirer, E pour interagir':'Joystick pour marcher, glisse à droite pour regarder'));save()},260)}
function derExit(silent){if(mode!='int')return;const on=DER.on;DER.on=null;DER.hack=null;DER.map=false;mode='space';ship.visible=true;scene.add(SPK.pts,FIRE.pts);SPK.clear();FIRE.clear();if(DER.psz){SPK.pts.material.size=DER.psz[0];FIRE.pts.material.size=DER.psz[1]}document.body.classList.remove('foot');btnSet('fire','fire','Feu');btnSet('boost','boost','Boost');btnSet('brake','brake','Frein');for(const b of DER.pb)b.m.parent&&b.m.parent.remove(b.m);for(const b of DER.eb)b.m.parent&&b.m.parent.remove(b.m);DER.pb=[];DER.eb=[];
try{if(document.pointerLockElement)document.exitPointerLock()}catch(e){}camInit=true;lastCK='';streamWorld();if(silent||!on)return;const q=DRH.act.get(on.q.id)||on.q;const ap=q.mesh?derAirPos(q):on.air;const out=ap.clone().sub(q.mesh?q.mesh.position:ap).normalize();S.pos.copy(ap).addScaledVector(out,40);S.q.setFromUnitVectors(new V3(0,0,-1),out);S.vel.set(0,0,0);S.spd=0;FADE.col='0,0,0';FADE.v=1;FADE.tg=0;FADE.sp=1.5;SFX.buy();toast('🚀 De retour à bord');save()}
// ----- butin -----
function crateOpen(I){I.done=true;const K=DERD[DER.on.q.id];if(!K.c.includes(I.id))K.c.push(I.id);if(I.bl)I.grp.remove(I.bl);I.lid.position.set(0,.6,.9);I.lid.rotation.x=-1.4;boom3(I.pos.clone(),10,0xffc040,4);SFX.win();
let cr=I.secure?250+Math.floor(Math.random()*350):60+Math.floor(Math.random()*140);G.cr+=cr;let txt='+'+cr+' ¢';const pool=I.secure?['lux','cristal','or','elec']:Math.random()<.12?ILLG.map(g=>g.id):['metal','elec','med','lux','titane','cristal'],id=pool[Math.random()*pool.length|0],q=Math.min(I.secure?3+(Math.random()*4|0):1+(Math.random()*3|0),cap()-cargoUsed());
if(q>0){G.cargo[id]=(G.cargo[id]||0)+q;txt+=' · '+q+' '+matG(id).n}if(I.secure&&Math.random()<.25&&cargoUsed()<cap()){G.cargo.exo=(G.cargo.exo||0)+1;txt+=' · 1 matière exotique'}if(!I.secure&&Math.random()<.2){const am=Math.random()<.5?'missile':'mine';G.ammo[am]=(G.ammo[am]||0)+(am=='missile'?3:2);txt+=' · munitions'}
toast((I.secure?'🔓 Coffre ouvert : ':'📦 Caisse : ')+txt);gainXP(I.secure?50:15);if(I.secure&&Math.random()<.3+rankOf('carto')*.03)setTimeout(giveBlueprint,1200);save()}
function bridgeLoot(o){const K=DERD[o.id];const first=!K.b;K.b=1;SFX.win();boom3(DER.p.clone().add(new V3(0,1.5,0)),20,0xffe08a,5);if(first){STS.ders++;CX.der[o.id]={n:o.n,t:Date.now()};G.cr+=1500;gainXP(300);addRep('carto',80);addRep('guilde',40);banner('star','Passerelle du '+o.n+' atteinte !','Coffre du capitaine : +1 500 ¢ et un plan de fabrication','#ffe08a');setTimeout(giveBlueprint,1500)}else{G.cr+=200;toast('Le coffre est vide… sauf 200 ¢ oubliés')}if(typeof fmEvent=='function')fmEvent('bridge',o.id);save()}
// ----- piratage (mini-jeu : appuyer quand l'aiguille passe dans la zone) -----
function hackStart(tg){if(DER.hack)return;DER.hack={tg,k:0,a:0,sp:2.6,z:1+Math.random()*4,w:.75,pos:DER.p.clone()};SFX.tick();tone(400,600,.1,'square',.04)}
function hackPress(){const H=DER.hack;if(!H)return;const a=((H.a%TAU)+TAU)%TAU,dz=Math.atan2(Math.sin(a-H.z),Math.cos(a-H.z));if(Math.abs(dz)<H.w/2){H.k++;tone(700+H.k*200,900+H.k*200,.12,'square',.05);if(H.k>=3){hackDone(H);return}H.z=Math.random()*TAU;H.sp*=1.18;H.w*=.9}
else{H.k=Math.max(0,H.k-1);tone(200,120,.3,'sawtooth',.06);toast('⚠ Erreur de code : alarme déclenchée !');const lv=DER.lvl;const p=DER.p.clone().add(new V3(rv(4),0,rv(4)));if(dFree(p.x,p.z,.5)){const d=droneMk(p.x,p.z,1);d.st='chase';lv.drones.push(d);DER.scene.add(d.g)}}}
function hackDone(H){DER.hack=null;STS.hacks++;SFX.win();gainXP(25);if(H.tg.door){const D2=H.tg.door;D2.lock=false;D2.strip.material.color.setHex(0x40ff90);const K=DERD[DER.on.q.id];(K.dh=K.dh||[]).push(D2.d.i+','+D2.d.j);const I=DER.lvl.inter.find(x=>x.door===D2);if(I)I.done=true;toast('🔓 Porte déverrouillée')}else if(H.tg.crate)crateOpen(H.tg.crate)}
// ----- boucle intérieure -----
const _d1=new V3(),_d2=new V3(),_d3=new V3();
function derUpdate(dt){const lv=DER.lvl;if(!lv||!DER.on)return;const P=DER.p;
// déplacement
let ix=0,iz=0;if(stick&&Math.hypot(stick.x,stick.y)>.1){ix=stick.x;iz=-stick.y}ix+=(K.KeyD|K.ArrowRight|0)-(K.KeyA|K.ArrowLeft|0);iz+=(K.KeyW|K.ArrowUp|0)-(K.KeyS|K.ArrowDown|0);const il=Math.hypot(ix,iz);if(il>1){ix/=il;iz/=il}
if(DESK&&!document.pointerLockElement&&MS.in&&Math.abs(MS.x)>.2)FOOT.cy-=(MS.x-Math.sign(MS.x)*.2)*1.8*dt;
const rm=dRoom(P.x,P.z),zg=rm&&rm.zg,fw=_d1.set(-Math.sin(FOOT.cy),0,-Math.cos(FOOT.cy)),rt=_d2.set(Math.cos(FOOT.cy),0,-Math.sin(FOOT.cy)),run=B.brake||K.ShiftLeft||K.ShiftRight,sp=(run?9:5.2)*(zg?.7:1);
const want=_d3.copy(fw).multiplyScalar(iz).addScaledVector(rt,ix).multiplyScalar(sp),kk=DER.grounded&&!zg?12:zg?1.6:3;DER.vel.x=lerp(DER.vel.x,want.x,damp(kk,dt));DER.vel.z=lerp(DER.vel.z,want.z,damp(kk,dt));
const hs=Math.hypot(DER.vel.x,DER.vel.z);if(hs>.4){const ty=Math.atan2(-DER.vel.x,-DER.vel.z);let d=ty-DER.yaw;d=Math.atan2(Math.sin(d),Math.cos(d));DER.yaw+=d*damp(10,dt);if(!FOOT.drag&&!document.pointerLockElement&&!DESK&&t-FOOT.lastLook>1.2){let e=DER.yaw-FOOT.cy;e=Math.atan2(Math.sin(e),Math.cos(e));FOOT.cy+=e*damp(1.2,dt)*Math.min(1,hs/5)}}if(isFire())DER.yaw=FOOT.cy;
const jump=B.boost||K.Space,ceil=dCeil(P.x,P.z);if(zg){DER.vy-=1.1*dt;if(jump&&DER.fuel>0){DER.vy=Math.min(4.5,DER.vy+12*dt);DER.fuel-=dt*.25;if(Math.random()<.5)FIRE.emit(P.x,P.y+1,P.z,rv(1),-4,rv(1),.25,.6,.75,1,.12)}if(DER.grounded)DER.fuel=Math.min(1,DER.fuel+dt*.4)}
else{if(DER.grounded){DER.fuel=Math.min(1,DER.fuel+dt*.5);if(jump&&!DER.jl){DER.vy=6.4;DER.grounded=false;tone(200,320,.1,'sine',.04)}}DER.vy-=18*dt}DER.jl=jump;
const nx=P.x+DER.vel.x*dt;if(dFree(nx,P.z,.42))P.x=nx;else DER.vel.x=0;const nz=P.z+DER.vel.z*dt;if(dFree(P.x,nz,.42))P.z=nz;else DER.vel.z=0;P.y+=DER.vy*dt;if(P.y>ceil-1.9){P.y=ceil-1.9;DER.vy=Math.min(0,DER.vy)}if(P.y<=0){P.y=0;if(DER.vy<-14)damage((-DER.vy-14)*.6,'col');DER.vy=0;DER.grounded=true}else if(P.y>.05)DER.grounded=false;
DER.ph+=dt*hs*1.3;const m=DER.model;m.position.copy(P);m.rotation.y=DER.yaw;animHuman(m,DER.ph,hs,!DER.grounded,isFire(),0,null);
// portes automatiques
for(const D2 of lv.doorsM){const near=!D2.lock&&Math.hypot(D2.pos.x-P.x,D2.pos.z-P.z)<3.2;const o0=D2.open;D2.open=clamp(D2.open+(near?dt*2.6:-dt*1.8),0,1);D2.panel.position.y=DCEIL/2+D2.open*(DCEIL-.4);if(o0<.02&&D2.open>=.02)tone(160,260,.35,'sawtooth',.02)}
// objets flottants, étincelles
for(const f of lv.floaters){f.g.position.y=f.y0+Math.sin(t*.6+f.ph)*.35;if(f.spin){f.g.rotation.y+=dt*.2;f.g.rotation.x+=dt*.1}}
for(const s of lv.sparks){s.t-=dt;if(s.t<0){if(s.t<-.6)s.t=2+Math.random()*3;if(Math.random()<.6)SPK.emit(s.p.x,s.p.y,s.p.z,rv(2),-1-Math.random()*3,rv(2),.5,1,.8,.4,.25);if(Math.hypot(P.x-s.p.x,P.z-s.p.z)<1.4&&t-(DER.spT||0)>.5){DER.spT=t;damage(4);toast('⚡ Câbles électriques !')}}}
for(const I of lv.inter)if(I.bl&&!I.done)I.bl.scale.setScalar(1.1+Math.sin(t*4)*.15);
// piratage : annulé si on s'éloigne
if(DER.hack){DER.hack.a+=DER.hack.sp*dt;if(DER.hack.pos.distanceTo(P)>3){DER.hack=null;toast('Piratage interrompu')}}
derDrones(dt);derShoot(dt);
// la touche F remonte à bord près du sas
if(K.KeyF&&!DER.kf&&lv.air&&lv.air.pos.distanceTo(P)<3)derExit(false);DER.kf=K.KeyF;
// lumières : les 5 plus proches
DER.lightsT-=dt;if(DER.lightsT<=0){DER.lightsT=.4;const A=lv.anchors.map(a=>[a,Math.hypot(a.x-P.x,a.z-P.z)]).sort((x,y)=>x[1]-y[1]).slice(0,DRPL.length);DRPL.forEach((L,i)=>{const a=A[i]&&A[i][0];if(!a){L.intensity=0;return}L.position.set(a.x,a.y,a.z);L.color.setHex(a.c);L.userData.k=a.k;L.userData.fl=a.fl})}
DRPL.forEach(L=>{const k=L.userData.k||0;L.intensity=k*(L.userData.fl?(.7+.3*Math.sin(t*23+L.position.x)*(Math.random()<.04?0:1)):1)});
S.hp=Math.min(S.hp,maxhp());if(S.hp<=0)die()}
function derDrones(dt){const lv=DER.lvl,P=DER.p,chest=_d1.set(P.x,P.y+1.3,P.z);for(const d of lv.drones){if(d.hp<=0)continue;const dist=d.pos.distanceTo(chest);
if(d.static){if(dist<26&&dLOS(d.pos,chest)){d.head.lookAt(chest.x,chest.y-.0,chest.z);d.head.rotateY(Math.PI);d.cd-=dt;if(d.cd<=0){if(d.burst<=0){d.burst=3}d.cd=d.burst>1?.18:2.4;d.burst--;dShot(d,chest,26)}}continue}
const see=dist<22&&dLOS(d.pos,chest);if(see){d.st='chase';d.seen=t}else if(d.st=='chase'&&t-d.seen>6)d.st='patrol';let goal;
if(d.st=='chase'){const away=_d2.copy(d.pos).sub(chest);away.y=0;const L=away.length()||1;away.divideScalar(L);const k=L<5?1:L>9?-1:0;goal=_d3.copy(d.pos).addScaledVector(away,k*3).add(new V3(Math.cos(t*1.3+d.mhp)*1.5,0,Math.sin(t*1.1+d.mhp)*1.5));goal.y=clamp(chest.y+.8,1,dCeil(d.pos.x,d.pos.z)-.6);
if(see){d.cd-=dt;if(d.cd<=0){d.cd=1.2+Math.random()*.6;dShot(d,chest,20)}}}
else{if(!d.tg||d.pos.distanceTo(d.tg)<1){const i=Math.floor(d.pos.x/DTS)+((Math.random()*5|0)-2),j=Math.floor(d.pos.z/DTS)+((Math.random()*5|0)-2);if(lv.L.at(i,j)>=-1)d.tg=new V3(i*DTS+DTS/2,2.2,j*DTS+DTS/2)}goal=d.tg||d.pos}
const to=_d2.copy(goal).sub(d.pos),L2=to.length();if(L2>.05){to.multiplyScalar(Math.min(1,L2)/L2);d.vel.lerp(to.multiplyScalar(d.st=='chase'?4.5:2.2),damp(3,dt))}else d.vel.multiplyScalar(.9);
const nx=d.pos.x+d.vel.x*dt,nz=d.pos.z+d.vel.z*dt;if(dFree(nx,d.pos.z,.45))d.pos.x=nx;else{d.vel.x*=-.5;d.tg=null}if(dFree(d.pos.x,nz,.45))d.pos.z=nz;else{d.vel.z*=-.5;d.tg=null}d.pos.y=clamp(d.pos.y+d.vel.y*dt,.8,dCeil(d.pos.x,d.pos.z)-.5);
if(d.st=='chase')d.g.lookAt(chest);else d.g.lookAt(_d3.copy(d.pos).add(d.vel));d.g.rotateY(Math.PI);d.ring.rotation.z+=dt*3;if(dist<12&&Math.random()<dt*.6)tone(1400+Math.random()*400,1500,.05,'sine',.012)}}
const DRBG=new THREE.CylinderGeometry(.05,.05,.8,5).rotateX(Math.PI/2),DRBM={p:new THREE.MeshBasicMaterial({color:0xffa060}),e:new THREE.MeshBasicMaterial({color:0xff3a30})};
function dBolt(list,o,dir,sp,dmg,mat,col){const m=new THREE.Mesh(DRBG,mat);const s=sprite(col,.9,.9);m.add(s);m.position.copy(o);m.lookAt(o.clone().add(dir));DER.scene.add(m);list.push({m,p:m.position,v:dir.clone().multiplyScalar(sp),l:2,d:dmg,col})}
function dShot(d,tg,sp){const dir=tg.clone().addScaledVector(DER.vel,d.pos.distanceTo(tg)/sp*.6).add(new V3(rv(.25),rv(.2),rv(.25))).sub(d.pos).normalize();dBolt(DER.eb,d.pos.clone().addScaledVector(dir,.6),dir,sp,d.dmg,DRBM.e,0xff3a30);tone(jit(520),180,.12,'sawtooth',.03)}
function derShoot(dt){const P=DER.p,lv=DER.lvl;DER.tcd-=dt;if(isFire()&&!DER.hack&&DER.tcd<=0){DER.tcd=.22;const hand=DER.model.userData.tool?DER.model.userData.tool.getWorldPosition(_d1).clone():P.clone().add(new V3(0,1.3,0));let dir=new V3(0,0,-1).applyQuaternion(camera.quaternion);if(!COCKPIT){dir.y=Math.sin(-FOOT.cp*.5+.04);dir.normalize()}
let best=null,ba=.32;for(const d of lv.drones){if(d.hp<=0)continue;const v=d.pos.clone().sub(hand),L=v.length();if(L>30)continue;const a=Math.acos(clamp(v.dot(dir)/L,-1,1));if(a<ba&&dLOS(hand,d.pos)){ba=a;best=d}}if(best)dir=best.pos.clone().sub(hand).normalize();DER.yaw=FOOT.cy;
dBolt(DER.pb,hand.clone().addScaledVector(dir,.4),dir,42,1.4+G.u[0]*.15,DRBM.p,0xffa060);fxGlow(hand,0xff9a50,.8,.08,1.5,DER.scene);tone(jit(900),260,.08,'square',.03)}
const step=(list,isP)=>{for(const b of list){const a=b.p.clone();b.p.addScaledVector(b.v,dt);b.l-=dt;if(dSolid(b.p.x,b.p.z)||b.p.y<0||b.p.y>dCeil(b.p.x,b.p.z)){b.l=0;SPK.emit(a.x,a.y,a.z,rv(3),rv(3),rv(3),.3,1,.6,.3,.2)}
if(b.l>0&&isP){for(const d of lv.drones){if(d.hp<=0)continue;if(segHit(a,b.p,d.pos,d.static?.7:.55)){b.l=0;d.hp-=b.d;SPK.emit(b.p.x,b.p.y,b.p.z,rv(3),rv(3),rv(3),.4,1,.7,.3,.25);tone(1200,600,.05,'square',.03);if(d.st!='sentry')d.st='chase',d.seen=t;if(d.hp<=0)droneDie(d);break}}}
else if(b.l>0){const c=_d2.set(P.x,P.y+1.1,P.z);if(segHit(a,b.p,c,.55)){b.l=0;damage(b.d);hurt=Math.min(.5,hurt+.15)}}if(b.l<=0)b.m.parent&&b.m.parent.remove(b.m)}return list.filter(b=>b.l>0)};DER.pb=step(DER.pb,true);DER.eb=step(DER.eb,false)}
function droneDie(d){d.hp=0;boom3(d.pos.clone(),18,0xff7030,6);fxGlow(d.pos.clone(),0xffa050,4,.3,2,DER.scene);noise(.3,.3,1200);d.g.parent&&d.g.parent.remove(d.g);const cr=d.static?120:40;G.cr+=cr;gainXP(d.static?40:15);STS.k[d.kind]=(STS.k[d.kind]||0)+1;STS.drones++;cxAdd('en',d.kind);toast((d.static?'Tourelle détruite':'Drone abattu')+' · +'+cr+' ¢')}
// ----- interface : action, invite, caméra, HUD -----
function derNearI(){const lv=DER.lvl;if(!lv)return null;let b=null,bd=1e9;for(const I of lv.inter){if(I.done)continue;const d=Math.hypot(I.pos.x-DER.p.x,I.pos.z-DER.p.z),dy=Math.abs(I.pos.y-(DER.p.y+.8));if(d<I.r&&dy<2.6&&d<bd){bd=d;b=I}}return b}
function derPrompt(){if(DER.hack)return'🔓 VALIDER LE CODE';const I=derNearI();return I?I.label():''}
function derAction(){if(DER.hack){hackPress();return}const I=derNearI();if(I){I.act();SFX.tick()}}
function derCam(dt){const P=DER.p;if(COCKPIT){camera.position.set(P.x,P.y+1.68,P.z);camera.quaternion.setFromEuler(new THREE.Euler(-FOOT.cp*.8,FOOT.cy,0,'YXZ'))}
else{const head=_d1.set(P.x,P.y+1.55,P.z),fw=_d2.set(-Math.sin(FOOT.cy),0,-Math.cos(FOOT.cy)),cp=FOOT.cp,dist=4.3,rt=new V3(Math.cos(FOOT.cy),0,-Math.sin(FOOT.cy));const want=_d3.copy(head).addScaledVector(fw,-dist*Math.cos(cp)).add(new V3(0,dist*Math.sin(cp)+.45,0)).addScaledVector(rt,.85);
// la caméra ne traverse pas les murs
const n=12;let ok=head.clone();for(let k=1;k<=n;k++){const q=head.clone().lerp(want,k/n);if(dSolid(q.x,q.z)||!dFree(q.x,q.z,.18))break;ok=q}ok.y=Math.min(ok.y,dCeil(ok.x,ok.z)-.25);if(camInit){camera.position.copy(ok);camInit=false}else camera.position.lerp(ok,damp(14,dt));camera.up.set(0,1,0);camera.lookAt(head.clone().addScaledVector(fw,2.5))}
if(shake>0){camera.position.x+=rv(shake*.15);camera.position.y+=rv(shake*.15);shake=Math.max(0,shake-dt*2.5)}const fv=innerWidth<innerHeight?78:66;if(Math.abs(camera.fov-fv)>.05){camera.fov=fv;camera.updateProjectionMatrix()}
const lf=new V3(0,0,-1).applyQuaternion(camera.quaternion);DRLAMP.position.set(P.x,P.y+1.62,P.z).addScaledVector(lf,.35);DRLAMP.target.position.copy(DRLAMP.position).addScaledVector(lf,10);if(DER.model)DER.model.visible=!COCKPIT&&camera.position.distanceTo(_d1.set(P.x,P.y+1.5,P.z))>1.5}
function derInfo(){const o=DER.on&&DER.on.q,lv=DER.lvl;const rm=dRoom(DER.p.x,DER.p.z);const RN={airlock:'Sas d\'amarrage',bridge:'Passerelle',cargo:'Soute',quarters:'Quartiers',engine:'Salle des machines',lab:'Laboratoire',armory:'Armurerie',breach:'Soute éventrée (apesanteur)'};const left=lv?lv.inter.filter(I=>I.secure!=null&&!I.done).length:0,dr=lv?lv.drones.filter(d=>d.hp>0).length:0;
return{info:`<span style="color:#c8c0b0">🛸 Épave du ${o?esc(o.n):'?'}</span><br><span style="color:#9fd8ff">${rm?RN[rm.role]:'Couloir'}</span>${rm&&rm.zg?'<br><b style="color:#7ab6ff">Apesanteur : maintiens SAUT pour monter</b>':''}`,sub:`<span title="Caisses">${ICO('cargo')}<b>${left}</b></span><span title="Drones">${ICO('target')}<b>${dr}</b></span>`,zone:[(DERD[o&&o.id]||{}).b?'Passerelle visitée ✓':'Objectif : la passerelle','#c8c0b0']}}
function derRadar(blip){const lv=DER.lvl;if(!lv)return;for(const I of lv.inter){if(I.done)continue;blip(I.pos,I.door?'#ff5050':I===lv.air?'#5af0a0':I.label().startsWith('✨')?'#ffe08a':'#ffc040',2)}for(const d of lv.drones)if(d.hp>0)blip(d.pos,'#ff4d4d',2.2)}
function derOverlay(W,H){const lv=DER.lvl;if(!lv)return;const sp=S.pos.clone(),sq=S.q.clone();S.pos.set(DER.p.x,DER.p.y+1,DER.p.z);S.q.setFromEuler(new THREE.Euler(0,FOOT.cy,0));try{radar()}finally{S.pos.copy(sp);S.q.copy(sq)}
// réticule
if(!COCKPIT||true){OX.strokeStyle='rgba(255,210,160,.8)';OX.lineWidth=1.5;OX.beginPath();OX.arc(W/2,H/2,7,0,TAU);OX.stroke()}
for(const d of lv.drones){if(d.hp<=0||d.hp>=d.mhp)continue;const s=proj(d.pos);if(!s.front||s.d>30)continue;OX.fillStyle='rgba(0,0,0,.5)';OX.fillRect(s.x-16,s.y-24,32,4);OX.fillStyle='#ff5050';OX.fillRect(s.x-16,s.y-24,32*d.hp/d.mhp,4)}
const I=derNearI();if(I){const s=proj(I.pos.clone().add(new V3(0,1,0)));if(s.front){OX.fillStyle='#ffd257';OX.font="700 12px 'Chakra Petch',system-ui";OX.textAlign='center';OX.fillText('◆',s.x,s.y)}}
const rm=dRoom(DER.p.x,DER.p.z);if(rm&&rm.zg||DER.fuel<.99){const bw=90,bx=W/2-bw/2,by=H-(DESK?60:250);OX.fillStyle='rgba(0,0,0,.45)';OX.fillRect(bx,by,bw,6);OX.fillStyle='#ffb040';OX.fillRect(bx,by,bw*DER.fuel,6);OX.font="700 10px 'Chakra Petch',system-ui";OX.fillStyle='#ffd8a0';OX.textAlign='center';OX.fillText('JETPACK',W/2,by-4)}
// mini-jeu de piratage
const Hk=DER.hack;if(Hk){const cx=W/2,cy=H*.42,R=Math.min(W,H)*.14;OX.fillStyle='rgba(4,10,20,.82)';OX.beginPath();OX.arc(cx,cy,R+26,0,TAU);OX.fill();OX.strokeStyle='rgba(120,200,255,.35)';OX.lineWidth=10;OX.beginPath();OX.arc(cx,cy,R,0,TAU);OX.stroke();OX.strokeStyle='#5af0a0';OX.lineWidth=12;OX.beginPath();OX.arc(cx,cy,R,Hk.z-Hk.w/2,Hk.z+Hk.w/2);OX.stroke();
const a=Hk.a;OX.strokeStyle='#ffd257';OX.lineWidth=3;OX.beginPath();OX.moveTo(cx,cy);OX.lineTo(cx+Math.cos(a)*(R+10),cy+Math.sin(a)*(R+10));OX.stroke();for(let k=0;k<3;k++){OX.fillStyle=k<Hk.k?'#5af0a0':'rgba(255,255,255,.2)';OX.beginPath();OX.arc(cx-16+k*16,cy,5,0,TAU);OX.fill()}
OX.fillStyle='#cdf2ff';OX.font="700 13px 'Chakra Petch',system-ui";OX.textAlign='center';OX.fillText('PIRATAGE — appuie quand l\'aiguille est dans la zone verte',cx,cy+R+44)}
// plan du pont (bouton carte)
if(DER.map){const s=Math.min(W*.9/(DGW*DTS),H*.7/(DGH*DTS)),ox=(W-DGW*DTS*s)/2,oy=(H-DGH*DTS*s)/2;OX.fillStyle='rgba(3,6,12,.86)';OX.fillRect(0,0,W,H);for(let j=0;j<DGH;j++)for(let i=0;i<DGW;i++){const v=lv.L.at(i,j);if(v<-1)continue;OX.fillStyle=v==-1?'rgba(120,160,200,.35)':lv.L.rooms[v].role=='bridge'?'rgba(255,224,138,.5)':lv.L.rooms[v].role=='airlock'?'rgba(90,240,160,.45)':'rgba(140,180,220,.25)';OX.fillRect(ox+i*DTS*s,oy+j*DTS*s,DTS*s-1,DTS*s-1)}
for(const D2 of lv.doorsM){if(!D2.lock)continue;OX.fillStyle='#ff4040';OX.fillRect(ox+D2.pos.x*s-3,oy+D2.pos.z*s-3,6,6)}OX.fillStyle='#fff';OX.beginPath();OX.arc(ox+DER.p.x*s,oy+DER.p.z*s,5,0,TAU);OX.fill();OX.fillStyle='#cdf2ff';OX.font="700 14px 'Chakra Petch',system-ui";OX.textAlign='center';OX.fillText('Plan du pont — '+DER.on.q.n+' (touche la carte pour fermer)',W/2,oy-14)}}
{const _om=openMap;openMap=function(){if(mode=='int'){DER.map=!DER.map;SFX.tick();return}_om()}}
OV.addEventListener('pointerdown',e=>{if(mode=='int'&&DER.map){DER.map=false}});
