// ===== MISSIONS DE FACTION : trois chaînes de 5 missions scénarisées (dialogues, choix, récompense unique) =====
Object.assign(CHAR,{dorn:{n:'Amiral Dorn',ic:'🎖️',c:'#7ab6ff'},brakka:{n:'Brakka, maîtresse de la Guilde',ic:'⛏️',c:'#ffb050'},lio:{n:'Lio, archiviste des Cartographes',ic:'🗺️',c:'#9fe8b0'},sable:{n:'Sable, lieutenant de Corbeau',ic:'🏴‍☠️',c:'#ff8a8a'}});
Object.assign(CHTXT,{dorn:'Commandant de la flotte de l\'Alliance. Droit, exigeant, il ne pardonne jamais une trahison.',brakka:'Elle a creusé son premier tunnel à neuf ans. Aujourd\'hui, la moitié des foreuses du secteur lui obéissent.',lio:'Archiviste passionné, persuadé que la galaxie cache une carte plus ancienne que toutes les autres.',sable:'Bras droit de Corbeau. Charmeur, imprévisible, et toujours prêt à négocier.'});
PARTS.eng.o.voile={n:'Voile stellaire',p:0,uniq:1,d:'Vitesse +35 % et boost +30 %. Flamme azur. Pièce unique des Cartographes.',spd:1.35,boost:1.3,col:0x7fe8ff};
const FM=GX('fm',{});for(const f of['alliance','guilde','carto'])FM[f]=FM[f]|0;if(typeof FM.fl!='object'||!FM.fl)FM.fl={};
const FMS={ents:[],foes:[],chc:null};
// ----- outils de position -----
function awayPt(dist,jit){const d=new V3(S.pos.x,0,S.pos.z);if(d.length()<2000)d.set(rv(1),0,rv(1));d.normalize();const p=S.pos.clone().addScaledVector(d,dist).addScaledVector(new V3(-d.z,0,d.x),rv(jit||dist*.3));p.y=clamp(S.pos.y+rv(400),-1500,1500);return{x:p.x|0,y:p.y|0,z:p.z|0}}
function stNear(pred,minD,maxD){const cx=cof(S.pos.x),cz=cof(S.pos.z);let best=null,bd=1e12;for(let i=-5;i<=5;i++)for(let l=-5;l<=5;l++)for(let j=-1;j<=1;j++){const s=cdata(cx+i,j,cz+l).st;if(!s||(S.docked&&s.n==S.docked.n))continue;const d=Math.hypot(s.x-S.pos.x,s.z-S.pos.z);if(d<minD||d>maxD||(pred&&!pred(s)))continue;if(d<bd){bd=d;best=s}}return best&&{n:best.n,x:best.x|0,y:best.y|0,z:best.z|0}}
function richNear(){const cx=cof(S.pos.x),cz=cof(S.pos.z);let best=null,bd=1e12;for(let i=-4;i<=4;i++)for(let l=-4;l<=4;l++)for(let j=-1;j<=1;j++){const c=cdata(cx+i,j,cz+l);if(c.sun||c.ast.length<=18)continue;const k=c.k,done=RICHD[k];if(done&&Date.now()-done<2*3600e3)continue;const q=richPos(c),p={x:q.x|0,y:q.y|0,z:q.z|0},d=Math.hypot(p.x-S.pos.x,p.z-S.pos.z);if(d<bd){bd=d;best=p}}return best}
const P3=o=>new V3(o.x,o.y,o.z);
// ----- les trois chaînes -----
const FMC={
alliance:{n:'Opération Bouclier',who:'dorn',ic:'shield',col:'#7ab6ff',where:st=>stFac(st)!='pirates',M:[
{t:'Patrouille de frontière',rk:1,rw:{cr:1200,xp:200,rep:150},intro:[['dorn','Pilote, ici l\'Amiral Dorn. On me dit que tu sais tenir un manche.'],['dorn','Les pirates harcèlent nos patrouilles à la frontière. Va nettoyer le point que je t\'envoie : quatre chasseurs, pas de quartier.']],
init:d=>{d.p=awayPt(7500)},steps:[{k:'kill',n:4,tys:['pirate','pirate','chasseur','pirate'],txt:'Nettoie le point de patrouille'}],outro:[['dorn','Proprement fait. Reviens me voir : j\'aurai bientôt du travail sérieux.']]},
{t:'Le convoi Hestia',rk:1,rw:{cr:1800,xp:260,rep:180},intro:[['dorn','Un convoi de médicaments doit rejoindre une station voisine. Les pirates l\'attendent, j\'en mettrais ma main au feu.'],['dorn','Rejoins le cargo Hestia au point de rendez-vous et escorte-le jusqu\'à destination. S\'il tombe, tu recommences.']],
init:d=>{const p=S.pos.clone().addScaledVector(fwd(),900);d.a={x:p.x|0,y:p.y|0,z:p.z|0};d.st=stNear(null,4500,10000)||stNear(null,2500,16000)||{n:'Base Alpha',x:0,y:0,z:0}},steps:[{k:'goto',at:'a',r:450,txt:'Rejoins le cargo Hestia'},{k:'escort',txt:d=>'Escorte le cargo jusqu\'à '+d.st.n}],outro:[['dorn','Le convoi est arrivé entier. L\'Alliance n\'oublie pas ses amis.']]},
{t:'La taupe',rk:2,rw:{cr:2200,xp:320,rep:220},intro:[['dorn','Quelqu\'un renseigne Corbeau sur nos patrouilles. Nos analystes ont repéré une balise d\'émission clandestine.'],['dorn','Approche-toi et reste près d\'elle le temps du scan. Discrètement… enfin, essaie.']],
init:d=>{d.p=awayPt(6500)},steps:[{k:'scan',r:300,dur:5,txt:'Scanne la balise clandestine'},{k:'kill',n:3,tys:['chasseur','chasseur','chasseur'],txt:'Embuscade ! Abats les intercepteurs',say:[['ia','Alerte : trois intercepteurs sortent de l\'ombre de la balise !']]}],outro:[['dorn','Le signal remonte jusqu\'à Sable, le bras droit de Corbeau. Cette fois, on le tient.']]},
{t:'Le choix de Sable',rk:2,rw:{cr:2500,xp:380,rep:200},intro:[['dorn','Sable se cache dans un repaire en zone hostile. Détruis son escorte et ramène-le.'],['dorn','Vivant, de préférence. Il sait beaucoup de choses.']],
init:d=>{d.p=awayPt(9500)},steps:[{k:'kill',n:3,tys:['lourd','chasseur','chasseur'],txt:'Détruis l\'escorte de Sable'},{k:'choice',who:'sable',q:'Attends, pilote ! Je peux te donner les codes de la flotte de Corbeau… ou te rendre très riche. 4 000 crédits et tu ne m\'as jamais vu.',a:[{t:'L\'arrêter pour l\'Alliance',f:()=>{FM.fl.sable='arrest';addRep('alliance',300);toast('⛓ Sable est arrêté')}},{t:'Le laisser filer (4 000 ¢)',f:()=>{FM.fl.sable='bribe';G.cr+=4000;G.rep.alliance=Math.max(0,G.rep.alliance-200);toast('💰 +4 000 ¢ — Sable disparaît dans le vide');addBounty(800,'Dorn soupçonne quelque chose')}}]}],
outro:d=>FM.fl.sable=='arrest'?[['dorn','Sable sous les verrous, et ses codes entre nos mains. Corbeau va sentir passer la prochaine.']]:[['dorn','Sable s\'est volatilisé… Curieux. Bref. Les codes, on les trouvera autrement.']]},
{t:'Bouclier levé',rk:2,rw:{cr:5000,xp:700,rep:400,hull:'sentinelle'},intro:[['dorn','Nous connaissons enfin la position du Rapace, le croiseur amiral de Corbeau. On frappe maintenant.'],['dorn','Trois frégates t\'attendent au point de rendez-vous. Mène l\'assaut, pilote.']],
init:d=>{d.a=awayPt(5000);const a=P3(d.a),dir=a.clone().setY(0).normalize();d.p={x:a.x+dir.x*4000|0,y:a.y|0,z:a.z+dir.z*4000|0}},steps:[{k:'goto',at:'a',r:500,txt:'Rejoins les frégates de l\'Alliance'},{k:'kill',n:5,tys:['boss','lourd','lourd','chasseur','chasseur'],allies:3,txt:'Détruis la flotte du Rapace',say:[['corbeau','Dorn t\'envoie jouer les héros ? Le Rapace va te réduire en poussière !']]}],
outro:[['dorn','Le Rapace est en miettes. Au nom de l\'Alliance… merci.'],['dorn','La Sentinelle est à toi : le meilleur chasseur de la flotte, pour le meilleur pilote du secteur.']]}]},
guilde:{n:'La Veine d\'or',who:'brakka',ic:'tool',col:'#ffb050',where:st=>stFac(st)!='pirates'||true,M:[
{t:'Prospection',rk:1,rw:{cr:1000,xp:180,rep:150},intro:[['brakka','Alors c\'est toi, le pilote dont tout le monde parle ? La Guilde paie ceux qui ramènent du minerai.'],['brakka','Montre-moi ce que tu vaux : ramasse 15 unités de titane. Astéroïdes, filons, peu m\'importe.']],init:d=>{},steps:[{k:'collect',id:'titane',n:15,txt:'Ramasse du titane'}],outro:[['brakka','Pas mal, petit. Tu as de la poussière dans les veines.']]},
{t:'Commande spéciale',rk:1,rw:{cr:1500,xp:240,rep:180},intro:[['brakka','Une station High-tech a besoin de cristaux d\'énergie pour ses boucliers. Elle paie bien, et la Guilde touche sa part.'],['brakka','Livre-lui 10 cristaux. Ne traîne pas.']],init:d=>{d.st=stNear(s=>stEcon(s)=='High-tech',1500,24000)||stNear(null,2000,12000)||{n:'Base Alpha',x:0,y:0,z:0}},steps:[{k:'deliver',id:'cristal',n:10,txt:d=>'Livre 10 cristaux à '+d.st.n}],outro:[['brakka','Livré et payé. J\'aime travailler avec toi.']]},
{t:'Les saboteurs',rk:2,rw:{cr:2000,xp:320,rep:220},intro:[['brakka','Des pirates sabotent nos foreuses dans un champ d\'astéroïdes. Ils ont volé une carotte de forage expérimentale.'],['brakka','Chasse-les et récupère la carotte. Elle brille comme un phare, tu ne peux pas la rater.']],init:d=>{d.p=awayPt(6000)},steps:[{k:'kill',n:5,tys:['pirate','pirate','chasseur','pirate','chasseur'],txt:'Chasse les saboteurs'},{k:'item',txt:'Récupère la carotte de forage'}],outro:[['brakka','La carotte est intacte ! Les ingénieurs vont pleurer de joie.']]},
{t:'Le filon interdit',rk:2,rw:{cr:2500,xp:380,rep:200},intro:[['brakka','Mes prospecteurs ont repéré un astéroïde gorgé de minerai précieux. Un vrai trésor.'],['brakka','Fore-le avec un laser de minage et ramène tout. Les canons ne suffiront pas.']],init:d=>{d.p=richNear()||awayPt(4000)},steps:[{k:'rich',txt:'Fore l\'astéroïde riche'},{k:'choice',who:'corbeau',q:'Joli butin, pilote. Je paie 5 000 crédits pour les coordonnées de ce coin d\'astéroïdes. La Guilde n\'en saura rien.',a:[{t:'Garder le secret pour la Guilde',f:()=>{FM.fl.filon='guilde';addRep('guilde',300);toast('⛏ La Guilde te fait confiance')}},{t:'Vendre les coordonnées (5 000 ¢)',f:()=>{FM.fl.filon='vendu';G.cr+=5000;G.rep.guilde=Math.max(0,G.rep.guilde-200);toast('💰 +5 000 ¢ — les pirates connaissent le filon')}}]}],
outro:d=>FM.fl.filon=='guilde'?[['brakka','Tu as refusé l\'argent de Corbeau ? Petit, tu es des nôtres.']]:[['brakka','Les pirates rôdent autour de notre filon… Quelqu\'un a parlé. Si je trouve qui…']]},
{t:'Le cœur de l\'astéroïde',rk:2,rw:{cr:5000,xp:700,rep:400,hull:'mastodonte'},intro:[['brakka','On installe une plateforme de forage géante. Les pirates vont tout tenter pour la détruire.'],['brakka','Tiens bon deux minutes, le temps qu\'elle s\'ancre. Après ça, elle se défendra toute seule.']],init:d=>{d.p=awayPt(5500)},steps:[{k:'goto',at:'p',r:700,txt:'Rejoins la plateforme de forage'},{k:'defend',dur:120,txt:'Défends la plateforme'}],
outro:[['brakka','Elle tient ! Elle est ancrée !'],['brakka','Le Mastodonte est à toi, petit. Le seul et l\'unique. Ne le raye pas.']]}]},
carto:{n:'L\'Atlas perdu',who:'lio',ic:'map',col:'#9fe8b0',where:st=>true,M:[
{t:'Relevés',rk:1,rw:{cr:1000,xp:180,rep:150},intro:[['lio','Bonjour, pilote ! Les Cartographes cherchent des yeux neufs.'],['lio','Découvre deux planètes que personne n\'a encore répertoriées. Les sondes comptent aussi !']],init:d=>{d.d0=G.disc.size},steps:[{k:'disc',n:2,txt:'Découvre de nouvelles planètes'}],outro:[['lio','Deux mondes de plus sur la carte ! Magnifique.']]},
{t:'Les balises perdues',rk:1,rw:{cr:1500,xp:240,rep:180},intro:[['lio','Nos anciennes balises de relevé dérivent dans le vide. Chacune connaît la position de la suivante.'],['lio','Retrouve-les dans l\'ordre, il y en a trois.']],init:d=>{const a=awayPt(3000,2000),b=awayPt(5500,3500),c=awayPt(8000,4000);d.bc=[a,b,c];d.bi=0},steps:[{k:'beacons',txt:d=>'Retrouve les balises ('+(d.bi||0)+'/3)'}],outro:[['lio','Les trois balises ! Leurs relevés vont nous occuper des semaines.']]},
{t:'La chute',rk:2,rw:{cr:2200,xp:320,rep:220},intro:[['lio','Un trou noir déforme toutes nos cartes : le Gouffre d\'Érèbe.'],['lio','Approche-toi à moins de 900 mètres et tiens 10 secondes pour les mesures. Pas plus près, je t\'en supplie !']],init:d=>{const f=ANFIX[0];d.p={x:f.x,y:f.y,z:f.z}},steps:[{k:'scan',r:900,dur:10,bh:1,txt:'Mesures près du trou noir'}],outro:[['lio','Les mesures sont incroyables… La lumière fait trois fois le tour du gouffre !']]},
{t:'Les archives du Vigilant',rk:2,rw:{cr:2500,xp:380,rep:220},intro:[['lio','L\'épave géante du Vigilant contient les archives d\'une expédition disparue.'],['lio','Entre à l\'intérieur, rejoins la passerelle et récupère les archives. Attention aux drones de sécurité.']],init:d=>{const D=DERFIX;d.p={x:D.x,y:D.y,z:D.z};d.der=D.id},steps:[{k:'bridge',txt:'Atteins la passerelle du Vigilant'},{k:'choice',who:'brakka',q:'Ces archives montrent nos routes minières secrètes. La Guilde te les rachète 4 000 crédits… à condition qu\'elles ne soient jamais publiées.',a:[{t:'Les publier pour tous',f:()=>{FM.fl.arch='pub';addRep('carto',300);let n=0;const cx=cof(S.pos.x),cz=cof(S.pos.z);for(let i=-8;i<=8;i++)for(let l=-8;l<=8;l++){const s=cdata(cx+i,0,cz+l).st;if(s&&!G.vst.some(v=>v.n==s.n)){G.vst.push({n:s.n,x:s.x|0,y:s.y|0,z:s.z|0});n++}}toast('🗺 Archives publiées : '+n+' stations ajoutées à ta carte')}},{t:'Les vendre à la Guilde (4 000 ¢)',f:()=>{FM.fl.arch='guilde';G.cr+=4000;G.rep.carto=Math.max(0,G.rep.carto-200);addRep('guilde',150);toast('💰 +4 000 ¢')}}]}],
outro:d=>FM.fl.arch=='pub'?[['lio','Tout le monde pourra en profiter. C\'est ça, l\'esprit des Cartographes !']]:[['lio','Vendues… Bon. Je garderai au moins le souvenir de leur existence.']]},
{t:'Au-delà du voile',rk:2,rw:{cr:5000,xp:700,rep:400,part:'eng:voile'},intro:[['lio','Les archives parlent d\'un phare ancien, de l\'autre côté de la Porte de Janus.'],['lio','Traverse le trou de ver et trouve ce phare. Personne n\'y est allé depuis des siècles.']],init:d=>{const f=ANFIX[1];d.w={x:f.x,y:f.y,z:f.z};d.p={x:f.ex+1800|0,y:f.ey+300|0,z:f.ez+1200|0}},steps:[{k:'worm',txt:'Traverse la Porte de Janus'},{k:'goto',at:'p',r:380,phare:1,txt:'Trouve le phare ancien'}],
outro:[['lio','Incroyable… Le phare a des milliers d\'années, et ses moteurs fonctionnent encore !'],['lio','Nos ingénieurs ont copié ses plans : voici le Voile stellaire. Il est à toi.']]}]}};
// ----- déroulement -----
const fmCur=()=>FM.cur&&FMC[FM.cur.f]?FM.cur:null;
const fmMis=()=>{const c=fmCur();return c&&FMC[c.f].M[c.i]};
const fmStep=()=>{const m=fmMis();return m&&m.steps[FM.cur.s]};
function fmTxt(){const s=fmStep();if(!s)return'';if(!s.txt)return s.k=='choice'?'Prends ta décision':'';return typeof s.txt=='function'?s.txt(FM.cur.d):s.txt}
function fmClear(){for(const o of FMS.ents){if(o.isFR)frRemove(o);else if(o.parent)o.parent.remove(o)}FMS.ents=[];for(const e of en)if(e.fm){e.dead=1;e.mesh.parent&&e.mesh.parent.remove(e.mesh)}FMS.foes=[]}
function fmStart(f){const C=FMC[f],i=FM[f];if(fmCur()){toast('Termine d\'abord ta mission en cours');return}if(i>=5){toast('Chaîne terminée');return}const M=C.M[i];if(rankOf(f)<M.rk){toast('🔒 '+FAC[f].n+' : rang « '+RANKN[M.rk]+' » requis');return}
FM.cur={f,i,s:0,d:{}};try{M.init(FM.cur.d)}catch(e){console.warn(e)}fmStepBegin();save();say(M.intro,()=>{banner(C.ic,C.n+' · '+M.t,fmTxt(),C.col)})}
function fmAbandon(){if(!fmCur())return;fmClear();FM.cur=null;toast('Mission de faction abandonnée');save()}
function fmStepBegin(){const s=fmStep(),d=FM.cur.d;if(!s)return;d.k0=0;d.got=0;d.tt=0;d.sp=0;if(s.k=='disc')d.d0=G.disc.size;if(s.say)say(s.say);if(s.k=='choice')setTimeout(()=>fmChoice(s),400)}
function fmNext(){const c=fmCur();fmClear();c.s++;const M=fmMis();if(c.s>=M.steps.length){fmDone();return}fmStepBegin();SFX.disc();const t2=fmTxt();if(t2)toast('🎯 '+t2);save()}
function fmDone(){const c=fmCur(),C=FMC[c.f],M=C.M[c.i],rw=M.rw;FM.cur=null;FM[c.f]=c.i+1;STS.fm++;G.cr+=rw.cr;gainXP(rw.xp);addRep(c.f,rw.rep);if(c.f=='alliance')warAdd(10);
const out=typeof M.outro=='function'?M.outro():M.outro;say(out,()=>{let extra='';if(rw.hull&&!G.owned.includes(rw.hull)){G.owned.push(rw.hull);extra=' · vaisseau unique : '+HULLS[rw.hull].n+' (onglet Vaisseaux)'}if(rw.part&&!G.pown.includes(rw.part)){G.pown.push(rw.part);const[s,id]=rw.part.split(':');extra=' · pièce unique : '+PARTS[s].o[id].n+' (Atelier)'}
banner(C.ic,'Mission accomplie : '+M.t,'+'+fmt(rw.cr)+' ¢'+extra,C.col);SFX.win();if(FM[c.f]>=5)setTimeout(()=>banner('trophy',C.n+' : chaîne terminée !','Merci, pilote. '+FAC[c.f].n+' se souviendra de toi.',C.col),4800);save()})}
// choix : panneau à deux boutons
function fmChoice(s){if(DLG.open){setTimeout(()=>fmChoice(s),500);return}const el=$('chc'),C=CHAR[s.who];el.innerHTML=`<div id="chcI">${C.ic}</div><div><div id="chcN" style="color:${C.c}">${C.n}</div><div id="chcT">${esc(s.q)}</div><div class="obtns">${s.a.map((a,i)=>`<button data-ch="${i}">${esc(a.t)}</button>`).join('')}</div></div>`;el.style.display='flex';cxAdd('ch',s.who);SFX.tick();
el.querySelectorAll('[data-ch]').forEach(b=>b.onclick=e=>{e.stopPropagation();el.style.display='none';try{s.a[+b.dataset.ch].f()}catch(err){console.warn(err)}SFX.buy();fmNext()})}
function fmEvent(ev,arg){const s=fmStep();if(!s)return;if(ev=='worm'&&s.k=='worm')setTimeout(fmNext,1200);if(ev=='rich'&&s.k=='rich')fmNext();if(ev=='bridge'&&s.k=='bridge'&&(!FM.cur.d.der||FM.cur.d.der==arg))fmNext()}
// ----- objets de mission -----
function fmBeacon(p,col){const g=new THREE.Group();g.add(new THREE.Mesh(new THREE.OctahedronGeometry(10,0),new THREE.MeshStandardMaterial({color:0x2a3040,metalness:.8,roughness:.3,emissive:col,emissiveIntensity:.4})));for(let i=0;i<2;i++){const r=new THREE.Mesh(new THREE.TorusGeometry(20+i*8,.8,6,40),new THREE.MeshBasicMaterial({color:col,transparent:true,opacity:.7,blending:ADDB,depthWrite:false}));r.rotation.x=Math.PI/2+i*.6;g.add(r)}g.add(sprite(col,90,.6));g.position.copy(p);scene.add(g);FMS.ents.push(g);return g}
function fmPhare(p){const g=new THREE.Group(),M=new THREE.MeshStandardMaterial({color:0x1a1820,metalness:.85,roughness:.25,emissive:0x2a1a40,emissiveIntensity:.5}),GL=new THREE.MeshBasicMaterial({color:0x9ff0ff});g.add(new THREE.Mesh(new THREE.CylinderGeometry(6,22,260,6),M));const top=new THREE.Mesh(new THREE.OctahedronGeometry(18,0),GL);top.position.y=150;g.add(top);top.add(sprite(0x9ff0ff,260,.7));
for(let i=0;i<3;i++){const r=new THREE.Mesh(new THREE.TorusGeometry(50+i*22,2,8,64),new THREE.MeshBasicMaterial({color:0x9ff0ff,transparent:true,opacity:.55,blending:ADDB,depthWrite:false}));r.position.y=40+i*40;r.rotation.x=Math.PI/2;r.userData.sp=(i%2?-1:1)*(.3+i*.2);g.add(r)}g.position.copy(p);scene.add(g);FMS.ents.push(g);g.userData.phare=1;return g}
function fmPlatform(p){const g=new THREE.Group(),M=new THREE.MeshStandardMaterial({color:0xc8a040,map:HULLT,metalness:.6,roughness:.4}),D=new THREE.MeshStandardMaterial({color:0x2a2e34,metalness:.6,roughness:.5});const add=(geo,m,x,y,z)=>{const o=new THREE.Mesh(geo,m);o.position.set(x,y,z);g.add(o);return o};
add(new THREE.CylinderGeometry(40,46,14,8),M,0,0,0);add(new THREE.CylinderGeometry(10,10,70,10),D,0,30,0);add(new THREE.ConeGeometry(14,40,10),M,0,-30,0).rotation.x=Math.PI;for(let i=0;i<4;i++){const a=i/4*TAU;add(new THREE.BoxGeometry(12,8,30),D,Math.cos(a)*48,0,Math.sin(a)*48).rotation.y=-a;const l=sprite(0xff8030,14);l.position.set(Math.cos(a)*58,6,Math.sin(a)*58);g.add(l)}
const F=frSpawn({kind:'platform',mesh:g,p,hp:950,mhp:950,r:62,name:'Plateforme de forage'});F.isFR=1;FMS.ents.push(F);return F}
function fmSpawnFoes(p,tys,tgF){const z=Math.max(1,danger());for(const ty of tys){const e=mkEnemy(ty,p.clone().add(new V3(rv(400),rv(120),rv(400))),z);e.fm=1;if(tgF)e.tgF=tgF;e.onKill=()=>{e.kfm=1};en.push(e);FMS.foes.push(e)}}
const fmLeft=()=>FMS.foes.filter(e=>!e.kfm).length;
// ----- boucle des missions -----
function fmTick(dt){const c=fmCur();if(!c||mode!='space'||S.dead)return;const s=fmStep(),d=c.d;if(!s)return;const tgPos=fmTarget();d.tt+=dt;
if(s.k=='goto'){const p=P3(d[s.at]);if(s.phare&&!FMS.ents.some(o=>o.userData&&o.userData.phare)&&S.pos.distanceTo(p)<9000)fmPhare(p);for(const o of FMS.ents)if(o.userData&&o.userData.phare)o.children.forEach(r=>{if(r.userData.sp)r.rotation.z+=r.userData.sp*dt});if(S.pos.distanceTo(p)<s.r)fmNext()}
else if(s.k=='kill'){const p=P3(d.p),dist=S.pos.distanceTo(p);if(!d.sp&&dist<1800){d.sp=1;fmSpawnFoes(p,s.tys);if(s.allies){for(let i=0;i<s.allies;i++){const F=frSpawn({kind:'ally',name:FRIGN[i%FRIGN.length],p:S.pos.clone().add(new V3(rv(200),rv(60),rv(200))),hp:120,mhp:120,dmg:2,rate:.7,rng:2400,sp:240,anchor:p,col:0xe8eef8,acc:0x2a6aff,bc:0x9fd0ff});F.isFR=1;FMS.ents.push(F)}}toast('⚠ Contact !');SFX.alarm()}
if(d.sp){const miss=FMS.foes.filter(e=>!e.kfm&&!en.includes(e));if(miss.length&&dist<1800){FMS.foes=FMS.foes.filter(e=>!miss.includes(e));fmSpawnFoes(p,miss.map(e=>e.ty))}if(!fmLeft())fmNext()}}
else if(s.k=='scan'){const p=P3(d.p),dist=S.pos.distanceTo(p);if(!s.bh&&!FMS.ents.length)fmBeacon(p,0xff5050);if(dist<s.r){d.got+=dt;if(Math.random()<dt*3)tone(800+d.got*120,900+d.got*120,.06,'sine',.03);if(d.got>=s.dur)fmNext()}else d.got=Math.max(0,d.got-dt*.5)}
else if(s.k=='escort'){let F=FMS.ents.find(o=>o.isFR&&o.kind=='freighter');if(!F&&!d.fail){F=frSpawn({kind:'freighter',name:'Cargo Hestia',p:P3(d.a),hp:420,mhp:420,r:28,sp:58,dest:null});F.isFR=1;F.mesh.lookAt(P3(d.st));FMS.ents.push(F);d.wv=8;F.onArrive=()=>{toast('📦 Le cargo Hestia est arrivé !');fmNext()};F.onDie=()=>{d.fail=1;toast('💥 Le cargo est détruit ! Retourne au point de rendez-vous pour réessayer');SFX.alarm()}}
if(d.fail){if(S.pos.distanceTo(P3(d.a))<500){d.fail=0;fmClear()}return}if(F&&!F.dest&&S.pos.distanceTo(F.pos)<1500){F.dest=P3(d.st);toast('📦 Le cargo Hestia se met en route')}if(F&&F.dest){d.wv-=dt;if(d.wv<=0){d.wv=40;d.wn=(d.wn||0)+1;const n=d.wn>=3?3:2;fmSpawnFoes(F.pos.clone().add(new V3(rv(600),rv(100),rv(600))),Array.from({length:n},(_,i)=>i==2?'chasseur':'pirate'),F)}if(F.pos.distanceTo(P3(d.st))<380&&!F.arr){F.arr=1;F.onArrive(F)}}}
else if(s.k=='collect'){if(d.got>=s.n)fmNext()}
else if(s.k=='deliver'){if(S.docked&&S.docked.n==d.st.n){if((G.cargo[s.id]||0)>=s.n){G.cargo[s.id]-=s.n;if(!G.cargo[s.id])delete G.cargo[s.id];fmNext()}else if(t-(d.wT||-99)>15){d.wT=t;toast('Il te faut '+s.n+' '+matG(s.id).n+' en soute')}}}
else if(s.k=='disc'){if(G.disc.size-d.d0>=s.n)fmNext()}
else if(s.k=='beacons'){const i=d.bi||0,p=P3(d.bc[i]);if(!FMS.ents.length)fmBeacon(p,0x9fe8b0);if(S.pos.distanceTo(p)<260){d.bi=i+1;fmClear();SFX.disc();if(d.bi>=3)fmNext();else toast('📡 Balise '+d.bi+'/3 trouvée — elle indique la suivante')}}
else if(s.k=='item'){const p=P3(d.p);if(!FMS.ents.length){const g=new THREE.Group(),m=new THREE.Mesh(new THREE.CylinderGeometry(2,2,12,10),new THREE.MeshStandardMaterial({color:0xffd060,emissive:0xff9a20,emissiveIntensity:1.2}));m.rotation.z=1;g.add(m);g.add(sprite(0xffb040,60,.8));g.position.copy(p);scene.add(g);FMS.ents.push(g)}const g=FMS.ents[0];if(g.rotation)g.rotation.y+=dt;if(S.pos.distanceTo(p)<40){SFX.win();fmNext()}}
else if(s.k=='defend'){let F=FMS.ents.find(o=>o.isFR&&o.kind=='platform');if(!F&&!d.fail){F=fmPlatform(P3(d.p));F.onDie=()=>{d.fail=1;toast('💥 La plateforme est détruite ! Reviens sur place pour réessayer');SFX.alarm()};d.got=0;d.wv=4}
if(d.fail){if(S.pos.distanceTo(P3(d.p))<900&&!en.some(e=>e.fm)){d.fail=0;fmClear()}return}const nearP=S.pos.distanceTo(F.pos)<3000;if(nearP)d.got+=dt;if(nearP)d.wv-=dt;if(d.wv<=0){d.wv=24;const tough=FM.fl.filon=='vendu';fmSpawnFoes(F.pos.clone().add(new V3(rv(900),rv(200),rv(900))),tough?['pirate','chasseur','lourd','chasseur']:['pirate','chasseur','pirate'],F)}if(d.got>=s.dur){toast('⛏ La plateforme est ancrée !');for(const e of en)if(e.fm)killQuiet(e);fmNext()}}}
function fmTarget(){const c=fmCur(),s=fmStep();if(!c||!s)return null;const d=c.d;if(s.k=='goto')return P3(d[s.at]);if(s.k=='kill'||s.k=='scan'||s.k=='item'||s.k=='rich'||s.k=='defend')return d.p?P3(d.p):null;if(s.k=='escort'){const F=FMS.ents.find(o=>o.isFR&&o.kind=='freighter');return d.fail?P3(d.a):F?F.pos:P3(d.a)}if(s.k=='deliver')return P3(d.st);if(s.k=='beacons')return d.bc&&d.bc[d.bi||0]?P3(d.bc[d.bi||0]):null;if(s.k=='bridge')return d.p?P3(d.p):null;if(s.k=='worm')return P3(d.w);return null}
STICK.push(fmTick);
{const _mt=minToast;minToast=function(){const s=fmStep();if(s&&s.k=='collect'&&MINQ[s.id])FM.cur.d.got=(FM.cur.d.got||0)+MINQ[s.id];_mt()}}
{const _wj=wormJump;wormJump=function(o){_wj(o);fmEvent('worm')}}
{const _rh=richHit;richHit=function(R,d,p){const was=R.gone;_rh(R,d,p);if(!was&&R.gone)fmEvent('rich')}}
// ----- HUD -----
{const _ci=contentInfo;contentInfo=function(){let s=_ci();const c=fmCur();if(c){const C=FMC[c.f],st=fmStep(),d=c.d;let pr='';if(st){if(st.k=='kill'&&d.sp){const n=fmLeft();pr=` (${n} restant${n>1?'s':''})`}else if(st.k=='scan')pr=` (${Math.min(100,Math.round(d.got/st.dur*100))} %)`;else if(st.k=='collect')pr=` (${Math.min(st.n,d.got|0)}/${st.n})`;else if(st.k=='disc')pr=` (${G.disc.size-d.d0}/${st.n})`;else if(st.k=='defend')pr=` (${Math.max(0,Math.ceil(st.dur-d.got))} s)`;else if(st.k=='escort'){const F=FMS.ents.find(o=>o.isFR&&o.kind=='freighter');if(F)pr=` (coque ${Math.round(F.hp/F.mhp*100)} %)`}}
s+=(s?'<br>':'')+`<span style="color:${C.col}">${ICO(C.ic)} ${C.n} ${c.i+1}/5 · ${fmTxt()}${pr}</span>`}return s}}
{const _ov=overlay;overlay=function(){_ov();if(mode!='space'||S.dead||!fmCur())return;const p=fmTarget();if(p&&S.pos.distanceTo(p)>150)edgeMarker(p,FMC[FM.cur.f].col,fmTxt().slice(0,34),'◆')}}
{const _mr=mpRadar;mpRadar=function(blip){_mr(blip);if(mode!='space'||!fmCur())return;const p=fmTarget();if(p)blip(p,FMC[FM.cur.f].col,3.4,true,true)}}
{const _mi=mapItems;mapItems=function(){const it=_mi();const p=fmTarget();if(p&&fmCur())it.push({k:'mis',n:FMC[FM.cur.f].n+' : '+fmTxt(),x:p.x,y:p.y,z:p.z,c:FMC[FM.cur.f].col});return it}}
// ----- station : contacts de faction -----
SVC.act.fmgo=f=>fmStart(f);SVC.act.fmab=()=>fmAbandon();
svcAdd({o:5,ic:'flag',t:'Contacts de faction',show:st=>!st.ground&&!st.base,html:st=>{let h='';const c=fmCur();for(const f in FMC){const C=FMC[f],i=FM[f],ch=CHAR[C.who];if(f=='alliance'&&stFac(st)=='pirates'){h+=SROW(`<div><b style="color:${C.col}">${ICO(C.ic)} ${C.n}</b><small>Aucun officier de l'Alliance n'ose se montrer dans un repaire pirate.</small></div>`,'');continue}
if(i>=5){h+=SROW(`<div><b style="color:${C.col}">${ICO(C.ic)} ${C.n}</b> <i class="tag">5/5</i><small>${ch.n} : « Merci encore, pilote. »</small></div>`,'');continue}const M=C.M[i],lk=rankOf(f)<M.rk;
if(c&&c.f==f){h+=SROW(`<div><b style="color:${C.col}">${ICO(C.ic)} ${C.n}</b> <i class="tag">${i+1}/5</i><small>En cours : <b>${M.t}</b><br>${esc(fmTxt())}</small></div>`,`<button class="red" data-sv="fmab">Abandonner</button>`);continue}
h+=SROW(`<div><b style="color:${C.col}">${ICO(C.ic)} ${C.n}</b> <i class="tag pvt">${i}/5</i><small>${ch.ic} ${ch.n}<br>Mission ${i+1} : <b>${M.t}</b> · ${fmt(M.rw.cr)} ¢${M.rw.hull?' + vaisseau unique':M.rw.part?' + pièce unique':''}${lk?'<br>Rang « '+RANKN[M.rk]+' » requis ('+FAC[f].n+')':''}</small></div>`,lk?`<button class="dim" data-sv="fmgo:${f}">🔒</button>`:c?'':`<button class="hot" data-sv="fmgo:${f}">Parler</button>`)}return h}});
// reprise après un rechargement
if(FM.cur&&FM.cur.d){FM.cur.d.sp=0;FM.cur.d.fail=0;const st0=fmStep();if(st0&&st0.k=='choice')setTimeout(()=>fmChoice(st0),3500)}
