// ===== NOUVEAUX ENNEMIS : essaims de drones, chasseurs furtifs, bombardiers (visent les stations), porte-chasseurs, Xil (vaisseaux vivants) =====
Object.assign(CXT.en,{swarm:['Essaim de drones','Une nuée de petits drones pirates. Fragiles un par un, dangereux tous ensemble.'],stealth:['Chasseur furtif','Invisible au radar tant qu\'il ne tire pas. Approche-toi à moins de 400 m pour le faire apparaître.'],bomber:['Bombardier','Lent et blindé, il fonce sur les stations. Abats-le avant qu\'il largue ses bombes.'],carrier:['Porte-chasseurs','Il lâche des vagues de chasseurs. Détruis ses armes, à l\'avant, pour stopper les lancements.'],xil:['Xil','Vaisseaux vivants venus des confins de la galaxie. Ils transportent parfois de la matière exotique.']});
CXT.fac.xil=['Essaim Xil','Une espèce inconnue qui sort des zones mortelles et des anomalies. Personne ne sait ce qu\'elle veut.'];
const FOES={t:80,bt:150};const FMATS={};
const fMat=(c,e,ei,o)=>{const k=[c,e,ei,o].join('|');return FMATS[k]||(FMATS[k]=new THREE.MeshStandardMaterial(Object.assign({color:c,map:HULLT,metalness:DESK?.6:.3,roughness:.4,emissive:e||0,emissiveIntensity:ei||0},o||{})))};
function fGroup(col){const g=new THREE.Group(),b=new THREE.Group();g.add(b);const bar=new THREE.Sprite(new THREE.SpriteMaterial({color:col,depthWrite:false,transparent:true}));bar.scale.set(10,.7,1);bar.position.y=9;bar.visible=false;g.add(bar);g.userData={body:b,bar};return g}
const fAdd=(b,geo,m,x,y,z,rx=0,ry=0,rz=0)=>{const o=new THREE.Mesh(geo,m);o.position.set(x,y,z);o.rotation.set(rx,ry,rz);b.add(o);return o};
function engGlow(b,x,y,z,c,s){const n=sprite(c,s);n.position.set(x,y,z);b.add(n)}
function mSwarm(){const g=fGroup(0xff6a3a),b=g.userData.body,M=fMat(0x3a3f46,0xff3a1a,.25),E=new THREE.MeshBasicMaterial({color:0xff4020});fAdd(b,new THREE.OctahedronGeometry(1.1,0),M,0,0,0).scale.set(1,.6,1.6);for(let i=0;i<3;i++){const a=i/3*TAU;fAdd(b,new THREE.BoxGeometry(2.6,.12,.9),M,Math.cos(a)*1.4,Math.sin(a)*1.4,.6,0,0,a)}fAdd(b,new THREE.SphereGeometry(.35,8,6),E,0,.2,-1.2);engGlow(b,0,0,1.6,0xff6030,3.5);return g}
function mStealth(){const g=fGroup(0xb070ff),b=g.userData.body,M=new THREE.MeshStandardMaterial({color:0x15161c,metalness:.9,roughness:.25,emissive:0x2a1050,emissiveIntensity:.4,transparent:true,opacity:1}),L=new THREE.MeshBasicMaterial({color:0xb070ff,transparent:true,opacity:1});
fAdd(b,lathe([[0,-6],[1.6,-1],[1.4,3],[0,3.4]],4),M,0,0,0).scale.set(1.6,.35,1);for(const s of[-1,1]){fAdd(b,new THREE.BoxGeometry(4.5,.1,3),M,s*2.6,0,1.4,0,s*-.5,0);fAdd(b,new THREE.BoxGeometry(4.6,.06,.12),L,s*2.6,.08,.1,0,s*-.5,0)}engGlow(b,0,0,3.6,0x9a50ff,4);g.userData.cloakM=[M,L];return g}
function mBomber(){const g=fGroup(0xff5040),b=g.userData.body,M=fMat(0x5a4a40,0x401008,.2),D=EDARK,E=new THREE.MeshBasicMaterial({color:0xff5030});fAdd(b,new THREE.BoxGeometry(5,2.2,9),M,0,0,0);for(const s of[-1,1]){fAdd(b,new THREE.BoxGeometry(9,.6,5),M,s*6.5,0,1.5,0,s*-.25,0);fAdd(b,new THREE.CylinderGeometry(.9,1.1,4,10).rotateX(Math.PI/2),D,s*4,-.6,3.8);engGlow(b,s*4,-.6,6,0xff7030,6)}
for(let i=0;i<4;i++)fAdd(b,new THREE.BoxGeometry(.6,.2,.6),E,-1.2+i*.8,-1.15,-1+i*.6);fAdd(b,new THREE.SphereGeometry(1,10,8),new THREE.MeshBasicMaterial({color:0xffb070}),0,.9,-3.6).scale.set(1,.6,1.2);return g}
function mCarrier(){const g=fGroup(0xff5040),b=g.userData.body,M=fMat(0x4a4e58,0x200808,.2),D=EDARK,W=new THREE.MeshBasicMaterial({color:0xffc070});fAdd(b,new THREE.BoxGeometry(9,5,34),M,0,0,0);fAdd(b,new THREE.BoxGeometry(4,6,8),M,0,5,6);fAdd(b,new THREE.BoxGeometry(5,1.2,2),W,0,5.5,1.9);
fAdd(b,new THREE.BoxGeometry(7,3,1),new THREE.MeshBasicMaterial({color:0xff9a40}),0,-.5,-17.1);for(const s of[-1,1]){fAdd(b,new THREE.BoxGeometry(3,3.6,24),D,s*6,-.6,2);for(let k=0;k<6;k++){const l=sprite(k%2?0xff3030:0xffb060,2.5);l.position.set(s*4.7,2.6,-14+k*5);b.add(l)}engGlow(b,s*3,0,18,0xff6030,10)}engGlow(b,0,0,18,0xff6030,12);return g}
function mXil(big){const g=fGroup(0x6dff8a),b=g.userData.body,M=new THREE.MeshStandardMaterial({color:0x1e3a2a,roughness:.5,metalness:.1,emissive:0x2aff7a,emissiveIntensity:.35,flatShading:true}),G=new THREE.MeshBasicMaterial({color:0x9dffb0});
fAdd(b,new THREE.IcosahedronGeometry(2.2,1),M,0,0,0).scale.set(1,.8,1.5);for(let i=0;i<5;i++){const a=i/5*TAU;fAdd(b,new THREE.SphereGeometry(.7,8,6),M,Math.cos(a)*1.9,Math.sin(a)*1.4,-.8)}for(let i=0;i<6;i++){const a=i/6*TAU;const tnt=fAdd(b,new THREE.ConeGeometry(.35,5,6),M,Math.cos(a)*1.2,Math.sin(a)*1,3.6,Math.PI/2+rv(.3),0,0);tnt.userData.ph=i}
fAdd(b,new THREE.SphereGeometry(.8,10,8),G,0,.4,-2.6);b.add(sprite(0x6dff8a,big?16:9,.6));g.userData.xil=1;return g}
function reMesh(e,g,sc){const old=e.mesh;g.position.copy(e.pos);g.scale.setScalar(sc);old.parent&&old.parent.remove(old);curScene().add(g);e.mesh=g;e.pos=g.position}
// ----- création -----
function mkFoe(kind,p,z,o){let e;if(kind=='swarm'){e=mkEnemy('chasseur',p,z);e.hp*=.35;e.dmg*=.55;e.sz=6;e.r=6;e.rw=12;reMesh(e,mSwarm(),1.5)}
else if(kind=='stealth'){e=mkEnemy('chasseur',p,z);e.hp*=1.7;e.dmg*=1.35;e.rw=70;e.bc=0xc070ff;reMesh(e,mStealth(),1.8);e.lastShot=-99;e.pcd=1e9}
else if(kind=='bomber'){e=mkEnemy('lourd',p,z);e.hp*=1.6;e.rw=160;e.big=1;e.persist=1;e.bomb=1;e.bsp=62;reMesh(e,mBomber(),2.2);e.mc=1e9}
else if(kind=='carrier'){e=mkEnemy('lourd',p,z);e.hp*=4.5;e.sp*=.5;e.rw=320;e.big=1;e.persist=1;e.carrier=1;e.launchT=6;e.kids=0;e.sz=40;e.r=40;reMesh(e,mCarrier(),2.6);e.mc=1e9}
else if(kind=='xil'){const big=o&&o.big;e=mkEnemy(big?'lourd':'chasseur',p,z);e.hp*=big?1.4:1.2;e.rw=big?150:55;e.bc=0x6dff8a;e.xil=1;if(big){e.big=1;e.mc=1e9}reMesh(e,mXil(big),big?3:1.8)}
e.mhp=e.hp;e.kind=kind;subInit(e);if(kind!='xil')e.pir=1;e.hitAt=0;en.push(e);return e}
function foeGroup(kind,z){fwd();const a=Math.random()*TAU,base=S.pos.clone().add(new V3(Math.cos(a)*1200,rv(250),Math.sin(a)*1200));
if(kind=='swarm'){const L=mkFoe('swarm',base,z);for(let i=0;i<6;i++){const e=mkFoe('swarm',base.clone().add(new V3(rv(60),rv(30),rv(60))),z);e.lead=L;e.side=Math.random()<.5?1:-1}toast('⚠ Essaim de drones en approche !')}
else if(kind=='stealth'){for(let i=0;i<2;i++)mkFoe('stealth',base.clone().add(new V3(i*60,0,i*40)),z);toast('📡 Signal brouillé… des chasseurs furtifs rôdent');SFX.alarm()}
else if(kind=='carrier'){mkFoe('carrier',base.clone().multiplyScalar(1).add(new V3(0,0,0)),z);banner('skull','Porte-chasseurs pirate !','Détruis ses armes (à l\'avant) pour stopper les lancements','#ff6a6a');SFX.alarm()}
else if(kind=='xil'){const n=2+(Math.random()*2|0);for(let i=0;i<n;i++)mkFoe('xil',base.clone().add(new V3(rv(120),rv(60),rv(120))),z,{big:i==0&&z>=3});banner('vortex','Contact inconnu : les Xil !','Des vaisseaux vivants sortent du vide','#6dff8a');SFX.alarm();cxAdd('fac','xil')}}
function bomberRaid(st){const z=Math.max(1,danger()),c=new V3(st.x,st.y,st.z),dir=c.clone().sub(S.pos).setY(0);if(dir.lengthSq()<1)dir.set(1,0,0);dir.normalize();for(let i=0;i<2;i++){const p=c.clone().addScaledVector(dir,2600).add(new V3(rv(300),rv(150)+150,rv(300)));const e=mkFoe('bomber',p,z);e.tgSt={n:st.n,x:st.x,y:st.y,z:st.z};e.weave=Math.random()*9}
banner('skull','Bombardiers en approche de '+st.n+' !','Intercepte-les avant qu\'ils atteignent la station','#ff6a6a');SFX.alarm()}
// ----- comportements spéciaux (après l'IA normale) -----
{const _ue=updEnemies;updEnemies=function(dt,z){const keep=en.filter(e=>e.persist||e.bomb),pre=new Map();for(const e of en)if(e.bomb)pre.set(e,e.pos.clone());_ue(dt,z);
for(const e of keep){if(e.dead&&e.hp>0&&!e.gone&&e.pos.distanceTo(S.pos)<9000){e.dead=0;if(!e.mesh.parent)curScene().add(e.mesh);en.push(e)}}
for(const e of en){if(e.bomb&&pre.has(e)&&!e.dead){e.pos.copy(pre.get(e));const tg=_c2.set(e.tgSt.x,e.tgSt.y,e.tgSt.z),to=tg.clone().sub(e.pos),d=to.length();to.normalize();e.weave+=dt;const side=_c3.crossVectors(to,AY).normalize();e.dir.copy(to).addScaledVector(side,Math.sin(e.weave*.8)*.25).normalize();e.vel.copy(e.dir).multiplyScalar(e.engOff?e.bsp*.5:e.bsp);e.pos.addScaledVector(e.vel,dt);e.mesh.lookAt(_c3.copy(e.pos).sub(e.dir));
if(d<320&&!e.dropped){e.dropped=1;bombStation(e)}}
if(e.carrier&&!e.dead&&!e.gunOff){e.launchT-=dt;if(e.launchT<=0&&e.pos.distanceTo(S.pos)<2500){e.launchT=16;const n=en.filter(x=>x.fromCar===e).length;if(n<6)for(let i=0;i<2;i++){const c=mkEnemy('chasseur',e.mesh.localToWorld(new V3(rv(2),-.5,-18)),Math.max(1,danger()));c.fromCar=e;c.vel.copy(e.dir).multiplyScalar(200);en.push(c)}if(n<6){boom3(e.mesh.localToWorld(new V3(0,0,-18)),10,0xffa040,40);toast('⚠ Le porte-chasseurs lance des chasseurs !')}}}
if(e.kind=='stealth'&&!e.dead){if(e.cd>(e.pcd||0)+.2)e.lastShot=t;e.pcd=e.cd;const vis=e.pos.distanceTo(S.pos)<400||t-e.lastShot<2.5||t-(e.hitT||-9)<1.5,k=vis?1:.07+.05*Math.sin(t*9+e.sz);if(e.cloaked&&vis){fxGlow(e.pos.clone(),0xb070ff,40,.3,2);tone(500,1400,.2,'sine',.04)}e.cloaked=!vis;for(const m of e.mesh.userData.cloakM||[])m.opacity=lerp(m.opacity,k,damp(6,dt))}
if(e.xil&&!e.dead){const s=1+Math.sin(t*3+e.sz)*.05;e.mesh.userData.body.scale.set(s,1/s,s);e.mesh.userData.body.children.forEach(c=>{if(c.userData.ph!=null)c.rotation.x=Math.PI/2+Math.sin(t*4+c.userData.ph)*.35})}}}}
function bombStation(e){const st=e.tgSt,c=new V3(st.x,st.y,st.z);for(let i=0;i<6;i++)setTimeout(()=>{boom3(c.clone().add(new V3(rv(80),rv(60),rv(80))),50,0xff8040,140,true);SFX.boom();shake=Math.min(1,shake+.2)},i*220);
toast('💥 '+st.n+' a été bombardée ! Les prix y flambent');if(typeof stationHit=='function')stationHit(st);if(typeof warAdd=='function')warAdd(-6,c);setTimeout(()=>{if(!e.dead){e.gone=1;e.dead=1;e.mesh.parent&&e.mesh.parent.remove(e.mesh)}},1500)}
// la cible camouflée n'est ni verrouillable, ni visible au radar
{const _st=spaceTargets;spaceTargets=function(){return _st().filter(T=>!T.cloaked)}}
{const _rd=radar;radar=function(){const keep=en;if(en.some(e=>e.cloaked))en=en.filter(e=>!e.cloaked);try{_rd()}finally{en=keep}}}
{const _ov=overlay;overlay=function(){const keep=en;if(en.some(e=>e.cloaked))en=en.filter(e=>!e.cloaked);try{_ov()}finally{en=keep}if(mode!='space'||S.dead)return;for(const e of en)if(e.bomb&&!e.dead&&e.pos.distanceTo(S.pos)>1400)edgeMarker(e.pos,'#ff5050','Bombardier → '+e.tgSt.n,'💣')}}
// butin des Xil
{const _he=hitEnemy;hitEnemy=function(e,d,p){const was=e.dead;e.hitT=t;_he(e,d,p);if(!was&&e.dead){if(e.xil&&Math.random()<(e.big?.8:.3)&&cargoUsed()<cap()){G.cargo.exo=(G.cargo.exo||0)+1;setTimeout(()=>toast('🌀 Le Xil laisse de la matière exotique (+1)'),400)}if(e.bomb)toast('💣 Bombardier abattu ! +'+fmt(e.rw)+' ¢');if(e.carrier){banner('trophy','Porte-chasseurs détruit !','+'+fmt(Math.round(e.rw*1.5))+' ¢','#ffc34d');setTimeout(giveBlueprint,1500)}}}}
// ----- apparitions -----
function foesTick(dt){if(S.docked||S.dead||BOSS||(typeof RC!='undefined'&&RC.on)||DLG.open)return;const z=danger();
FOES.t-=dt;if(FOES.t<=0){FOES.t=80+Math.random()*70;if(en.length<5){let nearAn=false;for(const o of AN.act.values())if(o.mesh.position.distanceTo(S.pos)<5000)nearAn=true;const r=Math.random();
if((z>=3&&r<.3)||(nearAn&&z>=1&&r<.25))foeGroup('xil',Math.max(1,z));else if(z>=2&&r<.45)foeGroup(r<.3?'stealth':'carrier',z);else if(z>=1&&r<.7)foeGroup('swarm',z)}}
FOES.bt-=dt;if(FOES.bt<=0){FOES.bt=160+Math.random()*120;if(en.some(e=>e.bomb))return;for(const st of stations){const c=typeof ctlOf=='function'?ctlOf(secOf(st.x,st.z)):'front';if(c=='alliance'&&st.n!='Base Alpha'&&Math.random()<.5)continue;if(st.n=='Base Alpha')continue;if(S.pos.distanceTo(_v.set(st.x,st.y,st.z))<4000&&Math.random()<.45){bomberRaid(st);break}}}}
STICK.push(foesTick);
