// ===== EFFETS DE PILOTAGE (aberration chromatique quand on est touché, traits de vitesse au boost sur mobile) + AMBIANCE DES ÉPAVES (gyrophares, écrans qui grésillent, câbles arrachés, poussière dans la lampe, craquements) =====
const HFX={v:0};
{const _dm=damage;damage=function(n,kind){const a=S.hp,b=S.sh||0;_dm(n,kind);const lost=(a-S.hp)+(b-(S.sh||0));if(lost>0)HFX.v=Math.min(1,HFX.v+.22+lost/30)}}
function gradePatch(){if(!GRADE||GRADE.uniforms.hit)return;GRADE.uniforms.hit={value:0};const m=GRADE.material;if(m.uniforms!==GRADE.uniforms)m.uniforms.hit=GRADE.uniforms.hit;
m.fragmentShader=m.fragmentShader.replace('uniform float tm,bst;','uniform float tm,bst,hit;').replace('vec2 off=d*(.002+bst*.006)*r2*4.;','vec2 off=d*(.002+bst*.006+hit*.045)*r2*4.+vec2(hit*.005,hit*.0015);').replace('gl_FragColor=vec4(c,1.);}','c=mix(c,c*vec3(1.22,.86,.86),hit*.45);gl_FragColor=vec4(c,1.);}');m.needsUpdate=true}
if(typeof setupGrade=='function'){const _sg=setupGrade;setupGrade=function(){_sg();gradePatch()}}gradePatch();
TICK.push(dt=>{HFX.v=Math.max(0,HFX.v-dt*2.4);if(GRADE&&GRADE.uniforms.hit)GRADE.uniforms.hit.value=HFX.v});
{const _ov=overlay;overlay=function(){_ov();const W=innerWidth,H=innerHeight;
// mobile : pas de passe d'étalonnage, on simule l'aberration et le flou de vitesse à l'écran
if(!GRADE&&HFX.v>.02){OX.save();OX.globalCompositeOperation='lighter';const R=Math.max(W,H)*.7;for(const[dx,col]of[[-6,'255,40,60'],[6,'40,220,255']]){const g=OX.createRadialGradient(W/2+dx*HFX.v*3,H/2,R*.45,W/2+dx*HFX.v*3,H/2,R);g.addColorStop(0,`rgba(${col},0)`);g.addColorStop(1,`rgba(${col},${.28*HFX.v})`);OX.fillStyle=g;OX.fillRect(0,0,W,H)}OX.restore()}
if(!DESK&&mode=='space'&&!S.docked&&fovK>.08&&!JMP.on){const k=fovK*clamp(S.spd/Math.max(1,boostSpd()),0,1);if(k>.05){OX.save();OX.strokeStyle=`rgba(210,235,255,${.32*k})`;OX.lineWidth=1.2;OX.beginPath();const cx=W/2,cy=H*.45,R=Math.hypot(W,H)/2;for(let i=0;i<26;i++){const a=Math.random()*TAU,r0=R*(.55+Math.random()*.3),r1=r0+R*(.1+k*.25);OX.moveTo(cx+Math.cos(a)*r0,cy+Math.sin(a)*r0);OX.lineTo(cx+Math.cos(a)*r1,cy+Math.sin(a)*r1)}OX.stroke();OX.restore()}}}}
// ===== ÉPAVES : ambiance =====
const SCRT=[0,1,2].map(k=>{const c=mkC(128,80),g=c.getContext('2d'),r=rng(41+k);g.fillStyle='#03080a';g.fillRect(0,0,128,80);const col=['#5aff9a','#ffb040','#7fd8ff'][k];g.fillStyle=col;g.strokeStyle=col;g.font='bold 9px monospace';
if(k==0){for(let i=0;i<7;i++){g.globalAlpha=.4+r()*.6;g.fillRect(6,6+i*10,20+r()*90,4)}}else if(k==1){g.globalAlpha=.9;g.fillText('ERREUR 0x'+(r()*65535|0).toString(16).toUpperCase(),6,16);g.fillText('COQUE BRÈCHE',6,30);g.globalAlpha=.5;for(let i=0;i<4;i++)g.fillRect(6,40+i*9,30+r()*80,3)}
else{g.globalAlpha=.8;g.lineWidth=1.5;g.beginPath();for(let x=0;x<128;x+=4){const y=40+Math.sin(x*.12)*14*r()+rv(6);x?g.lineTo(x,y):g.moveTo(x,y)}g.stroke();g.globalAlpha=.4;g.strokeRect(3,3,122,74)}return new THREE.CanvasTexture(c)});
const DFX={cr:9,fl:14,flT:0,amb0:null,dust:null};
const DFXG={hous:new THREE.CylinderGeometry(.16,.22,.3,8),cone:new THREE.ConeGeometry(.9,4.5,14,1,true).translate(0,-2.25,0).rotateZ(Math.PI/2),scr:new THREE.PlaneGeometry(.9,.56),fr:new THREE.BoxGeometry(1,.66,.08)};
const DFXM={hous:new THREE.MeshStandardMaterial({color:0x2a2e34,metalness:.7,roughness:.4}),beam:new THREE.MeshBasicMaterial({color:0xff3020,transparent:true,opacity:.1,blending:ADDB,depthWrite:false,side:THREE.DoubleSide}),bulb:new THREE.MeshBasicMaterial({color:0xff4030}),cab:new THREE.MeshStandardMaterial({color:0x15171a,roughness:.7}),cab2:new THREE.MeshStandardMaterial({color:0x6a3a1a,roughness:.6})};
function derAtmo(lv){const L=lv.L,r=rng((lv.o.seed||7)+91),g=lv.g,at=L.at;const fx=lv.fx={bea:[],scr:[],ends:[]};
const cable=(a,b,sag,mat,rad=.035)=>{const m=a.clone().lerp(b,.5);m.y-=sag;const geo=new THREE.TubeGeometry(new THREE.QuadraticBezierCurve3(a,m,b),10,rad,5,false);const o=new THREE.Mesh(geo,mat);g.add(o);return o};
for(const rm of L.rooms){if(rm.role=='airlock')continue;const ceil=rm.role=='breach'?DBRE:DCEIL,x0=rm.x*DTS,z0=rm.z*DTS,W=rm.w*DTS,Hh=rm.h*DTS;
// gyrophare
if(/engine|cargo|breach|armory/.test(rm.role)||r()<.35){const B=new THREE.Group();B.position.set(x0+.7+r()*(W-1.4),ceil-.18,z0+.7);g.add(B);B.add(new THREE.Mesh(DFXG.hous,DFXM.hous));const rot=new THREE.Group();rot.position.y=-.22;B.add(rot);const bl=new THREE.Mesh(new THREE.SphereGeometry(.12,8,6),DFXM.bulb);rot.add(bl);for(const s of[1,-1]){const c=new THREE.Mesh(DFXG.cone,DFXM.beam);c.rotation.y=s>0?0:Math.PI;c.rotation.z=-.18;rot.add(c)}const sp=sprite(0xff3020,1.2,.9);rot.add(sp);fx.bea.push({rot,sp,ph:r()*9})}
// écrans qui grésillent sur les murs
let ns=0;for(let i=rm.x;i<rm.x+rm.w&&ns<2;i++)for(let j=rm.z;j<rm.z+rm.h&&ns<2;j++){for(const[di,dj]of[[1,0],[-1,0],[0,1],[0,-1]]){if(ns>=2||at(i+di,j+dj)!=-2||r()>.12)continue;const cx=i*DTS+DTS/2+di*(DTS/2-.08),cz=j*DTS+DTS/2+dj*(DTS/2-.08);const S2=new THREE.Group();S2.position.set(cx,1.65,cz);S2.rotation.y=Math.atan2(-di,-dj);g.add(S2);
const fr=new THREE.Mesh(DFXG.fr,DFXM.hous);fr.position.z=-.03;S2.add(fr);const mt=new THREE.MeshBasicMaterial({map:SCRT[(r()*3)|0]});const sc=new THREE.Mesh(DFXG.scr,mt);sc.position.z=.02;S2.add(sc);fx.scr.push({mt,on:1,ph:r()*9,bad:r()<.6});ns++}}
// câbles qui pendent du plafond
const nc=1+(r()*2|0);for(let k=0;k<nc;k++){const a=new V3(x0+.6+r()*(W-1.2),ceil-.05,z0+.6+r()*(Hh-1.2));if(r()<.5){const b=new V3(x0+.6+r()*(W-1.2),ceil-.05,z0+.6+r()*(Hh-1.2));cable(a,b,.8+r()*1.2,r()<.3?DFXM.cab2:DFXM.cab)}else{const e=new V3(a.x+rv(.6),1.1+r()*1.3,a.z+rv(.6));cable(a,e,-.2,DFXM.cab,.045);fx.ends.push({p:e,t:r()*4})}}}
// couloirs : quelques câbles arrachés
for(let j=0;j<DGH;j++)for(let i=0;i<DGW;i++)if(at(i,j)==-1&&r()<.08){const a=new V3(i*DTS+DTS/2+rv(1.5),DCEIL-.05,j*DTS+DTS/2+rv(1.5)),e=new V3(a.x+rv(.5),1.3+r()*1.2,a.z+rv(.5));cable(a,e,-.15,DFXM.cab,.04);fx.ends.push({p:e,t:r()*4})}
if(!DFX.dust){const N=DESK?90:60,geo=new THREE.BufferGeometry(),P=new Float32Array(N*3);for(let i=0;i<N*3;i++)P[i]=rv(4);geo.setAttribute('position',new THREE.BufferAttribute(P,3));const pm=new THREE.PointsMaterial({color:0xfff0d8,size:DESK?.028:.04,transparent:true,opacity:.38,depthWrite:false,blending:ADDB});DFX.dust=new THREE.Points(geo,pm);DFX.dust.frustumCulled=false;DFX.dust.userData.v=Array.from({length:N},()=>new V3(rv(.05),rv(.03),rv(.05)));DER.scene.add(DFX.dust)}}
{const _db=derBuild;derBuild=function(o){const lv=_db(o);try{derAtmo(lv)}catch(e){console.warn(e)}return lv}}
{const _du=derUpdate;derUpdate=function(dt){_du(dt);const lv=DER.lvl;if(!lv||!DER.on||!lv.fx)return;const fx=lv.fx,P=DER.p;
for(const b of fx.bea){b.rot.rotation.y+=dt*4.2;b.sp.material.opacity=.6+.4*Math.sin(t*8+b.ph)}
for(const s of fx.scr){if(s.bad&&Math.random()<dt*(s.on?1.5:6))s.on=!s.on;const k=s.on?(.75+.25*Math.sin(t*37+s.ph)*(s.bad?1:.2)):.06;s.mt.color.setScalar(k)}
for(const e of fx.ends){e.t-=dt;if(e.t>0)continue;e.t=1.5+Math.random()*4;if(Math.abs(e.p.x-P.x)+Math.abs(e.p.z-P.z)>14)continue;for(let i=0;i<10;i++)SPK.emit(e.p.x,e.p.y,e.p.z,rv(2),rv(1.5)-.6,rv(2),.5+Math.random()*.4,1,.8,.4,.35);tone(2400+Math.random()*1500,1800,.06,'square',.012);noise(.08,.05,4000)}
// poussière qui flotte dans le faisceau de la lampe
if(DFX.dust){const D=DFX.dust,A=D.geometry.attributes.position.array,V=D.userData.v,f=_d1.set(0,0,-1).applyQuaternion(camera.quaternion),c=_d2.copy(camera.position).addScaledVector(f,3.2);D.position.copy(c);
for(let i=0;i<V.length;i++){const j=i*3;A[j]+=V[i].x*dt*6;A[j+1]+=V[i].y*dt*6;A[j+2]+=V[i].z*dt*6;const wx=A[j]+c.x,wy=A[j+1]+c.y,wz=A[j+2]+c.z,dx=wx-camera.position.x,dy=wy-camera.position.y,dz=wz-camera.position.z,L=Math.hypot(dx,dy,dz),cs=(dx*f.x+dy*f.y+dz*f.z)/Math.max(.01,L);
if(Math.abs(A[j])>3.4||Math.abs(A[j+1])>2.2||Math.abs(A[j+2])>3.4||cs<.82||L<.6){const d=1+Math.random()*3.6,a=Math.random()*TAU,s=Math.random()*d*.32;_d3.set(Math.cos(a)*s,Math.sin(a)*s,-d).applyQuaternion(camera.quaternion).add(camera.position).sub(c);A[j]=_d3.x;A[j+1]=_d3.y;A[j+2]=_d3.z}}D.geometry.attributes.position.needsUpdate=true;D.visible=true}
// craquements de la coque et lumière qui vacille
const cave=DER.on.q&&DER.on.q.cave;DFX.cr-=dt;if(cave&&DFX.cr<=0){DFX.cr=1.5+Math.random()*5;const f=1400+Math.random()*1400;tone(f,f*.55,.09,'sine',.022);if(Math.random()<.3)setTimeout(()=>tone(f*.8,f*.5,.08,'sine',.015),180);if(Math.random()<.08){noise(1.2,.05,300);tone(55,40,1.4,'sawtooth',.02)}}if(DFX.cr<=0){DFX.cr=7+Math.random()*12;if(Math.random()<.6){tone(70+Math.random()*30,40,1.2+Math.random(),'sawtooth',.028);noise(.9,.045,220)}else{tone(190,120,.3,'square',.025);noise(.18,.1,1600);setTimeout(()=>tone(160,110,.25,'square',.018),260)}if(Math.random()<.3)shake=Math.min(.4,shake+.15)}
if(cave)return;if(DFX.amb0==null)DFX.amb0=DRAMB.intensity;DFX.fl-=dt;if(DFX.fl<=0){DFX.fl=10+Math.random()*16;DFX.flT=.45}if(DFX.flT>0){DFX.flT-=dt;DRAMB.intensity=DFX.amb0*(Math.random()<.5?.25:.8)}else DRAMB.intensity=DFX.amb0}}
