// ===== PLANÈTES 3 : mer de nuages, villes extraterrestres, bioluminescence, eau miroir + sillage, végétation au vent, ciel (lunes, planètes, étoiles filantes), léviathans, traversée des nuages à l'atterrissage =====
const U3={a:new V3(),b:new V3(),c:new V3(),col:new THREE.Color(),F:null};
// texture de bruit qui se répète (nuages, transitions) : bien moins coûteuse qu'un bruit calculé
const NZ3=(()=>{const N=128,d=new Uint8Array(N*N*4),r=rng(808),acc=new Float32Array(N*N);let amp=.5,tot=0;
for(const f of[4,8,16,32]){const L=[];for(let i=0;i<f*f;i++)L.push(r());const at=(x,y)=>L[((y%f+f)%f)*f+((x%f+f)%f)];for(let y=0;y<N;y++)for(let x=0;x<N;x++){const X=x/N*f,Y=y/N*f,i=Math.floor(X),j=Math.floor(Y),fx=X-i,fy=Y-j,sx=fx*fx*(3-2*fx),sy=fy*fy*(3-2*fy),A=at(i,j),B=at(i+1,j),C=at(i,j+1),D=at(i+1,j+1);acc[y*N+x]+=(A+(B-A)*sx+(C-A)*sy+(A-B-C+D)*sx*sy)*amp}tot+=amp;amp*=.5}
let mn=1e9,mx=-1e9;for(const v of acc){mn=Math.min(mn,v);mx=Math.max(mx,v)}for(let i=0;i<N*N;i++){const v=(acc[i]-mn)/(mx-mn)*255;d[i*4]=d[i*4+1]=d[i*4+2]=v;d[i*4+3]=255}
const t=new THREE.DataTexture(d,N,N,THREE.RGBAFormat);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.magFilter=t.minFilter=THREE.LinearFilter;t.needsUpdate=true;t.userData={N,d};return t})();
const nz3At=(u,v)=>{const{N,d}=NZ3.userData,x=Math.floor(((u%1+1)%1)*N),y=Math.floor(((v%1+1)%1)*N);return d[(y*N+x)*4]/255};
// ---------- #7 mer de nuages ----------
const CS3_FS='uniform sampler2D nz;uniform float tm,cov,op;uniform vec3 lit,shd,fogC,camP;varying vec3 vW;void main(){vec2 p=vW.xz*.00055+vec2(tm*.004,tm*.0025);float n=texture2D(nz,p).r*.62+texture2D(nz,p*2.7+.3).r*.28+texture2D(nz,p*7.1-.5).r*.1;float d=smoothstep(cov,cov+.18,n);float top=smoothstep(cov+.05,cov+.32,n);float below=step(camP.y,vW.y);vec3 c=mix(shd,lit,mix(top,.25,below));float dist=length(vW.xz-camP.xz);float f=smoothstep(900.,3200.,dist);c=mix(c,fogC,f*.7);gl_FragColor=vec4(c,d*op*(1.-f*.6));}';
const CS3={m:null,Y:235,on:false,cov:.45,inside:0};
function cs3Build(F,sc){const ty=F.ty;CS3.on=ty!='Désertique';if(!CS3.on)return;{const hs2=[];for(let i=0;i<36;i++)for(let j=0;j<36;j++)hs2.push(F.h(-1500+i*86,-1500+j*86));hs2.sort((a,b)=>a-b);CS3.Y=Math.max(230,hs2[Math.floor(hs2.length*.93)]+45)}CS3.cov=ty=='Volcanique'?.5:ty=='Jungle'||ty=='Océanique'?.42:.48;
const m=new THREE.Mesh(new THREE.PlaneGeometry(7000,7000,1,1).rotateX(-Math.PI/2),new THREE.ShaderMaterial({uniforms:{nz:{value:NZ3},tm:TM,cov:{value:CS3.cov},op:{value:.95},lit:{value:new THREE.Color(1,1,1)},shd:{value:new THREE.Color(.6,.65,.72)},fogC:{value:new THREE.Color()},camP:{value:new V3()}},vertexShader:'varying vec3 vW;void main(){vec4 w=modelMatrix*vec4(position,1.);vW=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}',fragmentShader:CS3_FS,transparent:true,depthWrite:false,side:THREE.DoubleSide,fog:false}));
m.position.y=CS3.Y;m.renderOrder=3;m.frustumCulled=false;sc.add(m);CS3.m=m;CS3.tint=ty=='Volcanique'?new THREE.Color(.35,.3,.28):ty=='Glacée'?new THREE.Color(.92,.96,1):new THREE.Color(1,1,1)}
function cs3Tick(F){if(!CS3.on||!CS3.m)return;const cp=camera.position,u=CS3.m.material.uniforms;CS3.m.position.x=cp.x;CS3.m.position.z=cp.z;u.camP.value.copy(cp);u.fogC.value.copy(F.fog.color);
const day=typeof DN!='undefined'?DN.day:1,night=typeof DN!='undefined'?DN.night:0;u.lit.value.copy(CS3.tint).multiplyScalar(.25+day*.85).lerp(U3.col.set(1,.62,.4),(DN&&DN.set)||0);u.shd.value.copy(CS3.tint).multiplyScalar(.12+day*.5).lerp(U3.col.set(.08,.1,.18),night*.6);
// dans la couche : on ne voit plus rien
const dy=Math.abs(cp.y-CS3.Y);let k=0;if(dy<30){const tm=t,px=cp.x*.00055+tm*.004,pz=cp.z*.00055+tm*.0025,n=nz3At(px,pz)*.62+nz3At(px*2.7+.3,pz*2.7+.3)*.28+nz3At(px*7.1-.5,pz*7.1-.5)*.1,dd=clamp((n-CS3.cov)/.18,0,1);k=clamp(1-dy/30,0,1)*dd*dd*(3-2*dd)}CS3.inside=k}
// ---------- #8 villes extraterrestres ----------
const CT3={on:false};
function ct3Tex(){if(CT3.tex)return CT3.tex;const a=mkC(64,256),b=mkC(64,256),ga=a.getContext('2d'),gb=b.getContext('2d'),r=rng(77);ga.fillStyle='#a3adbb';ga.fillRect(0,0,64,256);gb.fillStyle='#000';gb.fillRect(0,0,64,256);for(let y=0;y<24;y++){const lit=r();for(let x=0;x<6;x++){const X=x*10+3,Y=y*10.6+3;ga.fillStyle='#3c4a5e';ga.fillRect(X,Y,6,6);if(r()<.25+lit*.4){gb.fillStyle=r()<.12?'#9fe0ff':'#ffd9a0';gb.fillRect(X,Y,6,6)}}ga.fillStyle='rgba(255,255,255,.18)';ga.fillRect(0,y*10.6,64,1.5)}
const ta=new THREE.CanvasTexture(a),tb=new THREE.CanvasTexture(b);CT3.tex={map:ta,em:tb};return CT3.tex}
function ct3Inhab(p){const ty=ptype(p);return !p.ring&&ty!='Volcanique'&&hs(p.x|0,p.z|0,8)<.6&&pvar(p)!='ruines'}
function ct3Build(F,sc){CT3.on=false;const p=F.p;if(!ct3Inhab(p))return;const h=F.h,r=rng(seedOf(p.x,p.y,p.z,91));let best=null;
for(let k=0;k<70;k++){const a=r()*TAU,d=850+r()*450,x=Math.cos(a)*d,z=Math.sin(a)*d,y=h(x,z);if(y<8)continue;if(F.op&&Math.hypot(x-F.op.x,z-F.op.z)<380)continue;if(W3.ruin&&Math.hypot(x-W3.ruin.x,z-W3.ruin.z)<400)continue;let sl=0;for(const[dx,dz]of[[60,0],[-60,0],[0,60],[0,-60]])sl=Math.max(sl,Math.abs(h(x+dx,z+dz)-y));if(!best||sl<best.sl)best={x,z,y,sl}}if(!best)return;
const cx=best.x,cz=best.z,n=DESK?34:20,tw=[],tex=ct3Tex(),hu=F.hu;
for(let i=0;i<n;i++){const a=r()*TAU,d=Math.sqrt(r())*130,x=cx+Math.cos(a)*d,z=cz+Math.sin(a)*d,y=h(x,z),hh=(30+r()*60)*(1.6-d/200),w=7+r()*9;tw.push({x,z,y,hh,w,ry:r()*TAU,k:r()});GR.col.push({x,z,r:w*.75})}
const mk=(col,em)=>new THREE.MeshStandardMaterial({color:col,map:tex.map,emissive:0xffffff,emissiveMap:tex.em,emissiveIntensity:em,roughness:.45,metalness:.35});
CT3.mA=mk(0xc4d6ea,.2);CT3.mB=mk(0xe6dccb,.2);const box=new THREE.BoxGeometry(1,1,1).translate(0,.5,0),d=new THREE.Object3D();
for(const[mat,list]of[[CT3.mA,tw.filter(o=>o.k<.6)],[CT3.mB,tw.filter(o=>o.k>=.6)]]){if(!list.length)continue;const m=new THREE.InstancedMesh(box,mat,list.length);list.forEach((o,i)=>{d.position.set(o.x,o.y-3,o.z);d.rotation.set(0,o.ry,0);d.scale.set(o.w,o.hh,o.w);d.updateMatrix();m.setMatrixAt(i,d.matrix)});m.castShadow=m.receiveShadow=DESK;sc.add(m)}
// enseignes néon, dômes, feux d'antenne
const neon=[],nc=[new THREE.Color().setHSL(((hu+180)%360)/360,1,.6),new THREE.Color(1,.3,.85),new THREE.Color(.3,.95,1)];for(const o of tw)if(o.k>.35){neon.push({x:o.x,z:o.z,y:o.y+o.hh*(.35+o.k*.4),w:o.w,ry:o.ry,c:nc[(o.k*30|0)%3]})}
if(neon.length){const m=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshBasicMaterial(),neon.length);neon.forEach((o,i)=>{d.position.set(o.x,o.y,o.z);d.rotation.set(0,o.ry,0);d.scale.set(o.w*1.03,1.2,o.w*1.03);d.updateMatrix();m.setMatrixAt(i,d.matrix);m.setColorAt(i,o.c)});sc.add(m)}
const dm=[];for(let i=0;i<5;i++){const a=r()*TAU,dd=40+r()*100,x=cx+Math.cos(a)*dd,z=cz+Math.sin(a)*dd;dm.push({x,z,y:h(x,z),s:12+r()*14})}{const m=new THREE.InstancedMesh(new THREE.SphereGeometry(1,24,12,0,TAU,0,Math.PI/2),new THREE.MeshStandardMaterial({color:0xa8d8ff,emissive:0x2a6a9a,emissiveIntensity:.3,transparent:true,opacity:.75,roughness:.1,metalness:.3}),dm.length);dm.forEach((o,i)=>{d.position.set(o.x,o.y-1,o.z);d.rotation.set(0,0,0);d.scale.setScalar(o.s);d.updateMatrix();m.setMatrixAt(i,d.matrix)});sc.add(m);CT3.dome=m.material}
const ant=[];for(const o of tw)if(o.hh>55)ant.push(o.x,o.y+o.hh-3+2,o.z);const ag=new THREE.BufferGeometry();ag.setAttribute('position',new THREE.Float32BufferAttribute(ant,3));CT3.ant=new THREE.Points(ag,new THREE.PointsMaterial({map:GLOW,color:0xff3020,size:9,transparent:true,blending:ADDB,depthWrite:false}));sc.add(CT3.ant);
// trafic aérien
const NF=DESK?12:8;CT3.fl=[];CT3.flm=new THREE.InstancedMesh(new THREE.BoxGeometry(1.6,.7,4.2),new THREE.MeshStandardMaterial({color:0xd8dde6,metalness:.6,roughness:.35,emissive:0x223040}),NF);CT3.flm.frustumCulled=false;sc.add(CT3.flm);const lp=new Float32Array(NF*3);const lg=new THREE.BufferGeometry();lg.setAttribute('position',new THREE.BufferAttribute(lp,3));CT3.fll=new THREE.Points(lg,new THREE.PointsMaterial({map:GLOW,color:0xfff0c0,size:7,transparent:true,blending:ADDB,depthWrite:false}));CT3.fll.frustumCulled=false;sc.add(CT3.fll);
for(let i=0;i<NF;i++)CT3.fl.push({R:60+r()*160,y:best.y+35+r()*130,a:r()*TAU,sp:(.12+r()*.18)*(r()<.5?-1:1),e:.6+r()*.4});
CT3.glow=sprite(0xffb070,600,0);CT3.glow.material=CT3.glow.material.clone();CT3.glow.material.fog=false;CT3.glow.position.set(cx,best.y+60,cz);sc.add(CT3.glow);
CT3.on=true;CT3.c=new V3(cx,best.y,cz)}
function ct3Tick(dt){if(!CT3.on)return;const night=typeof DN!='undefined'?DN.night:0,em=.12+night*1.5;CT3.mA.emissiveIntensity=CT3.mB.emissiveIntensity=em;CT3.ant.material.opacity=Math.sin(t*3)>0?1:.15;CT3.glow.material.opacity=night*.35;
const d=U3.d||(U3.d=new THREE.Object3D()),P=CT3.fll.geometry.attributes.position;CT3.fl.forEach((f,i)=>{f.a+=f.sp*dt;const x=CT3.c.x+Math.cos(f.a)*f.R,z=CT3.c.z+Math.sin(f.a)*f.R*f.e,y=f.y+Math.sin(f.a*2)*6;d.position.set(x,y,z);d.lookAt(CT3.c.x+Math.cos(f.a+f.sp*.2)*f.R,y,CT3.c.z+Math.sin(f.a+f.sp*.2)*f.R*f.e);d.updateMatrix();CT3.flm.setMatrixAt(i,d.matrix);P.setXYZ(i,x,y-.6,z)});CT3.flm.instanceMatrix.needsUpdate=true;P.needsUpdate=true}
// ---------- #9 bioluminescence ----------
const BI3={on:false};
function bi3Build(F,sc){BI3.on=false;const ty=F.ty;if(ty!='Jungle'&&ty!='Océanique'&&ty!='Cristalline')return;const h=F.h,r=rng(seedOf(F.p.x,F.p.y,F.p.z,93)),hu=F.hu,list=[],n=DESK?220:120;
for(let i=0;i<n*3&&list.length<n;i++){const x=(r()*2-1)*1300,z=(r()*2-1)*1300,y=h(x,z);if(y<3)continue;const k=1+r()*3|0;for(let j=0;j<k;j++){const xx=x+rv(5),zz=z+rv(5);list.push({x:xx,z:zz,y:h(xx,zz),s:.6+r()*1.6,a:r()*TAU})}}
const cap=new THREE.SphereGeometry(1,12,6,0,TAU,0,Math.PI/2).scale(1,.55,1).translate(0,1,0),stem=new THREE.CylinderGeometry(.18,.25,1,6).translate(0,.5,0),geo=mergeG([{g:cap},{g:stem,c:[.4,.4,.45]}]);
const col=new THREE.Color().setHSL(ty=='Cristalline'?(hu+60)%360/360:ty=='Jungle'?.47:.52,.9,.55);BI3.mat=new THREE.MeshStandardMaterial({vertexColors:true,color:0xcfd8e0,emissive:col,emissiveIntensity:.05,roughness:.6});
const m=new THREE.InstancedMesh(geo,BI3.mat,list.length),d=new THREE.Object3D();list.forEach((o,i)=>{d.position.set(o.x,o.y-.2,o.z);d.rotation.set(0,o.a,0);d.scale.setScalar(o.s);d.updateMatrix();m.setMatrixAt(i,d.matrix)});sc.add(m);
// lucioles autour du joueur
const N=DESK?90:55,pos=new Float32Array(N*3);BI3.ff=[];for(let i=0;i<N;i++)BI3.ff.push({o:new V3(rv(70),2+Math.random()*10,rv(70)),ph:Math.random()*TAU,sp:.4+Math.random()*.8});const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(pos,3));
BI3.pts=new THREE.Points(g,new THREE.PointsMaterial({map:GLOW,color:col.clone().lerp(new THREE.Color(1,1,.6),.5),size:2.2,transparent:true,opacity:0,blending:ADDB,depthWrite:false}));BI3.pts.frustumCulled=false;sc.add(BI3.pts);BI3.on=true;BI3.c=new V3()}
function bi3Tick(dt){if(!BI3.on)return;const night=typeof DN!='undefined'?DN.night:0;BI3.mat.emissiveIntensity=.04+night*1.6*(.85+.15*Math.sin(t*1.3));BI3.pts.material.opacity=night;if(night<.05)return;
const cp=FOOT.on?(FOOT.model?FOOT.model.position:FOOT.pos):camera.position;if(BI3.c.distanceTo(cp)>60)BI3.c.copy(cp);const P=BI3.pts.geometry.attributes.position,h=SURF.height;
BI3.ff.forEach((f,i)=>{f.ph+=dt*f.sp;const x=BI3.c.x+f.o.x+Math.sin(f.ph)*4,z=BI3.c.z+f.o.z+Math.cos(f.ph*.7)*4;P.setXYZ(i,x,Math.max(0,h(x,z))+f.o.y*.4+1+Math.sin(f.ph*2.3)*.8,z)});P.needsUpdate=true}
// ---------- #10 eau miroir (reflets du relief) + sillage ----------
const WA3={mat:null,foam:null,fi:0,ft:0,F:[]};
function wa3Patch(F){const m=F.lmat;if(!m||!m.uniforms||!m.uniforms.shallow||m.userData.wa3)return;const N=DESK?160:110,d=new Uint8Array(N*N*4),HALF=F.HALF||1600;for(let j=0;j<N;j++)for(let i=0;i<N;i++){const x=-HALF+(i+.5)/N*HALF*2,z=-HALF+(j+.5)/N*HALF*2,v=clamp((F.h(x,z)+30)/360,0,1)*255,k=(j*N+i)*4;d[k]=d[k+1]=d[k+2]=v;d[k+3]=255}
const t2=new THREE.DataTexture(d,N,N,THREE.RGBAFormat);t2.magFilter=t2.minFilter=THREE.LinearFilter;t2.needsUpdate=true;m.uniforms.hm2={value:t2};m.uniforms.rcol={value:new THREE.Color()};
const a='vec3 col=mix(wc,sky,fr*.75);';if(m.fragmentShader.indexOf(a)<0)return;m.fragmentShader=m.fragmentShader.replace('uniform sampler2D hm;','uniform sampler2D hm;uniform sampler2D hm2;uniform vec3 rcol;').replace(a,'vec3 Nr=normalize(vec3(-g.x*.07,1.,-g.y*.07));vec3 R=reflect(-V,Nr);vec3 rc=sky;float rh=0.;if(R.y>0.){for(int i=1;i<=10;i++){float s=float(i*i)*7.;vec3 q=vW+R*s;vec2 u2=(q.xz+hf)/(2.*hf);if(u2.x<0.||u2.x>1.||u2.y<0.||u2.y>1.)break;float th=texture2D(hm2,u2).r*360.-30.;if(th>q.y){rc=mix(rcol,fogColor,clamp(s/fogFar,0.,1.)*.75);rh=1.;break;}}}float frr=.03+.97*pow(1.-max(dot(Nr,V),0.),4.);vec3 col=mix(wc,rc,clamp(frr*1.05+.1+rh*.25,0.,.94));');
m.needsUpdate=true;m.userData.wa3=1;WA3.mat=m;WA3.rc=new THREE.Color().setHSL(F.hu/360,.22,.16)}
function wa3Foam(sc){const c=mkC(64),g=c.getContext('2d'),gr=g.createRadialGradient(32,32,8,32,32,31);gr.addColorStop(0,'rgba(255,255,255,0)');gr.addColorStop(.55,'rgba(255,255,255,.75)');gr.addColorStop(.8,'rgba(255,255,255,.25)');gr.addColorStop(1,'rgba(255,255,255,0)');g.fillStyle=gr;g.fillRect(0,0,64,64);
const N=60,m=new THREE.InstancedMesh(new THREE.PlaneGeometry(1,1).rotateX(-Math.PI/2),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(c),transparent:true,blending:ADDB,depthWrite:false}),N);m.frustumCulled=false;const d=new THREE.Object3D();d.scale.setScalar(.001);d.updateMatrix();for(let i=0;i<N;i++){m.setMatrixAt(i,d.matrix);m.setColorAt(i,U3.col.setRGB(0,0,0))}sc.add(m);WA3.foam=m;WA3.F=[]}
function wa3Spawn(x,z,s0,s1,life){if(!WA3.foam)return;const i=WA3.fi=(WA3.fi+1)%60;WA3.F[i]={x,z,s0,s1,l:life,ml:life}}
function wa3Tick(dt){if(WA3.mat){const day=typeof DN!='undefined'?DN.day:1;WA3.mat.uniforms.rcol.value.copy(WA3.rc).multiplyScalar(.25+day*.75)}if(!WA3.foam)return;
if(!FOOT.on&&mode=='surf'){const p=ship.position,gy=SURF.height(p.x,p.z);if(gy<-1.5&&p.y<32&&S.spd>18){WA3.ft-=dt;if(WA3.ft<=0){WA3.ft=.07;const k=1-p.y/32;wa3Spawn(p.x+rv(2),p.z+rv(2),4,16+S.spd*.05,2.6+k);if(Math.random()<k)for(let i=0;i<6;i++)SPK.emit(p.x+rv(4),.5,p.z+rv(4),rv(10)-S.vel.x*.2,8+Math.random()*16*k,rv(10)-S.vel.z*.2,.7,.85,.92,1,.9)}}}
const d=U3.d2||(U3.d2=new THREE.Object3D());for(let i=0;i<60;i++){const f=WA3.F[i];if(!f)continue;f.l-=dt;const a=clamp(1-f.l/f.ml,0,1);if(f.l<=0){WA3.F[i]=null;d.scale.setScalar(.001)}else{d.scale.set(f.s0+(f.s1-f.s0)*Math.sqrt(a),1,f.s0+(f.s1-f.s0)*Math.sqrt(a))}d.position.set(f.x,.25,f.z);d.updateMatrix();WA3.foam.setMatrixAt(i,d.matrix);const b=f.l>0?(1-a)*.8:0;WA3.foam.setColorAt(i,U3.col.setRGB(b,b,b))}WA3.foam.instanceMatrix.needsUpdate=true;if(WA3.foam.instanceColor)WA3.foam.instanceColor.needsUpdate=true}
// ---------- #11 végétation au vent + souffle des réacteurs ----------
const W11={wind:{value:.6},jp:{value:new V3(0,-999,0)},jk:{value:0}};
function w11Patch(m){if(!m||m.userData.w11)return;m.userData.w11=1;const prev=m.onBeforeCompile;m.onBeforeCompile=(sh,r)=>{if(prev&&prev!==THREE.Material.prototype.onBeforeCompile)try{prev(sh,r)}catch(e){}sh.uniforms.w11W=W11.wind;sh.uniforms.w11T=TM;sh.uniforms.w11P=W11.jp;sh.uniforms.w11K=W11.jk;
sh.vertexShader='uniform float w11W,w11T,w11K;uniform vec3 w11P;\n'+sh.vertexShader.replace('#include <project_vertex>',`vec4 mvPosition=vec4(transformed,1.);
#ifdef USE_INSTANCING
mvPosition=instanceMatrix*mvPosition;float w11h=max(mvPosition.y-instanceMatrix[3].y,0.);vec3 w11ip=instanceMatrix[3].xyz;
#else
float w11h=max(transformed.y,0.);vec3 w11ip=vec3(0.);
#endif
vec3 w11wp=(modelMatrix*mvPosition).xyz;float w11ph=dot(w11ip.xz,vec2(.13,.17));float w11sw=w11h*w11h/(w11h+6.)*w11W*.07;mvPosition.x+=sin(w11T*1.6+w11ph)*w11sw+sin(w11T*3.7+w11ph*2.)*w11sw*.3;mvPosition.z+=cos(w11T*1.3+w11ph*1.4)*w11sw*.7;
vec2 w11dj=w11wp.xz-w11P.xz;float w11dl=length(w11dj);float w11jw=w11K*smoothstep(40.,4.,w11dl)*smoothstep(70.,12.,abs(w11wp.y-w11P.y));if(w11jw>0.){vec2 w11pd=w11dj/max(w11dl,.1);float w11fl=.75+.25*sin(w11T*24.+w11dl);mvPosition.xz+=w11pd*w11jw*min(w11h,8.)*.5*w11fl;mvPosition.y-=w11jw*min(w11h,8.)*.12;}
mvPosition=modelViewMatrix*mvPosition;gl_Position=projectionMatrix*mvPosition;`)};const pk=prev&&prev!==THREE.Material.prototype.onBeforeCompile?String(prev).length+String(prev).slice(0,40):'';m.customProgramCacheKey=()=>'w11'+pk;m.needsUpdate=true}
function w11Apply(sc){const skip=new Set([...(typeof ROCKG!='undefined'?ROCKG:[]),...(typeof W3G!='undefined'?[W3G.crys]:[])]);sc.traverse(o=>{if(!o.isInstancedMesh||skip.has(o.geometry))return;const m=o.material;if(!m||Array.isArray(m)||!(m.isMeshStandardMaterial||m.isMeshLambertMaterial||m.isMeshPhongMaterial))return;if(CT3.mA===m||CT3.mB===m||BI3.mat===m||(m.emissiveMap))return;if(o===CT3.flm||o===WA3.foam)return;w11Patch(m)})}
function w11Tick(F){W11.wind.value=.55+(F.storm||0)*1.6;if(!FOOT.on&&mode=='surf'){const p=ship.position,gy=Math.max(0,SURF.height(p.x,p.z)),alt=p.y-gy;W11.jp.value.copy(p);W11.jk.value=clamp(1-alt/45,0,1)*clamp(.35+(S.thr||0)*.5+(isBoost()?.4:0),0,1.3)}else W11.jk.value=0}
// ---------- #12 ciel : lunes, planètes voisines, anneaux, étoiles filantes ----------
const SK12={o:[],ss:[],axis:new V3(),t:6};
const SKB_FS='uniform vec3 sd,col;uniform float op,ring;varying vec3 vN;varying vec2 vUv;void main(){float l=max(dot(normalize(vN),sd),0.);float b=.06+l*1.05;gl_FragColor=vec4(col*b,op);}';
function sk12Build(F,sc){SK12.o=[];const p=F.p,r=rng(seedOf(p.x,p.y,p.z,95));const s0=new V3(1,.12,.35).normalize(),s90=new V3(0,1.07,.35).normalize();SK12.axis.crossVectors(s0,s90).normalize();
const add=(dir,size,col,ringed)=>{const g=new THREE.Group();const m=new THREE.Mesh(new THREE.SphereGeometry(size,24,16),new THREE.ShaderMaterial({uniforms:{sd:{value:new V3()},col:{value:col},op:{value:.5},ring:{value:0}},vertexShader:'varying vec3 vN;varying vec2 vUv;void main(){vUv=uv;vN=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:SKB_FS,transparent:true,depthWrite:false,fog:false}));g.add(m);
if(ringed){const rg=new THREE.Mesh(new THREE.RingGeometry(size*1.4,size*2.3,64),new THREE.MeshBasicMaterial({color:col.clone().lerp(new THREE.Color(1,1,1),.3),transparent:true,opacity:.35,side:THREE.DoubleSide,depthWrite:false,fog:false}));rg.rotation.x=1.2;rg.rotation.y=.3;g.add(rg);g.userData.rg=rg}
g.renderOrder=-4;g.traverse(o=>{o.renderOrder=-4;o.frustumCulled=false});sc.add(g);SK12.o.push({g,m,dir:dir.normalize(),col})};
// lunes de la planète
const nm=1+(r()<.45);for(let i=0;i<nm;i++)add(new V3(rv(1),.14+r()*.32,rv(1)),140+r()*160,new THREE.Color().setHSL(.08+r()*.05,.08,.55+r()*.2),false);
// planètes voisines (vraies directions)
const cx=cof(p.x),cy=cof(p.y),cz=cof(p.z);let nb=0;for(let i=-3;i<=3;i++)for(let j=-1;j<=1;j++)for(let k=-3;k<=3;k++){if(nb>=4)break;const c=cdata(cx+i,clamp(cy+j,-1,1),cz+k);const q=c.pl;if(!q||q===p||q.name===p.name)continue;const d=new V3(q.x-p.x,q.y-p.y,q.z-p.z),dl=d.length();if(dl>22000)continue;d.y=Math.abs(d.y)+dl*.15;const sz=clamp(Math.atan(q.r/dl)*3800*3,40,420);add(d,sz,new THREE.Color().setHSL(q.hue/360,.5,.55),!!q.ring);nb++}
// étoiles filantes
SK12.ss=[0,1].map(()=>{const m=new THREE.Mesh(new THREE.PlaneGeometry(1,1),new THREE.ShaderMaterial({uniforms:{a:{value:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform float a;varying vec2 vUv;void main(){float k=pow(vUv.x,2.)*(1.-abs(vUv.y-.5)*2.);gl_FragColor=vec4(vec3(1.,.95,.85)*k*a,1.);}',transparent:true,blending:ADDB,depthWrite:false,fog:false,side:THREE.DoubleSide}));m.visible=false;m.frustumCulled=false;m.renderOrder=-3;sc.add(m);return{m,l:0}})}
function sk12Tick(F,dt){const cp=camera.position,ph=typeof DN!='undefined'?DN.ph:.25,night=typeof DN!='undefined'?DN.night:0,day=typeof DN!='undefined'?DN.day:1,sd=F.sunDir,q=U3.q||(U3.q=new QT());q.setFromAxisAngle(G3.up,t*.0015);
for(const o of SK12.o){const d=U3.a.copy(o.dir).applyQuaternion(q);o.g.position.copy(cp).addScaledVector(d,4200);o.g.visible=d.y>-.05;o.m.material.uniforms.sd.value.copy(sd);o.m.material.uniforms.op.value=.28+night*.72-day*.05;if(o.g.userData.rg)o.g.userData.rg.material.opacity=.15+night*.3}
SK12.t-=dt;if(night>.4&&SK12.t<=0){SK12.t=2.5+Math.random()*6;const S2=SK12.ss.find(s=>s.l<=0);if(S2){const a=Math.random()*TAU,el=.35+Math.random()*.45,d=U3.b.set(Math.cos(a)*Math.cos(el),Math.sin(el),Math.sin(a)*Math.cos(el));S2.p=cp.clone().addScaledVector(d,3800);S2.v=U3.c.set(rv(1),-.35-Math.random()*.3,rv(1)).normalize().multiplyScalar(900+Math.random()*700).clone();S2.l=S2.ml=.7+Math.random()*.5;S2.m.visible=true}}
for(const s of SK12.ss){if(s.l<=0){s.m.visible=false;continue}s.l-=dt;s.p.addScaledVector(s.v,dt);const a=Math.sin(clamp(1-s.l/s.ml,0,1)*Math.PI);s.m.position.copy(s.p);s.m.lookAt(cp);const L=180;s.m.scale.set(L,3.2,1);const vd=U3.a.copy(s.v).normalize();s.m.material.uniforms.a.value=a*night;
// aligne la traînée sur sa direction à l'écran
const p0=U3.c.copy(s.p).project(camera),p1=U3.b.copy(s.p).addScaledVector(vd,-50).project(camera);s.m.rotateZ(Math.atan2((p0.y-p1.y)*innerHeight,(p0.x-p1.x)*innerWidth))}}
// ---------- #13 léviathans ----------
const LV3={m:null,on:false,t:30+Math.random()*25,seen:0};
function lv3Geo(){const pts=[[0,-1],[.1,-.9],[.16,-.6],[.17,-.2],[.15,.2],[.11,.55],[.06,.85],[.02,1]].map(([r,z])=>new THREE.Vector2(r,z));const b=new THREE.LatheGeometry(pts,18).rotateX(Math.PI/2);b.scale(1,.8,1);const parts=[{g:b,c:[.16,.22,.28]}];
for(let i=0;i<9;i++){const sp=new THREE.ConeGeometry(.035,.16,5).translate(0,.08,0);parts.push({g:sp,m:M4(0,.12,-.7+i*.18),c:[.3,.45,.52]})}const fl=new THREE.SphereGeometry(1,8,6);fl.scale(.35,.02,.1);parts.push({g:fl,m:M4(0,0,1.02),c:[.16,.22,.28]});
for(let i=0;i<6;i++){const s=new THREE.SphereGeometry(.03,6,4);parts.push({g:s,m:M4(i%2?.12:-.12,.06,-.6+i*.22),c:[.5,1.4,1.6]})}return mergeG(parts)}
function lv3Tick(F,dt){const ok=F.ty=='Océanique';if(!ok)return;const cp=camera.position;
if(!LV3.on){LV3.t-=dt;if(LV3.t>0)return;LV3.t=40+Math.random()*40;const fw=U3.a.set(0,0,-1).applyQuaternion(camera.quaternion);fw.y=0;fw.normalize();for(let k=0;k<50;k++){const a=Math.atan2(fw.x,fw.z)+rv(k<25?1:3),d=380+Math.random()*700,x=cp.x+Math.sin(a)*d,z=cp.z+Math.cos(a)*d;if(Math.abs(x)>1400||Math.abs(z)>1400)continue;if(F.h(x,z)>-14)continue;const dir=Math.random()*TAU;const x2=x+Math.cos(dir)*190,z2=z+Math.sin(dir)*190;if(F.h(x2,z2)>-10)continue;
if(!LV3.m){LV3.m=new THREE.Mesh(lv3Geo(),new THREE.MeshStandardMaterial({vertexColors:true,roughness:.55,metalness:.15,emissive:0x061418}));LV3.m.scale.setScalar(130);LV3.m.frustumCulled=false}SURF.scene.add(LV3.m);LV3.on=true;LV3.a=new V3(x,0,z);LV3.b=new V3(x2,0,z2);LV3.e=0;LV3.dur=7;LV3.sp=0;break}return}
LV3.e+=dt;const u=LV3.e/LV3.dur;if(u>=1){LV3.on=false;SURF.scene.remove(LV3.m);return}const P=U3.b.copy(LV3.a).lerp(LV3.b,u);P.y=Math.sin(u*Math.PI)*34-20;const P2=U3.c.copy(LV3.a).lerp(LV3.b,u+.01);P2.y=Math.sin((u+.01)*Math.PI)*34-20;LV3.m.position.copy(P);LV3.m.lookAt(P2);LV3.m.rotateY(Math.PI);
const sp=Math.floor(u*14);if(sp!==LV3.sp){LV3.sp=sp;const near=Math.abs(P.y)<14;if(near){wa3Spawn(P.x,P.z,10,60,4);for(let i=0;i<14;i++)SPK.emit(P.x+rv(20),1,P.z+rv(20),rv(18),18+Math.random()*30,rv(18),1.4,.85,.92,1,.92)}}
if(LV3.e<dt*1.5){try{tone(70,38,3.2,'sine',.12);tone(95,50,2.6,'triangle',.05,.4)}catch(e){}if(!GX('lev',{s:0}).s){G.x.lev.s=1;banner('star','Léviathan !','Une créature gigantesque vient de surgir de l\'océan','#5fd8ff')}}}
// ---------- #6 traversée des nuages (entrée atmosphérique et décollage sans écran blanc) ----------
const LD6={on:false,sc:null,cam:null,m:null,col:new THREE.Color(1,1,1)};
const LD6_FS='uniform sampler2D nz;uniform float k,tm,asp;uniform vec3 col;varying vec2 vUv;void main(){vec2 p=(vUv-.5)*vec2(asp,1.);float r=length(p),a=atan(p.y,p.x);float z=1./(r+.08);vec2 q=vec2(a*.6366,z*.12+tm*1.6);float n=texture2D(nz,q).r*.6+texture2D(nz,q*2.3+.4).r*.4;vec2 q2=p*.7+vec2(tm*.05,0.);float m=texture2D(nz,q2).r;float c=n*.55+m*.45;float cov=smoothstep(1.05-k*1.2,1.3-k*1.2,c+r*.25*k)+pow(k,4.);float lit=.82+.18*smoothstep(.2,.9,c);gl_FragColor=vec4(col*lit,clamp(cov,0.,1.)*smoothstep(0.,.08,k));}';
function ld6Init(){const sc=new THREE.Scene(),cam=new THREE.OrthographicCamera(-.5,.5,.5,-.5,-1,1),m=new THREE.Mesh(new THREE.PlaneGeometry(1,1),new THREE.ShaderMaterial({uniforms:{nz:{value:NZ3},k:{value:0},tm:TM,asp:{value:1},col:{value:LD6.col}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy*2.,0.,1.);}',fragmentShader:LD6_FS,transparent:true,depthTest:false,depthWrite:false}));m.frustumCulled=false;sc.add(m);LD6.sc=sc;LD6.cam=cam;LD6.m=m}
function ld6Tick(){const tr=(S.entry&&FADE.tg==1)||(S.ascent&&FADE.tg==1);if(tr&&!LD6.on){LD6.on=true;const p=S.entry&&S.entry.p;if(p){LD6.col.setHSL(((p.hue+15)%360)/360,.25,.92)}else LD6.col.setRGB(.9,.94,1)}if(LD6.on&&FADE.tg==0&&FADE.v<.004)LD6.on=false;FADE.cloud=LD6.on}
{const _rfL=renderFrame;renderFrame=function(){_rfL();if(LD6.on&&FADE.v>.003){if(!LD6.sc)ld6Init();const u=LD6.m.material.uniforms;u.k.value=FADE.v;u.asp.value=innerWidth/innerHeight;const ac=R3.autoClear;R3.autoClear=false;R3.render(LD6.sc,LD6.cam);R3.autoClear=ac}}}
// ---------- entrée sur une planète / boucle ----------
function surf3Enter(F,sc){U3.F=F;CS3.m=null;CT3.on=false;BI3.on=false;WA3.mat=null;WA3.foam=null;LV3.on=false;LV3.m&&LV3.m.parent&&LV3.m.parent.remove(LV3.m);
const T=(n,f)=>{try{f()}catch(e){console.warn(n,e)}};T('nuages',()=>cs3Build(F,sc));T('ville',()=>ct3Build(F,sc));T('bio',()=>bi3Build(F,sc));T('eau',()=>{wa3Patch(F);if(F.ty!='Glacée'&&F.ty!='Volcanique')wa3Foam(sc)});T('ciel',()=>sk12Build(F,sc));T('vent',()=>w11Apply(sc))}
{const _se3=SURF.enter;SURF.enter=function(p,entry){_se3(p,entry);try{const F=typeof GR!='undefined'&&GR&&GR.F;if(F)surf3Enter(F,SURF.scene)}catch(e){console.warn(e)}}}
TICK.push(dt=>{ld6Tick();if(mode!='surf'||!U3.F)return;const F=U3.F;try{cs3Tick(F);ct3Tick(dt);bi3Tick(dt);wa3Tick(dt);w11Tick(F);sk12Tick(F,dt);lv3Tick(F,dt)}catch(e){console.warn(e)}});
{const _ovS3=overlay;overlay=function(){_ovS3();if(mode=='surf'&&CS3.inside>.02){const W=innerWidth,H=innerHeight,c=CS3.m?CS3.m.material.uniforms.lit.value:U3.col.setRGB(1,1,1);OX.fillStyle=`rgba(${c.r*230|0},${c.g*235|0},${c.b*240|0},${Math.min(.92,CS3.inside*.95)})`;OX.fillRect(0,0,W,H)}}}
// les villes se voient aussi de l'espace (même règle sur PC et mobile)
{const _bg3=buildPlanetGPU;buildPlanetGPU=function(p){const g=_bg3(p);try{const U=g.userData.U;if(U&&U.city&&pvar(p)!='ruines'){const L=planetLook(p);if(L.city)U.city.value=ct3Inhab(p)?1:0}}catch(e){}return g}}
