// ===== OUTILS DE VAISSEAU ET MÉTIERS : laser de minage, rayon tracteur, scanner longue portée, sondes ; astéroïdes riches, conteneurs dérivants ; vaisseaux spécialisés =====
Object.assign(WPN,{drill:{n:'Laser de minage',ic:'⛏',price:4500,lv:2,d:'Rayon continu : mine 4× plus vite et perce les astéroïdes riches. Faible contre les vaisseaux.'},tractor:{n:'Rayon tracteur',ic:'🧲',price:3800,lv:2,d:'Maintiens le tir : attire le butin, les minerais et les conteneurs de très loin.'},
scanner:{n:'Scanner longue portée',ic:'📡',price:3000,lv:1,d:'Maintiens le tir : révèle les minerais, les conteneurs cachés, les anomalies et les épaves.'},probe:{n:'Sondes',ic:'🛰',price:5000,lv:3,am:'probe',d:'Une sonde file droit devant sur 12 km et cartographie les planètes et les stations qu\'elle croise.'}});
AMMO.probe={n:'3 sondes',q:3,price:600};CRAFT_AMMO.probe={m:{elec:2,metal:2},fee:150,lv:3};if(G.ammo.probe==null)G.ammo.probe=0;
Object.assign(WSVG,{drill:'drill',tractor:'magnet',scanner:'pulse',probe:'probe'});applyPerks();
// ----- vaisseaux spécialisés (et uniques, gagnés avec les missions de faction) -----
Object.assign(HULLS,{prospecteur:{n:'Prospecteur',hp:1.25,spd:.9,turn:.85,cap:32,dmg:.9,price:16000,lv:4,rep:['guilde',1],desc:'Vaisseau minier : laser de minage +60 %, rayon tracteur +50 %.',tool:{drill:1.6,tractor:1.5}},
explorateur:{n:'Éclaireur Pathfinder',hp:.95,spd:1.2,turn:1.15,cap:18,dmg:.95,price:18000,lv:5,rep:['carto',1],desc:'Fait pour l\'exploration : scanner ×2, sondes plus rapides, voyages rapides −25 %.',tool:{scan:2,probe:1.4,trav:.75}},
sentinelle:{n:'Sentinelle',hp:2,spd:1.1,turn:1.1,cap:25,dmg:1.85,price:0,uniq:'alliance',desc:'Chasseur d\'élite offert par l\'Alliance aux héros de l\'Opération Bouclier.'},
mastodonte:{n:'Mastodonte',hp:2.3,spd:.85,turn:.75,cap:60,dmg:1.3,price:0,uniq:'guilde',desc:'Le cargo-foreuse légendaire de la Guilde : soute géante, laser de minage ×2.',tool:{drill:2,tractor:1.8}}});applyPerks();
Object.assign(SHIPN,{prospecteur:'Prospecteur',explorateur:'Pathfinder',sentinelle:'Sentinelle',mastodonte:'Mastodonte'});
const toolK=k=>{const T=HS().tool;return T&&T[k]||1};
TICK.push(()=>{TRAVK=(1-rankOf('carto')*.08)*toolK('trav')});
{const BASEH={prospecteur:'cargo',explorateur:'intercepteur',sentinelle:'faucon',mastodonte:'leviathan'};const _b=buildShip;
buildShip=function(...a){const h=G.ship,bh=BASEH[h];if(!bh)return _b(...a);G.ship=bh;let r;try{r=_b(...a)}finally{G.ship=h}try{shipDeco(r,h)}catch(e){console.warn(e)}return r}}
function shipDeco(root,h){const b=root.userData.body,P=(G.parts||{}).paint;const PAL={prospecteur:[0xd98c2a,0x3a3f46],explorateur:[0xeef2f4,0x1fa59a],sentinelle:[0x203a6e,0xd8ad48],mastodonte:[0xe8b820,0x2a2a2e]}[h];
if(!P||P=='std')b.traverse(o=>{if(o.isMesh&&o.material&&o.material.name=='hull'){o.material=o.material.clone();o.material.color.setHex(PAL[0])}else if(o.isMesh&&o.material&&o.material.name=='wing'){o.material=o.material.clone();o.material.color.setHex(PAL[1])}});
const M=new THREE.MeshStandardMaterial({color:PAL[0],map:HULLT,metalness:DESK?.6:.3,roughness:.4}),A=new THREE.MeshStandardMaterial({color:PAL[1],metalness:.55,roughness:.4}),D=new THREE.MeshStandardMaterial({color:0x2a3038,metalness:.6,roughness:.45}),GL=new THREE.MeshBasicMaterial({color:h=='explorateur'?0x6ff8ff:h=='sentinelle'?0xffe08a:0xffa040});
const add=(g,m,x,y,z,rx=0,ry=0,rz=0)=>{const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.rotation.set(rx,ry,rz);b.add(o);return o};
if(h=='prospecteur'||h=='mastodonte'){const k=h=='mastodonte'?1.25:1;add(new THREE.CylinderGeometry(.9*k,1.1*k,3*k,10).rotateX(Math.PI/2),D,0,-1.4,-7.6*k);const cone=add(new THREE.ConeGeometry(.9*k,2.6*k,10).rotateX(-Math.PI/2),A,0,-1.4,-10.2*k);cone.userData.spin=1;root.userData.drillBit=cone;
for(const s of[-1,1]){add(new THREE.BoxGeometry(1.4,1.4,3.6),A,s*2.2,-1.5,-5.2);add(new THREE.CylinderGeometry(.5,.5,4,8).rotateX(Math.PI/2),M,s*4.6,.4,1)}if(h=='mastodonte')for(let i=0;i<5;i++)add(new THREE.BoxGeometry(4.2,.22,.5),i%2?D:A,0,2.25,-2+i*1.2)}
else if(h=='explorateur'){add(new THREE.CylinderGeometry(.06,.06,4.5,5),D,0,2.4,1.5);const dish=add(new THREE.SphereGeometry(1.1,14,8,0,TAU,0,Math.PI*.35),M,0,4.4,1.5,Math.PI*.9,0,0);for(const s of[-1,1]){add(new THREE.CylinderGeometry(.35,.35,3.4,8).rotateX(Math.PI/2),A,s*2.6,-.6,-2.4);add(new THREE.SphereGeometry(.3,8,6),GL,s*2.6,-.6,-4.2)}const tip=sprite(0x6ff8ff,3);tip.position.set(0,4.7,1.5);b.add(tip)}
else if(h=='sentinelle'){for(const s of[-1,1]){add(new THREE.BoxGeometry(3.2,.18,2.4),A,s*5.6,.2,2.6,0,s*-.3,s*.2);add(new THREE.BoxGeometry(.16,2,2.6),M,s*2.2,1.3,3.6,0,0,s*.5);add(new THREE.BoxGeometry(.5,.12,3.4),GL,s*3.4,.35,1.4,0,s*-.15,0)}add(new THREE.BoxGeometry(.4,.4,4),GL,0,1.4,-1.2)}}
// ----- crochet de tir : les outils remplacent l'arme courante -----
const TS={drillB:null,trB:null,acc:0,chg:0,cd:0,pulse:null,reveal:0,revR:0,prb:[],snd:0};let DRILLING=false;
{const _fw=fireW;fireW=function(dt,TG){const w=curW(),f=TOOLF[w];if(!f){toolOff();return _fw(dt,TG)}LZ.on=0;fcd-=dt;if(w!='drill'&&TS.drillB)hideBeam(TS.drillB);if(w!='tractor'&&TS.trB)hideBeam(TS.trB);f(dt,TG,isFire()&&!S.docked&&!S.entry&&!S.ascent&&!S.dead)}}
function toolOff(){if(TS.drillB)hideBeam(TS.drillB);if(TS.trB)hideBeam(TS.trB);TS.chg=0}
const nosePt=()=>{const sc=ship.userData.body.scale;return _c1.set(0,-1.1*sc.y,-9*sc.z).applyQuaternion(S.q).add(S.pos)};
function rayPick(o,dir,R,TG,filter){let best=null,bt=R;for(const T of TG){if(T.dead||T.gone||(filter&&!filter(T)))continue;const r=(T.r||8)*1.05;_c2.copy(T.pos).sub(o);const tc=_c2.dot(dir);if(tc<0||tc>R+r)continue;const d2=_c2.lengthSq()-tc*tc;if(d2>r*r)continue;const th=tc-Math.sqrt(Math.max(0,r*r-d2));if(th<bt){bt=th;best=T}}return best?{T:best,d:Math.max(0,bt)}:null}
const TOOLF={
drill(dt,TG,on){if(!on){if(TS.drillB)hideBeam(TS.drillB);return}const o=nosePt().clone(),R=950;fwd();let dir=_f.clone();if(lock&&lock.pos.distanceTo(S.pos)<R){const ld=lock.pos.clone().sub(o).normalize();if(ld.dot(dir)>.9)dir=ld}
const hit=rayPick(o,dir,R,TG);const end=hit?o.clone().addScaledVector(dir,hit.d):o.clone().addScaledVector(dir,R);if(!TS.drillB)TS.drillB=mkBeam(0xffa030);placeBeam(TS.drillB,o,end,.55,!!hit);if(ship.userData.drillBit)ship.userData.drillBit.rotation.z+=dt*30;
TS.snd-=dt;if(TS.snd<=0){TS.snd=.11;tone(jit(140),jit(120),.12,'sawtooth',.03)}if(!hit)return;const T=hit.T,ast=T.isAst||T.rich,dps=(ast?12:1.6)*(1+.3*(G.u[0]-1))*toolK('drill');TS.acc+=dps*dt;if(Math.random()<.6)SPK.emit(end.x,end.y,end.z,rv(40),rv(40),rv(40),.35,1,.7,.3,.4);
if(TS.acc>(ast?.5:.4)){DRILLING=true;try{T.hit(TS.acc,end.clone())}finally{DRILLING=false}TS.acc=0}},
tractor(dt,TG,on){if(!on){if(TS.trB)hideBeam(TS.trB);return}fwd();const R=1100*toolK('tractor'),o=nosePt().clone();let near=null,nd=1e9;
for(const d of DROPS){const v=_c2.copy(S.pos).sub(d.p),dd=v.length();if(dd>R)continue;if(-v.dot(_f)/dd<.35&&dd>120)continue;d.v.addScaledVector(v.normalize(),1500*dt);d.l=Math.max(d.l,5);if(dd<nd){nd=dd;near=d.p}}
for(const C of CONT.act.values()){if(!C.found||C.opened)continue;const v=_c2.copy(S.pos).sub(C.pos),dd=v.length();if(dd>R)continue;if(-v.dot(_f)/dd<.35&&dd>120)continue;C.pos.addScaledVector(v.normalize(),Math.min(dd,260*dt));if(dd<nd){nd=dd;near=C.pos}}
if(!TS.trB)TS.trB=mkBeam(0x6fd8ff);if(near){placeBeam(TS.trB,o,near,.4,false)}else placeBeam(TS.trB,o,o.clone().addScaledVector(_f,R*.6),.25,false);TS.snd-=dt;if(TS.snd<=0){TS.snd=.25;tone(jit(320),jit(380),.22,'sine',.02)}},
scanner(dt,TG,on){if(TS.cd>0){TS.cd-=dt;TS.chg=0;return}if(!on){TS.chg=Math.max(0,TS.chg-dt*2);return}TS.chg+=dt;if(Math.random()<dt*6)tone(600+TS.chg*900,700+TS.chg*900,.06,'sine',.02);if(TS.chg>=1){TS.chg=0;TS.cd=6;scanPulse()}},
probe(dt,TG,on){if(!on||fcd>0)return;if((G.ammo.probe||0)<=0){fcd=1.2;toast('Plus de sondes — achète-en en station (onglet Armes)');return}fcd=1.2;G.ammo.probe--;probeLaunch()}};
{const _wh=wpnHUD;wpnHUD=function(){let s=_wh();const w=curW();if(w=='scanner')s+=TS.cd>0?` <small>recharge ${Math.ceil(TS.cd)} s</small>`:` <span class="heat"><i style="width:${(TS.chg*100).toFixed(0)}%;background:#6ef"></i></span>`;if(w=='probe')s=s.replace(/<b>\d+<\/b>/,`<b>${G.ammo.probe||0}</b>`);return s}}
// ----- scanner : onde de balayage -----
const PULSEM=new THREE.ShaderMaterial({uniforms:{op:{value:0}},vertexShader:AVS,fragmentShader:'uniform float op;varying vec3 vNV;void main(){float f=pow(1.-abs(vNV.z),3.);gl_FragColor=vec4(vec3(.35,.85,1.)*f*op,1.);}',transparent:true,blending:ADDB,depthWrite:false,side:THREE.DoubleSide});
function scanPulse(){const R=4000*toolK('scan');if(!TS.pulse){TS.pulse=new THREE.Mesh(new THREE.SphereGeometry(1,40,24),PULSEM);TS.pulse.frustumCulled=false}scene.add(TS.pulse);TS.pulse.position.copy(S.pos);TS.pt=0;TS.reveal=t+16;TS.revR=R;TS.revP=S.pos.clone();STS.scans++;tone(300,1800,.6,'sine',.08);tone(900,2400,.4,'triangle',.04,.1);
let n=0;for(const C of CONT.act.values()){if(!C.found&&C.pos.distanceTo(S.pos)<R){C.found=1;CONT.save(C);n++}}if(n){toast('📡 '+n+' conteneur'+(n>1?'s':'')+' dérivant'+(n>1?'s':'')+' détecté'+(n>1?'s':'')+' !');cxAdd('an','cont')}
let rich=0;for(const R2 of RICH.act.values())if(!R2.gone&&R2.pos.distanceTo(S.pos)<R){rich++;cxAdd('an','rich')}if(rich)setTimeout(()=>toast('📡 Astéroïde riche à proximité : sors le laser de minage'),900);
if(typeof anScan=='function')anScan(S.pos,R*3);if(typeof derScan=='function')derScan(S.pos,R*3)}
function updPulse(dt){if(!TS.pulse||!TS.pulse.parent)return;TS.pt+=dt;const k=TS.pt/1.3;if(k>=1){scene.remove(TS.pulse);return}TS.pulse.scale.setScalar(20+TS.revR*k);PULSEM.uniforms.op.value=(1-k)*.9}
// ----- sondes -----
const PRBG=new THREE.SphereGeometry(1.2,10,8),PRBM=new THREE.MeshStandardMaterial({color:0xdfe6ee,metalness:.7,roughness:.3});
function probeLaunch(){fwd();const m=new THREE.Mesh(PRBG,PRBM);for(let i=0;i<3;i++){const a=new THREE.Mesh(new THREE.CylinderGeometry(.05,.05,3.2,4),PRBM);a.rotation.z=i*1.05;m.add(a)}const s=sprite(0x6ff8ff,10);m.add(s);m.position.copy(nosePt());scene.add(m);
TS.prb.push({m,pos:m.position,v:_f.clone().multiplyScalar(650*toolK('probe')).addScaledVector(S.vel,.3),l:20,s,ck:''});SFX.missile();toast('🛰 Sonde lancée')}
function updProbes(dt){for(const P of TS.prb){P.l-=dt;P.pos.addScaledVector(P.v,dt);P.s.visible=Math.sin(t*12)>0;if(Math.random()<.5)SPK.emit(P.pos.x,P.pos.y,P.pos.z,rv(5),rv(5),rv(5),.4,.4,.9,1,.3);
const cx=cof(P.pos.x),cy=cof(P.pos.y),cz=cof(P.pos.z),k=cx+','+cy+','+cz;if(k!==P.ck){P.ck=k;for(let i=-1;i<=1;i++)for(let j=-1;j<=1;j++)for(let l=-1;l<=1;l++){if(Math.abs(cy+j)>1)continue;const c=cdata(cx+i,cy+j,cz+l);
if(c.pl&&!G.disc.has(c.pl.name)&&Math.hypot(c.pl.x-P.pos.x,c.pl.y-P.pos.y,c.pl.z-P.pos.z)<c.pl.r+2600){const p=c.pl;G.disc.add(p.name);G.dpos[p.name]=[p.x|0,p.y|0,p.z|0,p.hue|0,p.ring?1:0,p.r|0];G.cr+=30;gainXP(20);addRep('carto',10);STS.probes++;toast('🛰 Sonde : planète '+p.name+' cartographiée (+30 ¢)');SFX.disc()}
if(c.st&&!G.vst.some(v=>v.n==c.st.n)&&Math.hypot(c.st.x-P.pos.x,c.st.y-P.pos.y,c.st.z-P.pos.z)<3000){G.vst.push({n:c.st.n,x:c.st.x|0,y:c.st.y|0,z:c.st.z|0});toast('🛰 Sonde : '+c.st.n+' ajoutée à la carte (voyage rapide)');SFX.disc()}}
if(typeof anScan=='function')anScan(P.pos,3000);if(typeof derScan=='function')derScan(P.pos,3000)}
if(P.l<=0){boom3(P.pos,10,0x6ff8ff,40);scene.remove(P.m)}}TS.prb=TS.prb.filter(P=>P.l>0)}
// ===== astéroïdes riches et conteneurs dérivants (un par secteur, selon le hasard du secteur) =====
const RICHD=GX('rich',{}),CONTD=GX('cont',{});
const RICH={act:new Map()},CONT={act:new Map(),save(C){CONTD[C.k]=C.opened?'o'+Date.now():'f'}};
const RICHM=new THREE.MeshStandardMaterial({color:0x2c2622,roughness:.85,metalness:.15,flatShading:true});
function richMesh(min){const g=new THREE.Group(),c=MINC[min],m=new THREE.Mesh(AGEO[3],RICHM);g.add(m);const cm=new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:.9,metalness:.3,roughness:.2});
for(let i=0;i<14;i++){const s=new THREE.Mesh(new THREE.OctahedronGeometry(.12+Math.random()*.1,0),cm);const d=new V3(rv(1),rv(1),rv(1)).normalize();s.position.copy(d).multiplyScalar(.92);s.lookAt(d.clone().multiplyScalar(3));s.scale.z=2.4;g.add(s)}const gl=sprite(c,3.2,.5);g.add(gl);return g}
function contMesh(){const g=new THREE.Group(),M=new THREE.MeshStandardMaterial({color:0xb87a2a,map:HULLT,metalness:.5,roughness:.5}),D=new THREE.MeshStandardMaterial({color:0x2a3038,metalness:.6,roughness:.5});
g.add(new THREE.Mesh(new THREE.BoxGeometry(6,4,9),M));for(const z of[-3.6,0,3.6]){const r=new THREE.Mesh(new THREE.BoxGeometry(6.3,4.3,.5),D);r.position.z=z;g.add(r)}const b=sprite(0xffc040,9);b.position.y=3.2;g.add(b);g.userData.bl=b;return g}
function richPos(c){const a=c.ast[(h3(c.cx,c.cy,c.cz,201)*c.ast.length)|0],r=30+h3(c.cx,c.cy,c.cz,203)*10,k=(a.r+r+45)/1.45;return new V3(a.x+k,a.y+k*.3,a.z-k)}
function richHit(R,d,p){if(R.gone)return;const k=DRILLING?1:.12;R.hp-=d*k;const c=new THREE.Color(MINC[R.min]);for(let i=0;i<(DRILLING?3:6);i++){const v=new V3(rv(1),rv(1),rv(1)).normalize().multiplyScalar(40+Math.random()*60);SPK.emit(p.x,p.y,p.z,v.x,v.y,v.z,.45,c.r,c.g,c.b,.4)}if(!DRILLING&&Math.random()<.08)toast('Trop dur pour tes canons : utilise un laser de minage');SFX.mineTick();
R.mesh.scale.setScalar(R.r*(.7+.3*Math.max(0,R.hp/R.mhp)));if(R.hp<=0){R.gone=1;RICHD[R.k]=Date.now();boom3(R.pos,40,MINC[R.min],90,true);SFX.rock();spawnDrops(R.pos,16,R.min);spawnDrops(R.pos,5,R.min=='or'?'cristal':'or');scene.remove(R.mesh);toast('⛏ Astéroïde riche foré ! Ramasse le minerai');gainXP(80);addRep('guilde',40);cxAdd('an','rich');save()}}
function sectorObjs(){for(const[k,e]of SMALL){const c=e.c;if(c.sun)continue;
if(c.ast.length>18&&!RICH.act.has(k)){const done=RICHD[k];if(!done||Date.now()-done>2*3600e3){const min=h3(c.cx,c.cy,c.cz,202)<.5?'or':'cristal',r=30+h3(c.cx,c.cy,c.cz,203)*10;const R={k,min,r,hp:45+danger()*10,mhp:0,pos:richPos(c),gone:false};R.mhp=R.hp;R.mesh=richMesh(min);R.mesh.scale.setScalar(r);R.mesh.position.copy(R.pos);R.pos=R.mesh.position;scene.add(R.mesh);
R.tg={pos:R.pos,r:r,max:1500,cone:.16,w:1,isAst:1,rich:1,hit:(d,p)=>richHit(R,d,p)};RICH.act.set(k,R)}}
if(!CONT.act.has(k)&&h3(c.cx,c.cy,c.cz,211)<.3&&Math.abs(c.cx)+Math.abs(c.cz)>0){const st=CONTD[k];if(st&&st[0]=='o'&&Date.now()-(+st.slice(1))<4*3600e3)continue;const ox=c.cx*CS,oy=c.cy*CS,oz=c.cz*CS,C={k,found:st=='f',opened:false,pos:new V3(ox+600+h3(c.cx,c.cy,c.cz,212)*(CS-1200),oy+CS/2+(h3(c.cx,c.cy,c.cz,213)-.5)*1500,oz+600+h3(c.cx,c.cy,c.cz,214)*(CS-1200))};C.mesh=contMesh();C.mesh.position.copy(C.pos);C.pos=C.mesh.position;C.mesh.rotation.set(rv(1),rv(3),rv(1));scene.add(C.mesh);CONT.act.set(k,C)}}
for(const[k,R]of RICH.act)if(!SMALL.has(k)){if(R.mesh.parent)scene.remove(R.mesh);RICH.act.delete(k)}for(const[k,C]of CONT.act)if(!SMALL.has(k)){if(C.mesh.parent)scene.remove(C.mesh);CONT.act.delete(k)}}
function contOpen(C){C.opened=1;CONT.save(C);scene.remove(C.mesh);boom3(C.pos,18,0xffc040,50);SFX.win();const cr=150+Math.floor(Math.random()*300);G.cr+=cr;let txt='+'+cr+' ¢';const pool=Math.random()<.25?ILLG.map(g=>g.id):['metal','elec','med','lux','fuel','titane','cristal'],id=pool[Math.random()*pool.length|0],q=Math.min(2+(Math.random()*5|0),cap()-cargoUsed());
if(q>0){G.cargo[id]=(G.cargo[id]||0)+q;txt+=' · '+q+' '+matG(id).n}toast('📦 Conteneur récupéré : '+txt);gainXP(40);addRep('carto',15);if(Math.random()<.08+rankOf('carto')*.02)setTimeout(giveBlueprint,1200);save()}
let SOT=0;STICK.push(dt=>{SOT-=dt;if(SOT<=0){SOT=.5;sectorObjs()}updPulse(dt);updProbes(dt);
for(const R of RICH.act.values()){if(R.gone)continue;R.mesh.rotation.y+=dt*.05;const d=S.pos.distanceTo(R.pos),rr=R.r*.95+6;if(d<rr){_c2.copy(S.pos).sub(R.pos).normalize();S.pos.copy(R.pos).addScaledVector(_c2,rr);const rad=S.vel.dot(_c2);if(rad<0){S.vel.addScaledVector(_c2,-1.5*rad);S.spd*=.5;if(rad<-50)damage(4,'col')}}}
for(const C of CONT.act.values()){if(C.opened)continue;const d=S.pos.distanceTo(C.pos);C.mesh.visible=C.found||d<220;C.mesh.rotation.y+=dt*.1;C.mesh.userData.bl.visible=Math.sin(t*5)>0;if(!C.found&&d<120){C.found=1;CONT.save(C)}if(d<32&&!S.dead)contOpen(C)}});
{const _st=spaceTargets;spaceTargets=function(){const r=_st();for(const R of RICH.act.values())if(!R.gone)r.push(R.tg);return r}}
// ----- HUD : révélations du scanner, conteneurs, sondes -----
{const _ov=overlay;overlay=function(){_ov();if(mode!='space'||S.dead)return;const rev=t<TS.reveal;if(rev){let n=0;const L=asts.filter(a=>!a.gone&&a.pos.distanceTo(TS.revP)<TS.revR*.6).sort((a,b)=>a.pos.distanceTo(S.pos)-b.pos.distanceTo(S.pos));for(const a of L){if(n++>36)break;const mn=astMin(a),g=GOODS.find(x=>x.id==mn);label({x:a.pos.x,y:a.pos.y+a.r+10,z:a.pos.z},g.ic+' '+g.n,'#'+MINC[mn].toString(16).padStart(6,'0'),3500)}}
{const RL=[...RICH.act.values()].filter(R=>!R.gone&&R.pos.distanceTo(S.pos)<(rev?4000:1500)).sort((a,b)=>a.pos.distanceTo(S.pos)-b.pos.distanceTo(S.pos)).slice(0,2);for(const R of RL){const g=GOODS.find(x=>x.id==R.min);edgeMarker({x:R.pos.x,y:R.pos.y+R.r+20,z:R.pos.z},'#'+MINC[R.min].toString(16).padStart(6,'0'),'Astéroïde riche · '+g.n,'⛏')}}
{const CL=[...CONT.act.values()].filter(C=>C.found&&!C.opened&&C.pos.distanceTo(S.pos)<4500).sort((a,b)=>a.pos.distanceTo(S.pos)-b.pos.distanceTo(S.pos)).slice(0,3);for(const C of CL)edgeMarker(C.pos,'#ffc040','Conteneur','📦')}
if(curW()=='scanner'&&TS.chg>0){const W=innerWidth,H=innerHeight;OX.strokeStyle='rgba(110,230,255,.8)';OX.lineWidth=3;OX.beginPath();OX.arc(W/2,H/2,40,-Math.PI/2,-Math.PI/2+TAU*TS.chg);OX.stroke()}}}
{const _mr=mpRadar;mpRadar=function(blip){_mr(blip);if(mode!='space')return;for(const C of CONT.act.values())if(C.found&&!C.opened)blip(C.pos,'#ffc040',2.4,true);for(const R of RICH.act.values())if(!R.gone)blip(R.pos,'#'+MINC[R.min].toString(16).padStart(6,'0'),3.4);for(const P of TS.prb)blip(P.pos,'#6ff8ff',1.8,true)}}
